### ISSUE TITLE
GPL-791 As developers we would like to rationalise the printing templates

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#100]
**User story**
As developers we would like to rationalise the printing templates. Currently there are 18 printing templates a lot of which are similar and could be merged.

https://ssg-confluence.internal.sanger.ac.uk/display/PSD/Sequencescape+printing+rationalisation

**Who are the primary contacts for this story**
Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by KatyTaylor** [comment]
We can deprecate this as it's covered by https://github.com/sanger/General-Backlog-Items/issues/124
