### ISSUE TITLE
GPL-796	Beckman go live with Robots CP 3 & CP4 check list

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#101]
**Description**
Task list of work to be done get first to Beckman robotics live Robots CP 3 (Serial number 9) & CP4 (serial number 10)

**Who the primary contacts are for this work**
Lesley S
Scott T
Iraad
Ian J
Vernon

May close this ticket soon as is getting crufty. The to do list for that we have dependency with Beckman (S. Blob): https://lucid.app/lucidchart/invitations/accept/79addef0-4f6e-41b9-b584-d7666fb9b24a  

**WIP 12th Jan **
- [ ] *ISSUE?* Stock plate in SS - ns (possibly uploaded by Deb P) - document this
- [ ] Training Starts on 11th for 2 weeks - R&D / Ops - Inc logistics for Box Buster (WIP)
- [ ] Check into github the SAT passed version of the script (UAT & PROD) - Beckman
- [ ] Complete Transition To Live documents for IT systems - rl15
- [ ] Check  first 4 prod runs:  Destination plate barcodes are HT-111145 to 48, Scott will run them in that order)
- [x] a.Events ok
- [x] b.Migration from yesterday to PROD is good
- [x] c.Crawler inserted into DART overnight (1am)
- [ ] d.Duplicate plates in DART - understand this + document (latest is the one to pick)
- [x] e.Check Excel +ves report 'LIMS submission'  - Eduardo

TO DO

- [ ] View view_robot_status to have timestamp to give utilization  - rl15
- [ ] Human readable barcode in destination plate barcode event - JG
- [ ] No event if no plate map for source plate - Beckman (Risk controlled via Box Buster) - andrew

**DONE**
- [x] Fast track a 384 starting at ~16:45pm First production run - End to end run of occupancy ~27 +ves / plate with 21 plates (Gives us throughput / week) 4 runs in total, first expected to complete at 17:30
- [x] Change CP3 & CP4 client machines to point at Prod - Beckman (ISSUE: with permission reported at 17:35 ticket raised with DSA team Incident [.287247]) - Waiting on Mike A from DSA mail of 10:24 is ok.
- [x] Understand why a well property 'Source_coordinate' is missing from DART MIke mailed at 16:24 is fine.
- [x] Re-schedule the crawler nightly run, with the --add-to-dart flag enabled - Harry/ Eduardo
- [x] Do: Migrations fit to pick & plate maps into PRODUCTION DART from 17th December - On Monday the 11th - Philip/Eduardo ([pj] only running migration from the 6th to the 9th of Jan 2021 since this period covers the plates for live testing)
- [x] Beckman scripts to point at production URLS - Beckman (Needs to be Mike) (WIP 8th Jan)
- [x] SOPs Expected Monday - R&D / Ops (WIP)
- [x] Tab in Lighthouse UI hidden - Harry/ Eduardo
- [x] ISSUE: FCE PROD no ACL rule to DART prod database (Cherwell 287367)
- [x] Deploy all docker stack
- [x] Check & change end points are not toggled off for Beckmen in production - Harry/ Eduardo
- [x] Test: On UAT after 11am on 8th: Migrations fit to pick & plate maps into PRODUCTION DART from 17th December - psd (Alex/Philip/Andrew/Katy/Eduardo) : https://docs.google.com/document/d/1wZCdG2p1qG6sUV_qEeuxGcfND1MATYTyYpvlDlLwUMQ/edit?usp=sharing
- [x] Check load is healthy (WIP - 8th Jan) Katy / Andrew
- [x] Re check if prod backed up - Philip (mailed Aftab at 13:57)
- [x] Sign of SAT (for CP3 & 4)  - Ian J
- [x] Clarify how far back to pick from - John S / Ian J / Rich L 
- [x] Check data from CP4 run + events (post script modification )
- [x] Clarify if can back load date for dates and them go back further - - psd (Philip/ Alex) - Fixed at 17th Dec currently and this is ok to go live (7th Jan 4:30pm meeting)
- [x] Put missing views in place in DART prod to match UAT - psd (Eduardo/ Harry) - PSD dont have definitions have request DSA team to help - doing in next hour (15:30)
- [x] Register robots as user in LabWhere
- [x] Plate is going to output stack  - possibly wrong behaviour R&D decision - FIXED on 2 of robots (CP 3 & 4 but not tested) - R & D - But issue that now send plates have data but no +ves going back start cytomat (possibly retesting PM 7th)
- [x] Complexity with partly used source plates goes back to input - R&D happy to handle via SOP

**DEPRECATED**
- [ ]  Missing control source plate subject events - 
- [ ] Tweak GPL-711 so can backload plate map data between dates (WIP on 7th Jan)
- [ ] Migrations of mongo +ves only (Need space to test either DSA or FCE) (Alex/Philip)
- [ ] Crawler needs updating to look at  view_plate_maps (is looking at LIMS_test_plate_status)  Chris F on 11th at 4:30 - Became GPL-805

**Additional context or information**
How we expect the dual running to look: https://lucid.app/lucidchart/invitations/accept/86d628ab-6308-4b9c-965d-35c53aca0148 

From events work: See outcome of checks here - stuff to follow up on - https://docs.google.com/document/d/19uW73oDHnWO7UOcUuzlLiYUTE1uuRCohdEcFG7LlkM8/edit?usp=sharing 

From slack chat: https://docs.google.com/document/d/1LycwFO6IEvp-762rF1MpTsmOv3ZgxMLFFycjP4rw6vw/edit?usp=sharing

**Comment by KatyTaylor** [comment]
https://ssg-confluence.internal.sanger.ac.uk/display/PSD/Checking+Beckman+cherrypicking+%27Add+to+DART%27+migration

Log of checking prod migration numebrs
