### ISSUE TITLE
GPL-800	[Parent backlog item] New Lighthouse labs beyond MK, AP, CB, GLS & Randox [Heron]

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#102]
**Description**
Token for a conversation to have

**Who the primary contacts are for this work**
John S

**Knowledge or Stake holders**
Possible labs

- [ ]  IP5 Lab (Newport Wales) 

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by rl15** [comment]
Keith A wrote (Wednesday, 17 March 2021 at 09:46)

At this stage we are looking at getting up to 3 more LHs online in stages. Brant’s Bridge (Brbr) will be the one coming up first as they are already testing at low volumes and are keen to send soon.
 
I hope to have all requirements for Brbr by end of the week and will send over as a full pack. I will also set up an SFTP for them using the current format.

**Comment by rl15** [comment]
From slack on 19th March 

Brants Bridge (Lighthouse Lab) | BRBR 
Lemington Spa (Lighthouse Lab) | LSPA  
Plymouth (Lighthouse Lab) | PLYM

**Comment by rl15** [comment]
In weekly Heron project team on 24th new labs required by end of April. Expecting each lab to take 2 weeks to go from sending standards document to working file parse in production. Recommend splitting this into three backlog items; one for each lab.

**Comment by rl15** [comment]
Keith A wrote (Monday, 19 April 2021 at 20:35)


Lighthouse | COG-UK ID | SFTP | Plate Barcode
-- | -- | -- | --
HSL | HSLL | /project-heron_hsl | HSL123456
Plymouth | PLYM | /project-heron_plym | ??
Brants Bridge | BRBR | /project-heron_brbr | 95040456000420400
Leamington Spa | LSPA | /project-heron_lspa | ?

**Comment by rl15** [comment]
Plymouth have uploaded a test file to their directory already.

**Comment by harrietc52** [comment]
HSL Centre added in Sequencescape [GPL-985-2](https://github.com/sanger/sequencescape/issues/3164) and Crawler [GPL-985-1](https://github.com/sanger/crawler/issues/316)

**Comment by harrietc52** [comment]
Before starting on adding next center, regroup with James re Phils comment [here](https://github.com/sanger/sequencescape/pull/3165#pullrequestreview-644405933)

**Comment by harrietc52** [comment]
28.04.21 
Ticket to systems asking 
```
/project-heron_plym
/project-heron_brbr
/project-heron_lspa
```
to also be created, with read permissions, along with `/project-heron_hsl`

**Comment by rl15** [comment]
>Alan K wrote (Thursday, 20 May 2021 at 09:42) 

>Brants bridge went live this week but are sending them to PHE until they fit our requirements... will update timeline then but probably 3 weeks.
 
>Leamington Spa plan to start testing in June with cherry picking a month after that. I’d put end of July as [potential] date.

**Comment by rl15** [comment]
24th May 10 am meeting expecting o receive samples from Newcastle. Timeline TBD

**Comment by rl15** [comment]
Alan K wrote (Wednesday, 2 June 2021 at 09:42)

Lighthouse | COG-UK ID | Expected go live
-- | -- | -- | --
Brants Bridge | BRBR | Urgent |
Leamington Spa | LSPA | 24th June earliest |
Newcastle | xxxx| 24th June but uncertainty |
