### ISSUE TITLE
GPL-801	As a Sanger scientist at a LH Lab I want to scan a LH plate and know if it contains a sample from Business or holiday traveller returning to UK (Importation)

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#103]
**Description**
GPL-801	As a Sanger scientist at a LH Lab I want to scan a LH plate and know if it contains a sample from Business or holiday traveler returning to UK (Importation)

**Who the primary contacts are for this work**
John S (PAM)
Callum S (PAM)
Rich L
James McC (CIO)

Design Rubber ducked with Philip, Eduard and Harriet

**High level process flow: Flagging plates with 'Samples of importance'**

Draft Architecture (Boxes and arrows): https://lucid.app/lucidchart/invitations/accept/c0366b32-d59b-4861-91f6-bda92277c7cd (view only)

1. PAM updates Core LIMS: GPL-842 New integration point for lighthouse service, samples of importance
2. Core LIMS updates operations: GPL-843 Flag 'Must sequence' and 'preferentially sequence' samples in box buster
3. Core LIMS broad cas to MWLH: GPL-844 MLWH Lighthouse sample table 'must be sequenced' & 'sequenced preferentially'
4. Core LIMS removes redundant service from Summer 2019: GPL-845 Undo PAM end point ‘Value in Sequencing' (GPL-473)

**Agreements**

From discussion on 22nd January (James McC, John S, Callum S, Rich L, Tanya B)

We don't store why it was of importance in MLWH e.g. Importation or unrepresented Postcode. Why? This avoids the boundary of more secure systems interfacing with NHS digital into the LIMS. 

We don't send ‘sample of importance’ information to the DART database. In DART/Beckman service there is one value on well state ‘Pickable’ – we want to keep this simplicity

**Prototype option available today**

This idea is very similar to the ‘Value for sequencing true/false’ API end point we built for PAM in May: (GPL-473) https://github.com/sanger/lighthouse/issues/35
This was built UAT’ed by Christophe P but never used. In production. Is still available.
 
**Additional context or information**
This requirement was first identified in mid December. In the initial design teh service would run at the lighthouse. 

Rich L wrote (Wednesday, 16 December 2020 at 16:58)

From Johns discussion just now checking…he needs a service that
 
REQUEST with RNA plate barcode and
RESPONSE –
yes or no has a Importation sample on that plate
Or
Error: Not know RNA plate barcode
 
Assuming
 
Technician at LH scans a barcode plate (Q> Sanger or LH staff?)
Get response has Importation sample on plate
Yes – Technician packs in box
No – Technician maybe does not pack on box (still want to sequence other samples)
New field to parse and persist in Lighthouse and crawler systems ‘Imported’ (eg Business or holiday traveler returning to UK)
Q. Request/ response traveling over public network / or Sanger laptop/tablet on VPN?

We have retreaded from this position to a position to preferentially select these boxes with samples of interest to put onto the Beckman robots.  

NB Draft as is how you cut the calfs from the cows

**Comment by rl15** [comment]
[Box Buster (NHS digital).pdf](https://github.com/sanger/General-Backlog-Items/files/5872221/Box.Buster.NHS.digital.pdf)

**Comment by rl15** [comment]
Expect to have four backlog items from this epic, delivered in this order (API first to give us testible contract)

1. New API end point for lighthouse service + persist data on Mongodb inc new feilds (NB Do we want a new collection just for plates?)
2. GUI enhancement (see mock up)
3. Broadcast to MLWH + new column
4. Remove redundant feature (technical liability) requested May: (GPL-473) https://github.com/sanger/lighthouse/issues/35

**Comment by rl15** [comment]
Planned go live date (in prod) is February 25th.

**Comment by rl15** [comment]
Ryes wrote Friday, (29 January 2021 at 11:08)

3. Is there any reason I can't upsert directly from NiFi instead of via the described POST?

**Comment by rl15** [comment]
Rich L responded

- Its an unusual architecture for us.
- If you update the data store directly we won’t have any logging of messages. This make may troubleshooting more of a chore.
- I not sure what the implications are for updating the Warehouse – will ask team

Q> What do you gain over the API end point?
Q> Do you have concerns on performance?
Q> Do you think you will update a samples flagged for importance once set?

**Comment by rl15** [comment]
Rich L wrote (Monday, 1 February 2021 at 13:01)

Context
 
Two use cases
 
Flag to staff Lighthouse plate contains sample(s) of note
Flag to staff Operations need to place plate on robot as contains sample(s) of note
 
We are focused on getting use case 2 into production by 25th Feb
 
Agreed
 
Mongodb will be the integration point – require new collection
Not to use synchronous API call
 
For each sample PAM are aware of add to new collection
Root_sample_id
Flag must sequence (Sequence regardless – bypasses existing business rules)
Flag of Importance (Sequence if passes existing rules)
 
Next steps
 
Agree mongoDB schema.
We will update Backlog items to reflect changes agreed today (I will do this before cop today)
 
Q>
 
Can Core LIMS get any logging from Mongodb insert?

**Comment by KatyTaylor** [comment]
I haven't been at the meetings so might be misunderstanding, but from reading the stories it looks like we will need the following:

- To get the sample into DART as 'pickable' (regardless of whether they pass result / CT business rules), we either need to modify the code that chooses which samples to insert to DART, or modify the code that chooses whether to set 'filtered_positive' to true (probably the first option?)

Is this captured in a story anywhere?

**Comment by andrewsparkes** [comment]
Also Root sample id on it's own is not unique enough for that new collection key, it's the four fields of Root sample id, RNA ID, Result and Lab ID.

**Comment by rl15** [comment]
From meeting on 4th Feb General approach of 'must be sequenced' & 'sequenced preferentially' has been discussed between Callum S & Sonia G and confirmed as good strategy.
