### ISSUE TITLE
GPL-802 Cardinal

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#104]
**Description**
Token for a conversation to have

**Who the primary contacts are for this work**
Stefanie L (R&D)

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Mail between Stefanie L

Thursday, 7 January 2021 at 11:28 - Subject: Cardinal Cell counter export - Possibly Quanthub

**Comment by stevieing** [comment]
I am sure that this has come up before and we tested it. It should just work with a new quant type as long as you can get the machine to export a csv or text file.
