### ISSUE TITLE
GPL-807	Epic: Process improvement for Lighthouse box manifests

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#106]
**Description**
Token for a conversation to have: Process improvement for Lighthouse box manifests

**Who the primary contacts are for this work**
Rich C
Alan K (PAM)
Cristina A (PAM)
Siobhan AG (SSR)
Andrew

**Knowledge or Stake holders**
James M
Rich C

**Additional context or information**
High level understanding of current process: https://lucid.app/lucidchart/invitations/accept/3ea5d6ad-644f-4a7f-b589-20c08223b64d

**Comment by andrewsparkes** [comment]
Updated lucid diagram (link in panel above) to latest understanding.
