### ISSUE TITLE
GPL-863 change the sample metadata without going through third parties 

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#115]
**User story**
GPL-863 As representative for Faculty (Martin P) I would like faculty to be able to change the sample metadata without going through third parties which introduces delay

**Who are the primary contacts for this story**
Martin P 
Rich L

**Acceptance criteria**
To be considered successful the solution must allow:
TBD

**Additional context**
Raised in questions from presentation Livett, R. (2021) ICT town hall: Laboratory Information Management Systems (LIMS), 9th February 2021 + follow up email sent on 12th

**Comment by rl15** [comment]
Rich L wrote ()

Questions

•	Is the metadata missing or incorrect?
•	What is root cause of missing or incorrect?
•	How would you like to update this via GUI or API?

Assumptions 

•	Metadata is the 45 fields that are persisted on sample?

**Comment by rl15** [comment]
Martin P wrote(Monday, 15 February 2021 at 12:34)

Is the metadata missing or incorrect?
The metadata is usually both missing and/or incorrect. This may be because it was completed in the wrong metadata field or it has been omitted altogether.

What is the root cause if missing or incorrect?
Typically this is caused by two processes:
- projects where samples are supplied by external collaborators 
- projects where samples leave pipelines and pass through a faculty lab for processing and returns to pipelines with new sanger id for sequencing.

The external collaborators and lab staff currently complete the sample manifest form for the plates they supply. This then populates the data in sequencescape. As this is often done many months before an informatician is brought to a project and the project nomenclature established, this often results in metadata fields being inconsistent. One plate might end up with Country of origin set to 'south sudan', whereas the other might end up with the same information put into Geographical region or Ethnicity. As some of these metadata fields are then propagated to IRODS and are the basis for the publicly facing ENA/EGA metadata, it is important that Sequencescape as the "source of truth" is correct. Hopefully this will reduce the number of faculty excel spreadsheets.

How would you like to update this via GUI or API?
Ideally some kind of GUI which can function across multiple studies rather than at plate level. It might be easier if we did this on one field at a time and allowed the flood filling of groups of samples.

Metadata is the 45 fields that are persisted on sample (list below signature for clarity)?
Correct.

Updates would be 1 or many samples identified by Supplier Sample Name
1 or many is correct. However, they could additionally (and more likely) be identified by Sanger Sample Name. This depends how the project is being run

**Comment by rl15** [comment]
Backlog refinement conversation

Whats the impact from species changes?

**Comment by KatyTaylor** [comment]
Removing from project as seems outdated.
