### ISSUE TITLE
GPL-864 Housekeeping - Add operation eagle to cohort as required from RT tickets in Neils absence

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#116]
**Describe the Housekeeping**
Add operation eagle to cohort as required from RT tickets in Neils absence

**Additional context**
how to articles https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Heron%3A+Add+cohort+name

**Comment by rl15** [comment]
Katy
Harriet

**Comment by rl15** [comment]
712447 | add Eagle to cohort for AP plates

**Comment by KatyTaylor** [comment]
Done for RT #712447
Updated this page with more detail - https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Heron%3A+Add+cohort+name
