### ISSUE TITLE
GPL-866	Client side to use left hook - https://github.com/Arkweid/lefthook with git leaks - https://github.com/zricethezav/gitleaks (PSDTHV)

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#117]
**Description**
GPL-866	Client side to use left hook - https://github.com/Arkweid/lefthook with git leaks - https://github.com/zricethezav/gitleaks (PSDTHV)

**Who the primary contacts are for this work**
All 

- [x] Investigate how to use left hook globally
- [x] Investigate how to use git leaks or equivalent to check credentials before commit
- [ ] ~In git hub Sanger repo update read me template https://github.com/sanger/.github/blob/master/README_template.md~
- [x] Or add to (standards) appropriate document: https://github.com/sanger/.github/blob/master/standards.md
- [ ] Add to the new starters guide - https://docs.google.com/document/d/1hdXRsBYRnnG4nZRRqSnrc9pCq5engI2DC98roRoFl8Q/edit

**Plan to be managed on internal confluence**
https://ssg-confluence.internal.sanger.ac.uk/x/Hq2eBg

**Comment by KatyTaylor** [comment]
Team: to set up, go to https://github.com/sanger/global-git-hooks and follow instructions in Readme
