### ISSUE TITLE
GPL-894 Investigation work 

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#120]
**Describe the Housekeeping**
See RTS for detail;

- [x] #712200
- [x] #683460
- [x] #712164

**Comment by KatyTaylor** [comment]
https://github.com/sanger/sequencescape/issues/3074 - offshoot from #683460

**Comment by KatyTaylor** [comment]
Still to do on first ticket (#683460):
1. Update Well Links for transfers into cherrypick plates
2. Update the Cherrypick Requests - leave a comment, link to the RT
3. Look into how to correct event data (48-62 for each sample)

**Comment by KatyTaylor** [comment]
Tickets #683460 and #712200 are both done in prod now, with the exception of fixing the Event data.

**Comment by KatyTaylor** [comment]
Status update:
- #683460 - fixed in prod (NPG checked and signed off) apart from Events data
- #712200 - fixed in prod (NPG checked and signed off) apart from Events data
- #712164 - not yet done, waiting for information on where in the process the plate rotation happened

**Comment by KatyTaylor** [comment]
Update:
All three tickets are fixed in prod, except for the Events data, which is still being worked on / tested.

**Comment by KatyTaylor** [comment]
Events data fix is now in prod as well, for all three tickets.
