### ISSUE TITLE
GPL-nnn As a developer I would like to talk to Tree of Life to discuss reporting

### ISSUE THREAD

**Issue by BenTopping** [sanger/General-Backlog-Items#121]
**Description**
I would like to know the reporting requirements for the development of long read LIMS for Pacbio IsoSeq. In order to do determine the requirements we need a meeting with Ken Haug (Tree of Life)

**Who the primary contacts are for this work**
Steve

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by stevieing** [comment]
Superceded
