### ISSUE TITLE
GPL-nnn - As developers we need to find out how long read users get information from the different types of QC

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#122]
**User story**
As developers we need to find out how long read users get information from the different types of QC. 

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] A list of all of the different types of QC with how the information is recorded
- [ ] If the machine produces a spreadsheet an example of the structure

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
QC machines:

- [ ] Qubit
- [ ] Tapestation
- [ ] Nanodrop
- [ ] FEMTO pulse

**Comment by TWJW-SANGER** [comment]
Sounds sensible - but given this is about  a year and a half old I'm marking as a candidate for deprecation.
