### ISSUE TITLE
GPL-906 - Create working document for plan to move to Squix printers (C: L, V: 4)

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#124]
**Description**
This document will contain:
- diagram showing the current situation
- steps to create squix templates from current print my barcode label templates
- steps for provisioning new Squix printers
- steps for converting from print my barcode v1 to v2 api
- application priority list

**Who the primary contacts are for this work**
Steve

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by KatyTaylor** [comment]
See page https://ssg-confluence.internal.sanger.ac.uk/display/PSD/Sequencescape+printing+rationalisation

**Comment by KatyTaylor** [comment]
Includes https://github.com/sanger/print_my_barcode/issues/70

**Comment by stevieing** [comment]
Done for Sequencescape.
