### ISSUE TITLE
GPL-923 Set up UAT Simulation Testing for Beckman Method Code Changes (stalled with capacity in R&D, still of value though)

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#126]
**User story**
As developers and R&D we would like the ability to test Beckman code changes to their cherrypicking methods in a UAT environment before they get deployed to production. Beckman have supplied a simulation copy of their software, so in theory this can be loaded up with a version of the methods and tested pointing at a UAT environment. We would need to set up data in UAT DART to allow testing of the various scenarios.

**Who are the primary contacts for this story**
Iraad
Scott

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Running Beckman methods in simulation in the UAT environment with a given inventory file
- [ ] Agreement on a set of scenarios that will be tested
- [ ] Repeatable creation of suitable DART plate data via crawler file
- [ ] Repeatable complimentary setup of a Beckman inventory file to mock loading of the input stacks
- [ ] A written set of compliance data checks to make sure all LIMS events are created as expected
- [ ] A written set of compliance checks to make sure all 'plates' end up in the expected simulated plate stacks

**Dependencies**
This story is blocked by the following dependencies:
- [ ] Beckmans simulation PC must be accessible (physically in office at Sanger)
- [ ] Must have R&D time to set up and run the simulations

**Additional context**
Recent production issue with versions 22 (CP1) and 16 (others): Source plates not having state set to 'started', causes problems with partial sources, being sent straight to output.

**Comment by KatyTaylor** [comment]
In progress because R&D are working on this with Mike

**Comment by rl15** [comment]
Discussed in retrospective held on 27th May. Team still wants to complete this see Rich L (Thursday, 27 May 2021 at 15:20) _Subject: ACTION: Retrospective: Stop Start and spice up 27th May_, email to team

**Comment by TWJW-SANGER** [comment]
@andrewsparkes 
Discussed with Lesley & Scott at standup today.

The story is blocked by difficulties setting up the PC with the Beckman software on it for UAT, it seems:

- The number of dependencies around Beckman simulation processes make this very difficult 
- The PC itself doesn't have a physical location where it can be installed at the moment

These issues themselves are unlikely to be resolved this side of Christmas.


Clearly we do not want to run new Beckman codes without testing it. 
This is currently being solved in R&D by a process of swapping out production Beckman systems and placing them into UAT to test the changes with Beckman.

We propose this story is deprecated from our board and becomes an item on the R&D board to resolve the hardware setup.

Thoughts?

**Comment by TWJW-SANGER** [comment]
Closing this issue on our board as we cannot progress.
The Beckman software is not capable of simulating the third party instruments (cytomats etc), which makes the approach in this story unworkable.
R&D will add this issue to their board to consider what other options there are to test Beckman code changes before they hit production. (The current approach takes one Beckman system out of production)
