### ISSUE TITLE
GPL-940 Box manifests - Story 1 - Phase 1 - Creation of SFTP site for box manifest uploads [Heron]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#128]
**User story**
As PSD we would like to have an SFTP site created that box manifests can be uploaded into for the various Lighthouses. Similar to what we have for plate maps.
We can then extract box manifests from emails, cloud drives or have Lighthouses upload them there directly, and process the files into LabWhere from that one location.

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] A new SFTP upload site is created (or existing one made dual-purpose)
- [ ] Site is user access controlled (similar to existing plate map SFTP site)
- [ ] Directories exist for each Lighthouse

**Who are the primary contacts for this story**
TBD - who maintains existing SFTP

**Dependencies**
None

**Additional context**
Steps:
- Find out who was responsible for the existing plate map SFTP site and request a new one
- Have an account set up for PSD to read from and write to it
- Have a mechanism for Lighthouses to request access

**Comment by TWJW-SANGER** [comment]
Callum's team are working on automating the box manifest ingestion and feeding that to our labwhere API.
