### ISSUE TITLE
GPL-941 Box manifests - Story 2 - Phase 1 - Create Standards Document for Box Manifests [Heron]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#129]
**User story**
As PAM we would like a document we can send to Lighthouses to define how they should format their box manifests and what options they have for sending them to Sanger. Similar to the plate map standards document already created.

**Who are the primary contacts for this story**
Siobhan AG
Alan K

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] A standards document for the creation and sending of box manifests to Sanger is created

**Dependencies**
None

**Additional context**
Steps:
- Create Document for Box Manifest standards
- Maintain and handover new versions to PAM (Alan K) for distribution to Lighthouses as needed
- Document should encourage Lighthouses to upload files directly to SFTP but not prevent other methods

**Comment by TWJW-SANGER** [comment]
Callum's team are working on automating the box manifest ingestion and feeding that to our labwhere API.
Ultimately the plan is to move the Lighthouse's to using SFTP to transfer the box manifests as per the plate maps, however they may need an intermediate solution
As far as PSD goes though, I believe we can close this issue.
