### ISSUE TITLE
GPL-942 Box manifests - Story 3 - Phase 1 - Allow Lighthouses to directly drop box manifests directly into SFTP directory [Heron]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#130]
**User story**
As PSD we would like it to be possible for Lighthouse to directly drop box manifest files into the relevant SFTP directory (similar to plate maps)

**Who are the primary contacts for this story**
TDB - who manages the SFTP site?
Siobhan AG
Alan K

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] New Lighthouses can request an account to access the box manifest SFTP site

**Dependencies**
This story is blocked by the following dependencies:
Box manifest story 1

**Additional context**
Steps:
- Set up directory for Lighthouse of SFTP
- Set up account access for Lighthouse via whoever manages the SFTP sites

**Comment by TWJW-SANGER** [comment]
Callum's team are working on automating the box manifest ingestion and feeding that to our labwhere API.
Ultimately the plan is to move the Lighthouse's to using SFTP to transfer the box manifests as per the plate maps, however they may need an intermediate solution
As far as PSD goes though, I believe we can close this issue.
