### ISSUE TITLE
GPL-943 Box manifests - Story 4 - Phase 1 - Creation of a box manifest file handling application (Boxer?) [Heron]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#131]
**User story**
As PSD we would like the box manifest data to be automatically processed into LabWhere at regular intervals throughout the day from the SFTP site.

**Who are the primary contacts for this story**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Box manifest crawler reads from SFTP site by Lighthouse
- [ ] Box manifests are validated and corrected if necessary (by Lighthouse)
- [ ] Corrected manifest files are:
- [ ] uploaded to LabWhere
- [ ] copied to an email address
- [ ] copied to a network location
- [ ] Records are written to a database to record the box and it’s plates
- [ ] Errors are visible to SSRs via display (see story 7) along with reference to original email or file uploaded from, as relevant

**Dependencies**
None

**Additional context**
Steps:
- Think of a suitable name for the application
- Validations and corrections to file in config by Lighthouse centre
- Upload file to LabWhere [Q. API required or already exists?]
- Write database records for successfully imported file information (box and plate barcodes, plus metadata if email or cloud route)
- Write import log for imported file, including if there are errors (like Crawler)
- Copy of completed box manifest file to network location for SSRs backup
- Copy of completed box manifest file to email address for SSRs

Draft data structure diagram:
https://lucid.app/lucidchart/invitations/accept/c2e0efc0-b5fa-4316-91fe-80a14d5ce[…]loc=-140%2C-22.666666666666668%2C2909.3333333333335%2C1464%2C0_0

**Comment by TWJW-SANGER** [comment]
Callum's team are working on automating the box manifest ingestion and feeding that to our labwhere API.
Ultimately the plan is to move the Lighthouse's to using SFTP to transfer the box manifests as per the plate maps, however they may need an intermediate solution
As far as PSD goes though, I believe we can close this issue.
