### ISSUE TITLE
GPL-944 Box manifests - Story 5 - Phase 1 - Summary display for uploaded box manifests [Heron]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#132]
**User story**
As SSRs and PAM we would like to see a visual representation of the boxes and number of plates imported by each Lighthouse for each day of the week. Any validation or other errors with interpretation of manifests should also be clear.

**Who are the primary contacts for this story**
Siobhan AG
Alan K
Rich C
James M

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Visible import log information from the box manifest processing

**Dependencies**
This story is blocked by the following dependencies:

**Additional context**
Steps:
- The box manifest processing application should write import logs of the data it's processed (record original email detail or cloud file and tab that the files were uploaded from).
- Addiitonal, email and cloud file processes should also write imformation in a way that can be pulled into this summary (e.g. email subject, cloud file name etc.)
- Import log information should be displayed on Lighthouse-UI screen

Summary table something like:
Date | Centre | Source type | Box barcode | No. Plates | Approx. Samples | Errors
-- | -- | -- | -- | -- | -- | --
12/03/2021 | MK | Email | lw-uk-biocentre-box-mk-687-17456 | 80 | 7,680 |  
12/03/2021 | AP | OneDrive |   |   |   | Error: File [filename] tab for 12th March 2021 failed to parse
12/03/2021 | CB | SFTP | lw-uk-biocentre-box-mk-687-17456 | 80 | 7,680 | Warning: Manifest rows that contained multiple plate barcodes: 1

**Comment by TWJW-SANGER** [comment]
Callum's team are working on automating the box manifest ingestion and feeding that to our labwhere API.
Ultimately the plan is to move the Lighthouse's to using SFTP to transfer the box manifests as per the plate maps, however they may need an intermediate solution
As far as PSD goes though, I believe we can close this issue.

Have had a conversation with Rhys about compiling list of errors from parsing - he had a several good ideas.
