### ISSUE TITLE
GPL-945 Box manifests - Story 6 - Phase 1 - Screen for SSR to upload box manifests into SFTP site [Heron]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#133]
**User story**
As an SSR I would like a way to upload box manifest files into the SFTP site. I should be able to select the Lighthouse (SFTP directory), upload a file, and have some immediate feedback on whether the file is a valid format or not.

**Who are the primary contacts for this story**
Siobhan AG

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Box manifests can be uploaded via a screen
- [ ] Validation is done to check the file format is as expected

**Dependencies**
This story is blocked by the following dependencies:
Story 1, creation of SFTP site

**Additional context**
Steps:
- Selection of Lighthouse
- Upload of file
- Validation if file format is correct for the Lighthouse [share validation code with Boxer application]
- If valid, file is deposited in SFTP directory using an all-Lighthouses access account, for Boxer app to process later
- Visual feedback to SSR of success or failure (validation or upload exception)

Screen should be in Lighthouse-UI.
If the file already exists we want to allow a new version to be uploaded. The Boxer app can use checksums to compare files and update if different.

**Comment by TWJW-SANGER** [comment]
Callum's team are working on automating the box manifest ingestion and feeding that to our labwhere API.
Ultimately the plan is to move the Lighthouse's to using SFTP to transfer the box manifests as per the plate maps, however they may need an intermediate solution
As far as PSD goes though, I believe we can close this issue.
