### ISSUE TITLE
GPL-946 Box manifests - Story 7 - Phase 2 - Automated extraction of box manifest files from email into the SFTP site [Heron]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#134]
**User story**
As SSRs we would like box manifest files to be automatically extracted from emails sent to Sanger and dropped into the relevant directory in an SFTP site. Initially this includes box manifest emails from Cambridge, Glasgow, Milton Keynes and Randox Lighthouses.

**Who are the primary contacts for this story**
Siobhan AG
Rich C
James M

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Box manifests should be automatically extracted from emails
- [ ] The box manifest files are written to the SFTP site
- [ ] A log is written in a database to record which emails have been processed for reporting purposes (including any errors)

**Dependencies**
This story is blocked by the following dependencies:
Phase 1 stories

**Additional context**
Steps:
- Creation of a mongodb collection to store processed email logs
- With columns something like box_barcode (key), email_timestamp, email_subject, sftp_upload_success (boolean), uploaded_to_sftp_timestamp
- Identification of relevant new emails since previous run using database logs
- Identification of lighthouse centre from email source and/or subject
- Extraction of box manifest file attachment(s) from email
- Write box manifest files into SFTP
- Write log of processed emails and whether errors encountered to database

**Comment by TWJW-SANGER** [comment]
Callum's team are working on automating the box manifest ingestion and feeding that to our labwhere API.
Ultimately the plan is to move the Lighthouse's to using SFTP to transfer the box manifests as per the plate maps, however they may need an intermediate solution
As far as PSD goes though, I believe we can close this issue.
