### ISSUE TITLE
GPL-947 Box manifests - Story 8 - Phase 3 - Automated extraction of box manifest information from cloud drive [Heron]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#135]
**User story**
As SSRs we would like box manifest data to be automatically extracted from Excel spreadsheet tabs stored in the cloud, then box manifest files created and uploaded into the SFTP site. Initially this involves processing box manifest spreadsheets from Alderley Park Lighthouse.

**Who are the primary contacts for this story**
Siobhan AG
Rich C
James M

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Creation of a mongodb collection to store processed OneDrive logs. With columns something like box_barcode (key), filename, file_tab
- [ ] Box manifest data are automatically extracted from the spreadsheet tabs into new box manifest files
- [ ] The box manifest files are written to the SFTP site
- [ ] A log is written in a database to record which spreadsheets and tabs have been processed for reporting purposes (including any errors)

**Dependencies**
This story is blocked by the following dependencies:
Stories from phase 1

**Additional context**
Steps:
- Identification of latest spreadsheet and tab processed from previous record in database
- Extraction of information from each new spreadsheet tab into new box manifest files
- Write box manifest files into SFTP
- Write log of each spreadsheet and tab processed and if any errors to database

**Comment by TWJW-SANGER** [comment]
Callum's team are working on automating the box manifest ingestion and feeding that to our labwhere API.
Ultimately the plan is to move the Lighthouse's to using SFTP to transfer the box manifests as per the plate maps, however they may need an intermediate solution
As far as PSD goes though, I believe we can close this issue.
