### ISSUE TITLE
Housekeeping - research how to move Warehouse Two [C=L, V=5*]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/General-Backlog-Items#137]
**Describe the Housekeeping**
Spun out of https://github.com/sanger/General-Backlog-Items/issues/97 

Migrate Warehouse Two to FCE

**Comment by KatyTaylor** [comment]
Large due to uncertainty due to ancient Ruby and Rails versions

**Comment by stevieing** [comment]
closed in favour of sanger/deployment/#127
