### ISSUE TITLE
GPL-955 [EPIC] visualise the inventory of plates from end to end for everybody

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#141]
**Description**
GPL-955 As a process improvement specialist (Lee W) I would like to visualise the inventory of plates from end to end (core LIMS & NPG) for other sequencing products to show state of operations for everybody!

**Who the primary contacts are for this work**
Sara S (Product lead ops)
Rich C
James M
Lee W (PAM)
James G (Prototype this idea previously)
Tom W (Prototype approach for UKB)

**Suggestion**
Work down the list of pipelines by volumes per year? 

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
See GPL-953 & GPL-954

**Comment by Skrich1999** [comment]
Email from Rich Rance "My understanding is that that this has been superseded by DPL 323. This piece of work is active and looks to introduce a Kanban system across all pipelines (not just Heron)"
