### ISSUE TITLE
GPL-986 As an SSR (Rich C) I would like to be able to record that one or more samples is a "Terminal Failure" in a given failure category and with a free text note on a page in SequenceScape.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#143]
**User story**
As an SSR (Rich C) I would like to be able to record that one or more samples is a "Terminal Failure" in a given failure category and with a free text note on a page in SequenceScape.

We define a "Terminal Failure" as the point in the process where no further work will be done on that sample. We may ask suppliers for resupply after this, but fresh supplies of samples will be allocated new Sanger IDs.
"Terminal Fails" is a final exit point in the whole process from sample reception -> DNAP -> NPG  → to confirmed data upload at EBI. So it is something that is a manual decision taken by SSR's looking at the sample history as a whole.

There are other "failures" recorded in SequenceScape (e.g. Library prep failures), however in general these do no automatically prevent further work being done on the sample. 

We need to know when a sample has reached a "Terminal Failure" state in order to prevent samples sitting in the last swim lane reached in the process forever & also to order resupplies.

There is a contractural requirement to report these to UKB. Currently "Terminal Fails" are being reported manually by the SSR's for UKB and are then fed into the UKB QC report and have been monthly since late 2019. See [UKB Failed Samples](https://ssg-confluence.internal.sanger.ac.uk/display/PSD/UKB+Failed+Samples)

**Who are the primary contacts for this story**
Rich C.
Tom W

**Acceptance criteria**
To be considered successful the solution must allow:

- [ ] The user can enter one or a list of Sanger IDs into the page
- [ ] The user can select one failure category to apply to all samples in the list.  UKB failure categories can be used as basis for MVP - found [here](https://ssg-confluence.internal.sanger.ac.uk/display/PSD/Sample+Failure+Categories)
- [ ] The user can enter a free form text note to apply to all samples in the list.
- [ ] The terminal failures are exported to a table / tables in the MLWH so they can be used in reports
- [ ] We define & communicate a process where samples can be removed from Terminal Failure state
- [ ] Backload Rich C.'s existing spreadsheet of UKB failure samples into the system
- [ ] SSR's can view failed list of samples - this might be provided by say an example SQL query to MLWH

**Dependencies**

**Additional context**

**Comment by Skrich1999** [comment]
This was for the UKB project but is no longer needed as UKB is now complete
