### ISSUE TITLE
GPL-996 Bioseros PC, remote acces and database comissioning - dependency with ICT [Heron]

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#148]
**User story**
As the wider Biosero team we need to set up a mirror of the test environment to complete the site acceptance tests

**Who are the primary contacts for this story**
Lesley S (R&D)
Scott T (R&D)
Andrew S
Philip VV
Harry 
Eduardo

**The todo list**
To be considered successful the solution must allow:
- [x] Simulation PC Cherwell incident 294903. (st2) order in UBW as of 27th April. Will go in In D345. Updated 11th May shipping 22nd May, expected 28th May - 
- [x] Request for loan PC in interim commission (done), team viewer (done) GBG installed (update in project meeting on 18th)
- [x] locate and network to local port Simulation PC Cherwell incident 2xxxxx (ls7)
- [x] Network + remote access simulation pc Cherwell incident 297201 (rl15)
- [x] Set up UAT shared Biosero MySQL database Cherwell incident 297808 (as28)
- [x] Set up PROD shared Biosero MySQL database Cherwell incident 297808 (as28)

**Additional context**

High level architecture: https://lucid.app/lucidchart/invitations/accept/inv_62430c85-d0ce-449e-befe-806229346ccb 

*1 Tableau reports: 

- https://globalreporting.internal.sanger.ac.uk/#/workbooks/3491/views
- https://globalreporting.internal.sanger.ac.uk/#/views/BeckmanCPrunstatus/BeckmanCherrypickingRunStatus?:iid=3 

This project is managed under project 775 in ICT

**Comment by andrewsparkes** [comment]
UAT database creation in progress, Simon E progressing.

**Comment by andrewsparkes** [comment]
UAT database server creation complete, PROD to wait until after hardware upgrades to DB infrastructure in 2 weeks. Not needed till physical Biosero hardware arrives onsite (June?)
