### ISSUE TITLE
DPL-020	Blue light: R&D work 3 plates from MK that are duplicates samples have been eluted 

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#153]
**Description**
DPL-020 | Blue light: 3 plates from MK that are duplicates samples have been eluted (extra buffer added) to test if this solves the issues we have seen with low sample volumes

**Who the primary contacts are for this work**
Cristina A (PAM)
Sonia )PAM)
Naomi P (R&D)
Lesley S (R&D)
Tom W
Katy T

**Assumptions**

Plates are on site today

**Plan**
These must be processed on Beckmans 
Duplicates need to be given same COG-UK id 
Patch samples into R&D study 6198 (NPG will upload to R&D space on CLIMB)

**Additional context or information**
See Slack herron-ss 21st May

**Comment by TWJW-SANGER** [comment]
[Adding link to confluence page with more details and plans]
(https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=122292157)
