### ISSUE TITLE
DPL-021 Bug - update date tested field

### ISSUE THREAD

**Issue by pjvv** [sanger/General-Backlog-Items#154]
**Describe the bug**
Lighthouse lab uploaded plate map data with the incorrect `Date Tested` field.

**RT Ticket Number**
719720

**To do:**
- [x] write SQL query to update `lighthouse_sample` table @neilsycamore 
- [x] write mongo query to update `sample` collection @pjvv 
- [x] send email to notify about changes to be made @neilsycamore 
- [x] run on UAT and production MLWH @neilsycamore 
- [x] run on UAT and production mongo @pjvv

**Comment by neilsycamore** [comment]
update lighthouse_sample
set date_tested = '2021-05-06 00:00:00'
where plate_barcode = 'RDX-J1-032213';

**Comment by pjvv** [comment]
For the mongo update:
```javascript
db.samples.updateMany({plate_barcode:'RDX-J1-032213'},{$set:{'Date Tested':new Date("2021-05-06")}})
```

**Comment by neilsycamore** [comment]
included updated_at
UPDATE lighthouse_sample
SET date_tested = '2021-05-06 00:00:00', updated_at = NOW()
WHERE plate_barcode = 'RDX-J1-032213';
