### ISSUE TITLE
GPL-356	As Development team (LIMS) we want to automatically create samples and their metadata in Sequencescape for heron samples to automate this high throughput process

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#16]

**Comment by stevieing** [comment]
**User story**
As a development team when we receive a request from the csv parser to create a tube rack we want to create a tube rack, with the specified number of sample tubes and samples

**Who the primary contacts are for this story**
e.g. Eduardo

**Acceptance criteria**
To be considered successful the solution must allow:
1 - A tube rack will be created with the specified tube rack barcode that is sent in the request from csv parser
2 - The correct number of tubes will be created which will each have a sample, tube barcode and a position (rack location)
3 - Each sample created will have sample name, supplier sample name and the sample public name in sample metadata populated from the original tube barcode from the MLWH e.g. PHEC-nnnnnnnnnnnnn
4. - All of required sample metadata will be populated with default data as it is not available.
