### ISSUE TITLE
DPL-117 prevent samples being picked into fixed locations on Beckman (& Biosero) robotics 

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#163]
**User story**
DPL-117 | As lead for Genomic Surveillance Unit (GSU) (Cristina A) I may like to prevent samples being picked into fixed locations on Beckman (& Biosero) robotics to ameliorate a production issue raised on 13th Aug

**Who are the primary contacts for this story**
Cristina A (GSU)
Andrew S

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Prevent samples being picked into 1 or more fixed locations of CP destination plate for
- [ ] Beckman (4 instruments) 
- [ ] Biosero (2 Hamiltons)
- [ ] Todays test case is prevent picking into wells A3, B3, B7, B10, C7, D3, E11, G7, H3, H10
- [ ] Keep one random control per plate so plate would have 85 samples. (88.75% capacity)

**Additional context**
Request raised in 10am Heron meeting on 16th 
More than 1 tag in wells

D14 – 10915 filtered reads
D19 – 1350
N13 – 1075
E14 – 950

Options

- Configure each robotics platform to to pick into destination plate as wells x, y, & z
- Seed the destination that wells already picked into at start of run (triggered stored procedure as temp fix)
- Not software change add inhibitor to destination plate in known wells (+ dont add controls to these wells) + train operations
- NPG mark them as fails
- Do nothing

**Comment by rl15** [comment]
Andrew wrote;


For Biosero we currently have the ability to prevent (exclude) specific destination wells from containing controls (this is currently excluding wells A3, B3, D3, E11, H3, and H10 because of tag issues). 
These wells can still contain samples. 
This is a database configuration and can be changed by Sanger at short notice.

For Beckman I believe it is hardcoded into the method to avoid certain wells or columns. Not so easy to change and we don't have a working simulation to test in.
Both configurations have a single control source well to pick the negative control from (i.e. not a list of 'n' wells).
Both expect to place a single negative control into the destination plate, neither method has any functionality to dispense additional negative controls or to specify where they go on the destinations, the requirement was to have one positive and one negative and randomise the destination plate well locations to avoid plate swaps.

So that's significant changes to the methods of Beckman and Biosero if you want to do that.
We'd have to test if multiple negative controls breaks the LIMS plate creation and Limber plate views as well.

**Comment by andrewsparkes** [comment]
Update:
For Beckman it is in fact relatively easy to change the exclusion list for Beckman. It is in a single configuration file and R&D know how to change it. The wells excluded (from being controls) list was expanded Mon 16th Aug for both Biosero and Beckman to: A3, B3, B7, B10, C7, D3, E11, G7, H3, H10.
