### ISSUE TITLE
DPL-193 Scoping for Open Sourcing PSD applications

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#168]
**Description**
Scoping for Open Sourcing PSD applications:
- [x] Process diagram for current Genomics England process - https://lucid.app/lucidchart/41a33f13-e07a-44db-ac2d-e92ac528840f/edit?invitationId=inv_386ff994-6507-41ce-bc88-e8d50a7c566d
- [x] Process diagram for Genomics England ONT pipeline - https://lucid.app/lucidchart/41a33f13-e07a-44db-ac2d-e92ac528840f/edit?invitationId=inv_386ff994-6507-41ce-bc88-e8d50a7c566d
- [x] Process diagram for Scientific Operations Long Read ONT pipeline https://lucid.app/lucidchart/448a9a9b-00b1-496a-9a9b-0a93ab5fb0d7/edit?page=0_0&invitationId=inv_a0251db5-18dd-4761-8cf3-0530dddd87e6#
- [x] Report for Genomics England on areas for collaboration
- [x] Identify PSD applications that would be ideal for Open Sourcing
- [x] rename existing traction to traction-legacy
- [ ] create traction monorepo
- [x] add tasks from meeting as stories

**Who the primary contacts are for this work**
Steve

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by stevieing** [comment]
Notes from Genomics England meeting:

Receive samples fluidx
Scan rack
DNA only all fridge based
Manifest manual check
IDs already in gel database with metadata
Rename tubes 10 digits
Manually creating codes
Internal sample Id

Generating barcodes and writing them on

Row for each sample and adding metadata

Qc output manually entered.

Now Receive random tube that is not trackable.

Needs to be reracked.

Sequencing
Promethion
Experiment name id
Position Id
Flow cell id
Sample id

Shearing
Sre
Beads
Library prep
Femto

Femto output
Manual calculations

**Comment by stevieing** [comment]
Notes from Genomics England informatics meeting:

When a sample comes into the lab scan barcode and find out whether it already exists.

Identifiers to pull out of clinical system to use in the LIMS.

How to process the sample.

qc outputs.
femto pulse
??

produce sample sheets.

Qc output from pipelines into LIMS.

Original sample manifest. Hopefully as standard that sample will be registered in the Genomics England clinical database.
Assign a barcode to each sample in a tube.
Lab person would scan the barcode into LIMS and LIMS would make a call to GE database which would retrieve any information that they need.
qc done on original sample which would determine what they do next e.g may need to shear it.
Create libraries and go into a new tube with a new barcode.
Make a decision on which libraries go on which flowcells ( 2 flowcells for cancer samples and 1 for normal samples ).
Generate a sample sheet which you would upload to the Promethion. Generate run names and ids - lab sample id. Related to filenames.

Advanced:
uploading qc data
using the ONT API.

**Comment by stevieing** [comment]
What would we need to do to make traction open source ready?

modularising sample imports
create configuration elsewhere - where? service or json
dockerisation
monorepos
more professional styling - remove bootstrap
ability to turn pipelines on and off
configurable library types
configurable services e.g. samples, printing, warehouse, messaging
single reception form
accessibility - screen reader
security - dependency updates
upgrade to Vue3
optional authentication
- logins
- api keys
audit trail / event handling
documentation
 - read me
 - setup
 - troubleshooting
 - developer documentation for ui
 - developer documentation for service
typescript?
Vite
remove yarn
configurable databases?
configurable sample sheets
configuring automation
- pacbio api
- ONT api
proper release strategy - semver
integration suite - cypress and docker
store - vuex or pinia?

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
