### ISSUE TITLE
DPL-nnn Re-enable the removal of the oldest docker package on releasing a new package (C=S, V=4)

### ISSUE THREAD

**Issue by BenTopping** [sanger/General-Backlog-Items#170]
**Describe the Housekeeping**
As a developer I would like github actions to remove the oldest docker package when I release a new package. This is to make sure we stay within our github registry memory limits. 

For this task to be successful there should be a working action in the automated_release github workflow that removes the oldest docker package.
This should be implemented into the follow repos:

- [ ] Cherrytrack
- [ ] Lighthouse
- [ ] Lighthouse-ui
- [ ] Wrangler
- [ ] Crawler
- [ ] Automanual
- [ ] Baracoda
- [ ] Print-my-barcode

**Blocking issues**
No known blocking issues, this was previously disabled due to the action being used not working

**Additional context**
Github added the ability to delete packages from their API. Some useful links may be: 
- https://octokit.github.io/rest.js/v18#packages-delete-package-for-org
- https://docs.github.com/en/rest/reference/packages#delete-a-package-for-an-organization

**Comment by SujitDey2022** [comment]
Hi @BenTopping, wanted to confirm if this story is still relevant, and if yes, please could help understand if this is a Technical Debt or Housekeeping or security-related requirement. Also, if possible could you tag the Size and Value based on the current understanding?
