### ISSUE TITLE
DPL-302 Check if labware should be destroyed

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/General-Backlog-Items#172]
**User story**
As a Heron Lead I would like a tool to help lab staff decide if labware should be destroyed.

**Who are the primary contacts for this story**
Anna G, Katy

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Quick and easy page that allows users to scan a labware barcode, and displays visually whether it should be destroyed or not.
- [ ] Different labware types could have different lifespans - a labware should be destroyed if 'today' is a certain amount of time after the labware was created.
- [ ] The highest priority labware for this are the Lib Pool XP tubes (1 month from creation), and the Norm tubes (1 month from creation). But ideally the feature could be used for all labware types in the pipeline, from the RT-Q plate onwards (there's currently no restriction on how long the initial 96-well plates can be kept).

**Additional context**
The destroying process is OK - this is just an aid to make sure the correct labware are being destroyed, at the right times.

James G has investigated the Asset Audits feature for destroying labware. It:

> 1. Lets you scan in ~(currently up to 15)~ barcodes
> 2. Finds the corresponding labware, but then does some kind of filter/conversion into plates
> 3. Checks that all scanned labware have:
>   - A purpose with the lifespan value set
>   - That the labware is older than that lifespan
>   - All scanned barcodes could be found
> 4. If the above all pass the batch is registered as destroyed, otherwise you see an error letting you know the problem
> 

This seems pretty suitable. At the least we could definitely reuse the 'lifespan' field on Purpose. The above would need to be converted to work with tubes as well as plates. Could consider an integration with LabWhere if that's what Heron use to mark labware as destroyed - however, that would probably be best as another story.

**Comment by TWJW-SANGER** [comment]
For other teams the lifespan of samples would be different (2 years).

**Comment by sdjmchattie** [comment]
Katy and I had a meeting with Anna where we showed the Asset Audits tool and asked that it be tested during this week to see if it already satisfies the requirements of this ticket.  I will catch up with Anna next week to see how things went.

**Comment by sdjmchattie** [comment]
Anna has tested the Asset Audits and found that they satisfy the requirements of this story.  There are some outstanding UX issues that Anna would like to see addressed, but those are handled in the following tickets, so I will close this one:

https://github.com/sanger/asset_audits/issues/365
https://github.com/sanger/asset_audits/issues/339
https://github.com/sanger/asset_audits/issues/340
