### ISSUE TITLE
DPL-313 - Create a process diagram for the architecture for the ToL SciOps data transfer

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#173]
**Description**

- ToL would now like to request work via their ELN and we would like to push this to Traction.
- Currently they are using an interim solution with samples registered via Sequencescape using a sample manifest
- They would like this to be automated
- The suggestion is to use a message queue, similar to the Heron Pickable logic OKR.
- The outcome of this is a process diagram which can be presented to ToL to explain how this would work architecturarly and technically.

**Who the primary contacts are for this work**
Andrew / Eduardo

**Knowledge or Stake holders**
ToL

**Additional Context**
This is in preparation for a meeting on 12/04

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
