### ISSUE TITLE
DPL-335 As a team (PSD) we would like to setup a private repository to store data patch scripts & instructions so that we have one easily discoverable place for this information [C=S, V=4]

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#175]
**User story**
As a team (PSD) we would like to setup a private repository to store data patch scripts & instructions so that we have one easily discoverable place for this information.

**Who are the primary contacts for this story**
PSD team

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] The repo is structured to store scripts for data patches that might run across different databases
- [ ] The repo can store logs / records of data patches that have been applied
- [ ] Move Jonnie's data patch scripts here ?

References
This story is an outcome of a retrospective on the 2022-04-05.

**Additional context**

**Comment by JamesGlover** [comment]
Basic repo setup on internal git-lab

**Comment by JamesGlover** [comment]
https://gitlab.internal.sanger.ac.uk/psd/data-patch-archive

**Comment by stevieing** [comment]
@JamesGlover all seems fine to me. I have added a star to the repo as my approval.

**Comment by andrewsparkes** [comment]
@JamesGlover so plop looks interesting.
Is the idea you create common re-useable bits of code as you make patches? If so should we create a directory structure to encourage this re-use from the start so it doesn't rapidly get in a mess?
And how would database access be handled? especially as there are likely to be multiple databases e.g. for a heron data fix. e.g. deployment app has a vault for credentials, wouldn't want to be duplicating it all

**Comment by KatyTaylor** [comment]
Are you planning to add Jonnie's scripts? (3rd acceptance criteria)

**Comment by emrojo** [comment]
All very good and works very well I think. I would also add an optional docker setup, so we can run also all in a docker container in case we have problems with versions with the local development setup.

**Comment by emrojo** [comment]
I think Jonnie script is this? https://github.com/sanger/lighthouse/pull/528

**Comment by KatyTaylor** [comment]
> I think Jonnie script is this? [sanger/lighthouse#528](https://github.com/sanger/lighthouse/pull/528)

There are also several under this Confluence page - https://ssg-confluence.internal.sanger.ac.uk/display/PSD/Project+Heron+Data+Fixes

Mine, Jonnie's and Stuart's.

**Comment by JamesGlover** [comment]
@emrojo @andrewsparkes  I think running scripts is probably going to end up depending so much on a case by case basis that I didn't think about adding any standard infrastructure for running them... it might be something that evolves over time. Most scripts will probably end up needing to run in the context of their applications for instance, so can't be triggered directly from this repo without considerable work.

@andrewsparkes I did consider a lib director for standard scripts, however I think it's important that we keep a record of scripts as they were run, and shared libraries could complicate this. (As they could be updated) Perhaps we could have a directory, but encourage you to copy the file in to the separate script directory to make use of it?

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
