### ISSUE TITLE
DPL-337-3 - Please can we investigate if there is additional LIMS/tracking support available for HiC submissions, to allow for a single HiC submission up-front from the SSR to reduce errors and save time

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#176]
**Description**
Please can we investigate if there is additional LIMS/tracking support available for HiC tracking and submissions, to allow for a single HiC submission up-front from the SSR.
Current status:
Samples are received in tubes, with manifest uploaded to SS. The tubes (and the HiC protocol required) are listed on a googlesheet for the lab team. The tubes are processed through SE LIMS, which results in a stock plate ID, in SS, which is also filled back into the googlesheet by the lab team. At this point, the SSR selects samples (based on the proportion of sequencing lane required), copies these to a new googlesheet tab for tracking purposes and make the CP and library prep request in SS. We would like to reduce the tracking on googlesheets and the need for the SSR to manually select samples for batching in the middle of the process.
 
Potential new status:
The SSR makes an up-front submission for HiC cross-linking, library prep, pooling and sequencing. The submission would allow the tissue tubes to go through SE LIMs, generate a plate and also include the lib prep and sequencing submission for HiC. This would mean that the SSR does not need to make a submission at the mid-point in the process, and a single “batch” of samples can stay together through the full lab process.
If there are any alternative solutions, we would be happy to explore these.
Please ensure that al13 and ad30 are also consulted on any changes to process/submissions to ensure that this fits with the lab processing.
 
Acceptance criteria:
Not fully yet set, research story to see what is possible.
 
If the above suggestion is taken forward:
-          One upfront submission made by SSR on tubes with tissue samples, which allows HiC cross-linking, generation of DNA in stock plate, and library prep/pooling and sequencing submission in one go.
-          Sample progress trackable in LIMS.

**Who the primary contacts are for this work**
Liz / Emma

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**

- #195

**Comment by andrewsparkes** [comment]
Andrews notes from meeting on 14th:

HiC Meeting Notes - 13th April
**Attending**
Emma Gray, Elizabeth Cook, Alice Linsdell, Stephen Inglis, James Glover and Andrew Sparkes
**Background**
Story DPL-337
https://github.com/sanger/General-Backlog-Items/issues/176
**Notes**
Currently around 70 Tree of Life (ToL) samples per week, numbers increasing and may double if each sample is treated to two processes.
Samples are in Tubes.

Samples are tracked via google sheets.
Tube manifests are sent out to ToL with sample ids and barcodes.

Google sheets track information from ToL.
Information is copied into HiC schedule, another google sheet.

Capacities for both Cross-linking and Library prep (separate processes with separate capacities) are given each week to Alice (via TL in long read)

A batch of Cross-linking happens in the lab, and then the samples get put into Samples Extraction LIMs after work has been completed.
A ‘stock plate’ is created in Samples Extraction LIMs.

Samples are then manually grouped together based on the number or proportion of lanes of sequencing required and genome size (Liz mentioned ranges of genome size).

A ‘fake’ Cherrypick is done as a way of re-organising the samples from the stock plate(s) into the new batch groupings on new plates. i.e. the samples are cross-linked in one grouping then re-organised for library prep and sequencing in another grouping.

A library prep and sequencing submission is created (bulk submission in Sequencescape), with a HiC library type for Novaseek sequencing.

All information is tracked in google sheets. Alice and Liz think this is not sustainable if numbers of samples increase further.

Emma G would like this work to be tracked in Traction, as opposed to Samples Extraction or Limber.

Emma G  mentioned there is currently a lot of difficulty in reporting what has happened.
James G mentioned that Samples Extraction has some reporting functionality that may help.

James G mentioned that it would be possible to defer pooling of samples into a sequencing batch until later in the pipeline, although this has the complication that you have to deal with tag clashes., so it may be impractical.

Emma G pointed out that the manual library prep currently being done for this work is very similar (but not identical) to the high throughput library prep being done routinely in the main labs. Is there a reason not just push the samples through this existing library prep process?
 
Actions:
Create a process diagram about what is currently happening and confirm with all parties that it is correct.

**Comment by stevieing** [comment]
Notes from Emma:

HiC submission
Current process –
Tube manifest (tissue) sent out to ToL, google docs contain multiple google sheets to capture info from ToL
Info copied into HiC schedule, another google sheet
Capacity given to Alice via TL in long read, capacity given for Cross linking and library prep (treated as 2 separate processes with differing capacities)
Cross linking happens in the lab which gets put into extraction LIMs after work has been completed and then is a stock plate created in extraction LIMs
Library submission in Limber with hic lib type, need to look at proportion of lane needed as this differs with genome size
Fake cherry-pick (re-arrayed manually)
Batch in Cross linking is different to library batch
Added to google sheet and lab work is started
Limber bespoke submission

**Comment by stevieing** [comment]
Lucid chart to explain current process https://lucid.app/lucidchart/1d28211e-f43c-4d68-a58c-5d503a09d9ea/edit?invitationId=inv_e93fa4c0-d501-400a-9b25-b2d1ff32a0bb

**Comment by stevieing** [comment]
Notes from meeting with Tracey (10/5):

Go to Limber

Tracey send a worksheet of submission 

pool number
Plate ids

in the hi-c v2 google sheet

illumina library prep tab

select batch number related to paperwork

check batch against the paperwork i.e. plate barcode

manually write well positions against the pooling strategy from submission - manual cherrypick??

put samples into covaris plate and shear them - mark it on the top so don’t put barcode on it as it is used multiple times

spry clean up into semi skirted plate - write dn number on side of plate

transfer into new semi skirted plate once eluted - write dn on the side

biotin encrichment - same plate

qubit quant? They want to drop this

library prep

wash buffer clean up

Elution

transfer into twin tech plates for pcr - write barcode

transfer back into semi skirted plate (same) -write barcode

spry clean up

eluted into final volume into final twin tech plate (put on barcode label from lbb lib pcr xp plate)

Limber

type dn number for submission

check pooling against submission

print cherrypick label(s) - lbb

add an empty lbb ligation plate - manual transfer

print label - put on worksheet

scan lab ligation barcode into limber

add an empty lbb lib pcr xp plate

add tag plate - scan IDT tag plate barcode

select i7 tag 1 group and i5 tag 2 group

create new custom tagged plate

print 2 labels 
1put on worksheet
1 put on twin tech plate 


lbb lib pcr xp plate
run qc on tapestation and dilutions - record Hi-C v2 google sheet - library 5nM dilution calculator
manual pooling - excel spreadsheet (automated byb Ben Far)
pool into a tube which is qced on tapestation - no barcode??
if it is passed then you charge and pass libraries
add an empty lbb lib pool stock tube - print barcode and add that to the pool tube that has been created
Add qc against each pool tube
manual transfer
print label
qc each pool twice on tapestation to get average
dilute pool stock tube to 2.8nm
Back to limber scan each pool
Add lb lib pool norm tube
print barcode
send for sequencing


stock pool to 5nM
take volume to dilute into lb lib pool norm tube - add eb
put final volume into limber. Molarity would be 2.8nM

final manual transfer
