### ISSUE TITLE
DPL-350 [BUG] SMRT link is unavailable in UAT which is preventing PSD from testing sample sheets

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#178]
**Describe the bug**
SMRT link is unavailable in UAT which is preventing PSD from testing sample sheets

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by BenTopping** [comment]
@stevieing confirmed its working now so move to done and close?
