### ISSUE TITLE
DPL-356 - As PSD developers we would like to decide on how best to consume the messages into our Long Read LIMS or Samples Extraction for sample transfer from ToL (S=M)

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#183]
**User story**
As PSD developers we would like to decide on how best to consume the messages into our Long Read LIMS for sample transfer from ToL

**Who are the primary contacts for this story**
Eduardo
Stuart
Andrew

**Acceptance criteria**

To be considered successful the solution must allow:

- [ ] Test Avro parsing libraries for Ruby and check if there is anything equivalent to fastavro that could be used with Ruby
- [ ] Make a decision between using a new consumer or running from inside an existing application (Traction, Sequencescape)
- [ ] Take a decision on which framework to use for the consumer (options: a) reuse python b) recreate in ruby)

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by emrojo** [comment]
Demo implemented in python.
