### ISSUE TITLE
DPL-364 - As developers we would like to consolidate the tube barcode printing templates for Sequencescape and Limber to make the labels easier to print and reduce maintenance [C=M, V=4]

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#189]
**User story**
As developers we would like to consolidate the tube barcode printing templates for Sequencescape and Limber to make the labels easier to print and reduce maintenance

**Who are the primary contacts for this story**
Steve / James

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] There should be a single template for printing labels from Sequencescape and Limber for tubes
- [ ] The labels should print correctly on all Squix printers
- [ ] The labels should contain sufficient information
- [ ] In Sequencescape change the field names to send to pmb so they are the same as the Limber template
- [ ] In Limber change over to pmb v2

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
Replaces:
sanger/print_my_barcode#98

**Comment by stevieing** [comment]
main difference between limber and sequencescape:
- sequencescape - top_line, middle_line and bottom_line
- limber - first_line, second_line, third_line, fourth_line
- to get sequencescape to fit with new naming we would need to change lib/label_printer/label
- create a new template
- flipper actors

**Comment by stevieing** [comment]
Tasks:

- [ ] Duplicate the current Limber tube template
- [ ] test alignment on printers in Heron lab
- [ ] test alignment on 2 Toshiba printers in Ogilvie
- [ ] test alignment on 2 Squix printers in Ogilvie
- [ ]

**Comment by stevieing** [comment]
Testing current printers

H105bc

G216bc

heron-bc7

ssrtubebc-sq1

**Comment by Sangeetha-Bheeman** [comment]
Limber PR - https://github.com/sanger/limber/pull/1103/commits/c77a271204a01217b5a6674a90ba676446ec1017
