### ISSUE TITLE
GPL-nnn Sample Type field

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#19]
**Description**
CGAP guys have been asked to add a new field to the warehouse table sample type. Will this field be needed in Genomic LIMS? If so what changes need to be made?

**Users**
The primary users that have requested the work. e.g. John Smith

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by rl15** [comment]
Escalated to Charlotte Beaver <cb29@sanger.ac.uk> Friday, 3 April 2020 at 13:16

**Comment by stevieing** [comment]
From Laura Letchford: Sample type will determine whether samples need to be extracted before sequencing (primary and lysates) or not (extracts), so i imagine it will need to be imported and displayed somewhere so user knows what to do with the samples

**Comment by rl15** [comment]
Charlotte B wrote Monday, 20 April 2020 at 17:29

Hi Rich
 
I’ll raise this in the stand up tomorrow.
 
Thanks
Charlotte
 
From: Rich L
Sent: 20 April 2020 15:32
Subject: Re: Lysate Samples
 
Understood.
 
I can see that lysates are appearing in the MLWH table that marks the release of material from cellular to genomics
To my knowledge genomics are not using with that information.
As part of running these pilot samples can you find out from the genomics pipeline if they need to see this information anywhere? (processing will be different in genomics?)
 
...
 
regards
 
Rich L
