### ISSUE TITLE
DPL-398 - RVI Project - Research for preparing and running an initial test plate

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#194]
**Description**
As Sara S, Scott T and James M we would like to cherrypick and run a set of old covid positive samples in a 384-well plate through the Heron pipeline to check to see if the RVI project is viable. These samples will need to be cherrypicked from multiple source plates using a Biosero robot, be moved into a different Study (TBC), to have their sample name prefixes changed from 'heron', and to be manually submitted for library prep and sequencing in order to use a different primer panel.

**Who the primary contacts are for this work**
Sara S

**Knowledge or Stake holders**
Scott T
James M
Eduardo and Andrew from PSD

**Outputs / Acceptance Criteria**
1. Sara S to supply PSD with the list of source plates
2. PSD to check the samples are useable in terms of plate map data, and are not already in Sequencescape via some other route (some of the early samples were entered via manual manifests or via the Sentinel route and not picked, which means the Biosero method would blow up on the plate creation step due to duplication).
3. Sara S to supply PSD with the details of the Study to be used for the test, and what the sample prefixes would be changed to (from ‘heron’).
4. Sara S to confirm to PSD that the intention is to cherrypick 4  x 96-well full destination HT plates and quad stamp them into 1 x 384-well plate and run the 384 version of the heron pipeline.
5. PSD to test run the process in either UAT or in Training to see if it’s viable, and that no errors are thrown up by using a different Study or by doing a manual submission. Hopefully can use Andrews python script to simulate the Biosero picking stage using the actual plate barcodes. Then move Study and rename samples, create a manual submission, then run a version of the integration suite to process the plates through the Limber Heron pipeline.
6. Sara S to clarify with PAM that these samples will not show up in Heron reporting (as they will have a different Study)
7. Sara S and PSD to consider the implication of creation of Heron events in the MLWH for these plates.

**Additional context or information**
This is to work out how a this test run can be done, and to run it without making changes (and therefore risking) the existing Heron pipeline.
The Biosero method cannot be changed for this test, and neither can the Limber pipeline. So it will need to involve manual interventions at a couple of stages.

**Initial plan for running the test**
1. Cherrypick the positive samples from the chosen source plates into destinations on the Biosero in the normal way using the normal Biosero method. This will create ‘heron' named samples in the Heron Study in Sequencescape. It will also create events suggesting the source plates are completed and binned. The lab should then pause these destination plates until PSD and James M do the next 2 steps. They could manually scan the used source plates into a different LabWhere location so they do not appear ‘binned’.
2. Neil from PSD can then manually move and rename the picked samples on the 4 x 96-well destination plates into the chosen test study.
3. James M can then make a manual heron library prep and Novaseq sequencing submission on the 4 x 96-well plates, setting the required primer panel (he should use the heron submission template and library type or we won’t be able to run the plates in the existing heron Limber pipeline).
4. Lab can now proceed. They can scan one of the 96-well destination plates in Limber, and proceed with heron pipeline quad stamping of the 4 x 96-well destinations to create the 384 plate as normal (it should not use the automatic submission if a manual submission already exists).
5. Quad stamping and the rest of the Limber heron library preparation and sequencing pipeline should then work as normal, as long as the heron submission template and library type were used.

**Comment by andrewsparkes** [comment]
Tested manual submission of LTHR Cherrypick plates (heron submission template and setting non-standard primer panel) and Limber pipeline in UAT works fine. Auto-submission is bypassed.

**Comment by harrietc52** [comment]
What we did: 
- Created the file with the barcodes
- Copied file to dsm hot tmp directory 
`scp rvi_test2_barcodes_2b.csv dsm-01-prod.psd.sanger.ac.uk:/tmp`
- Move file to Crawler container
`docker cp /tmp/rvi_test2_barcodes_2b.csv <crawler container ID>:/code/migrations`
- Ran migration
`python run_migration.py back_populate_source_plate_and_sample_uuids ./migrations/rvi_test2_barcodes_2b.csv`

Also note:
We were unable to test on UAT or Training, as no single environment contains all the data which needs to match up i.e Training mongo didn't have plate map data and UAT MLWH didn't have MLWH data. A story has been created to better handle this.

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
