### ISSUE TITLE
DPL-337-1 - As an SSR I need a process diagram to explain the current submissions process for Hi-C to create a shared understanding of the current complexities

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#195]
**User story**
As an SSR I need a process diagram to explain the current submissions process for Hi-C to create a shared understanding of the current complexities

**Who are the primary contacts for this story**
Alice / Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] A process diagram which explains the current Hi-C submissions process
- [x] The diagram should be reviewed and agreed by the SSR and the long read team

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
[Process diagram for current Hi-C process] (https://lucid.app/lucidchart/1d28211e-f43c-4d68-a58c-5d503a09d9ea/edit?viewport_loc=-120%2C442%2C3222%2C1954%2C0_0&invitationId=inv_e93fa4c0-d501-400a-9b25-b2d1ff32a0bb#)

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
