### ISSUE TITLE
DPL-489 As a project lead (LW) I would like to identify if timestamps for points on the LMBC pipeline are recorded, or are not available, or have a potential proxy so that DNAP can build a picture of sample turn around time.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#209]
**User story**
As a project lead (LW) I would like to identify if timestamps for points on the LMBC pipeline are recorded, or are not available, or have a potential proxy so that DNAP can build a picture of sample turn around time.

**Who are the primary contacts for this story**
Lee W
Sara V
Mark TL

**Who is the nominated tester for UAT**
A good question TBD, would suggest one of the primary contacts?

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Identify if each desired point in the process has a timestamp recorded, has one or more possible proxy timestamps or no available data.
- [x] Where a timestamp or a proxy is available indicate where the timestamp is recorded e.g. database, table, column.

**Dependencies**
None

References
None

**Additional context**
Please prioritise finding timestamps for points in the process that bookend SSR <-> Faculty interactions.

Miro board, with process map and description of timestamps - https://miro.com/app/board/uXjVPX6xWqg=/?openActivity&utm_source=notification&utm_medium=email&utm_campaign=daily-updates&utm_content=view-activity

**Comment by TWJW-SANGER** [comment]
![Tats whiteboard ](https://user-images.githubusercontent.com/66008413/190647444-3a87b01d-a26e-47bc-b523-f24104515dc2.jpg)
Whiteboard of current LMBC process

**Comment by KatyTaylor** [comment]
Moving this to 'done'. Data sources for timestamps are recorded in the Miro board, which is linked in the description. 

There's still a bit of ongoing uncertainty about whether we can pull out any data for the SSR-faculty interactions:
- We have looked into pulling information from the SSR's RT queues (not a lot currently available, but should improve in the future as Liz C is working on adding custom fields).
- It was decided that Lee and the team would look into using the SSR's WIP spreadsheet instead.
