### ISSUE TITLE
DPL-492 As an active user of the MLWH I would like the REMARKS column in the Samples table to be populated to remove or reduce ambiguity or assumptions for new bioinformaticians starting at Sanger that are building software exchanging this data.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#210]
**User story**
As an active user of the MLWH I would like the REMARKS column in the Samples table to be populated to remove or reduce ambiguity or assumptions for new bioinformaticians starting at Sanger that are building software exchanging this data.

**Who are the primary contacts for this story**
Rich L

**Who is the nominated tester for UAT**
Can be tested internal by PSD team

 particularly fields (names)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] All fields in REMARKS column of sample table in MLWH populated with human readable description of fields purpose
- [ ] Descriptions exist at a minimum for columns: cid_sample_lims, name, common_name, sanger_sample_id, supplier_name, public_name, doner _id
- [ ] All non-prod and prod instances have same information.
 

**Dependencies**
None

References
None

**Additional context**
Column description/remarks are visible when running "SHOW FULL COLUMNS FROM sample;" on MLWH

Ambiguity surfaced in GSU pipelines team sprint planning where naming information is being passed into output files to external customer.

NPG are good at describing their tables, they could be used as reference.

**Comment by SujitDey2022** [comment]
Nice to have capability
