### ISSUE TITLE
DPL-494 Identify a list of Heron source plates that should be kept for RVI and a complementary list of plates that can be destroyed

### ISSUE THREAD

**Issue by sdjmchattie** [sanger/General-Backlog-Items#212]
**Description**
RVI need to identify a list of source plates to keep that meet the following criteria for Heron samples:

* Plates for all samples tested in 2020.
* All plates that had negative samples tested between January 2021 and April 2022 (inclusive).
* All the ONS samples* (but check to see how many extra plates this would be).

Source plate means the plate that samples were delivered on from lighthouse labs. It may be that plates are stored in boxes such that suitable plates are already together. The decision to keep or destroy may need to be done at the box level so using data from both the MLWH and LabWhere will be necessary.

A second list should be produced that is the complement of this one, showing the plates and boxes that can be destroyed.

**Who the primary contacts are for this work**
Stuart M, Katy T

**Knowledge or Stake holders**
Cristina A, Tina B, Adrianne L, Thomas W

**Additional context or information**
*ONS samples are those with a root sample ID starting with one of ("ONS", "ONN", "ONW", "ONC")

**Comment by TWJW-SANGER** [comment]
FYI ONS samples can be identified by having root_sample_id in the lighthouse_sample table starting with one of the prefixes below:
ONS
ONN
ONW
ONC

**Comment by sdjmchattie** [comment]
The spreadsheet with the data needed to do this filtering can be found at https://drive.google.com/drive/folders/1GdH--ZMKAF2eLo0wzbIXaEGG83Sh8rM4?usp=sharing
