### ISSUE TITLE
DPL-495 [Research] Come up with a plan of action to turn off HTTP access to our API endpoints.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#213]
**Description**
Our applications are no longer calling our API end points over HTTP. Our end point servers currently have a redirect from HTTP to HTTPS enforced by NGINX, which has been in place for a couple of months.

API client handling of redirects is often problematic **and** would like to use API Keys for security.
So we would like to encourage any end users to call the endpoints directly on HTTPS to avoid redirect issues and enable the secure use of API keys. 

We would like to come up with a plan of turning off HTTP access to our API endpoints. It should consider:

- All API/servers to be changed
- Notifying possible end users
- Rollback planning

Note we are not currently turning of the HTTP to HTTPS redirect for browser end points as browsers typically handle this well and removing the HTTP from the address will confuse users/bookmarks.

**Who the primary contacts are for this work**
PSD

**Knowledge or Stake holders**

**Additional context or information**

**Comment by SujitDey2022** [comment]
@TWJW-SANGER please can you help review the story and confirm if we need this story or if we can archive the same.

**Comment by TWJW-SANGER** [comment]
Closing in favour of #238
