### ISSUE TITLE
DPL-506 Bioscan OKR: Sample Data Export from STS

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#215]
**Description**
Discussion with Faculty and R&D about what plate and sample information needs to be exported from STS into Sequencescape (or imported to Sequencescape via manifest). Which plate and sample fields, and what are the data types. Example sample data would be useful.
The goal appears to be to have the information required at the end of the library prep pooling steps to create the file for mBrave containing the correct information. mBrave performs the de-plexing and species identification steps rather than NPG doing the analysis. Sequencing data gets uploaded to the BOLD (Barcode Of Life Data) system
 
**Who the primary contacts are for this work**
Scott T
Emma B

**Knowledge or Stake holders**
Mara L/ Lyndall (Bioscan faculty)
Andrew S

**Additional context or information**
This information will inform the discussion with the STS developers, and be the basis of what needs to be in the message schemas for RabbitMQ to import the data through into Sequencescape. 
Or, it will inform PSD what fields a sample manifest needs to handle.
It will likely include information that needs to be visible in the Sample Summary file export at the end of Bioscan library prep (e.g. Sample Name and/or ID) or needs to be passed through for mBrave for sequencing analysis.

**Comment by andrewsparkes** [comment]
From mtg 6th Oct:
Requires a discussion with the Bioscan faculty team, R&D are not clear on the Sample metadata details.
Also unclear is whether STS is the 'core' for information, as in the current testing STS may not be being updated once the samples get into the lysate prep.

**Comment by andrewsparkes** [comment]
Mtg 8th Nov clarified this won't be done for MVP. Will use manual Sequencescape sample manifests and submissions.

**Comment by TWJW-SANGER** [comment]
There is a branch point in the overall process where a lysate sample can go a different ANOSPP pipeline or continue through on the Bioscan pipeline or potentially through one or both pipelines.  (See process diagram in lucid)
 
I think the output of this story should be:

- [ ] Define the data required by DNAP from STS.
- [ ] Define how that data will be transferred on the manifest.
- [ ] Document the logic that determines the sample's routes through this pipelines?
- [ ] Can the route through the pipelines be stored in or inferred by the proposed manifest?
- [ ] If not how will the route through the pipeline be determined and when?

**Comment by harrietc52** [comment]
# Findings

## Sample Manifest

Expecting to create a new sample manifest template, based off an existing template (such as the stock plate). **Liz to confirm** which sample manifest template to base the new one off. 

This sample manifest will have the following fields:
- `Sanger Plate ID`: Automatically generated by Sequencescape. This represents the new barcode for the initial `LBSN-96 Lysate` plate.
-  `Sanger Sample ID`: Automatically generated by SS. This is generated from the type of study selected.
- `Supplier Sample Name`: Here, the `Partner Code` will be uploaded. This is a Bioscan provided field on the plate level, which will later be used to populate the `Group` field in the mBrave file. 
- `Sample Description`: Here, the `Sample Plate ID`, will be uploaded. This is a Bioscan provided field on the plate level, which represents the Lysate plate barcode. This will later be used to populate the `Sample Plate ID` field in the mBrave file. 
- `Control`: A dropdown containing three options: `PCR +ve`, `PCR -ve` and `Lysate -ve`.

### Study
A new study will also need to be created. 
This will need a name (Q: and what other data?)
The study is also used to generate the Sanger Sample ID (Q: what study information is use?)

## Submission

**Liz to confirm** with Scott/ Lesley if an automated submission would be possible (similar to Heron). This assumes there is no variation in the processings of the samples, and that all Bioscan samples are handled in the same way (e.g. same library type etc)

### Project

A new project with a name and linked cost code will need to be created.
