### ISSUE TITLE
DPL-508 Bioscan OKR: Non-destructive Robot Run Events to be Recorded and API

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#217]
**Description**
What are the required run events that need to be recorded during a method run of the non-destructive extraction robot? This informs what endpoints we need for the Bioscan API and the format of their inputs and outputs. 

**Who the primary contacts are for this work**
PSD
Who will report on this pipeline?

**Knowledge or Stake holders**
Scott T
Turnaround time project overlap? What are the key milestone timestamps that need recording?

**Additional context or information**
- What will the Bioscan API app and repo be called?
- Do we want something more generic or refactor/rename the Lighthouse app?
- Consider how we document existence of Postman and APIs linked to a specific pipeline. e.g. Confluence page. 

Initial thoughts on events: 
a.) Run started including Limber pick filename used 
b.) Source completed including 'lost' samples 
c.) Destination completed including source wells picked and controls added (Limber should already know this information so maybe not required)
 d.) Run completed 
e.) Run error (when possible, would only be possible for controlled error)

What about error recovery? If a run fails (so no completed event) how will we know if/when the robot is done? The bed verification in Limber is manually triggered by the LIMS user and may not match the actual time of the run.

**Comment by SujitDey2022** [comment]
@andrewsparkes is this story obsolete based on the diagram [here](https://lucid.app/lucidchart/b21a6020-df09-4be1-af69-26403ed467a1/edit?invitationId=inv_44a43cc4-479b-4e19-924c-2a0182f4255c&page=0_0#)

**Comment by andrewsparkes** [comment]
@SujitDey2022 Yes this is not required.
