### ISSUE TITLE
DPL-513 As a Team Lead (Tom) I would like the current location of plates in LabWhere to be available in the MLWH database so that queries combining sample types and locations can be easily performed by our customers.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#221]
**User story**
As a Team Lead (Tom) I would like a simple table to hold the current location of plates to be created in the MLWH database so that queries combining sample types and locations can be easily performed by our customers.

**Who are the primary contacts for this story**
Tom W
GSU
MLWH notices

**Who is the nominated tester for UAT**
Internal testing within PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Create a flat table in MLWH named **current_labware_location** with the following columns:
- "item_barcode" - the barcode on the stored labware e.g. "HT-135362"
- "location_barcode" - the barcode associated with the storage location e.g.  "lw-sm4072a-16152"
-  "full_location_address"  - the fully qualified address of the nested location e.g. "/Sanger/Reefer 2/R2 Racking 1/Shelf 2/UK Biocentre box MK 6"

- "lims_id" - id of the storage system this data comes from. Fixed to "LabWhere" for now.
- "stored_by" - the username of the person who placed the item there
- "stored_at" - datetime item was stored at this location
- "created_at" - datetime this row was created 
- "updated_at" - datetime this row was updated at

- [x] The item_barcode should be a primary key 
- [x] The location_barcode column  should also be indexed.
- [x] The "full_location_address" should also be indexed
- [ ] Table schema checked with the DBA team.

**Additional context**
LabWhere currently exports events to the MLWH Events database, but are very difficult and slow to find the current location of an item, and do not fire when a location containing child locations  is itself moved.

We would like to make the **current** location of plates/labware easily and quickly queryable from the MLWH.
The will reduce the development effort required to produce reports that need to locate samples of given types across the Institute.

Eventually we anticipate this table will be used by multiple different storage systems and received updates via a RabbitMQ interface. For now we would like the simplest possible solution in the time.

**Comment by javidahmed64592** [comment]
We decided to not use item_barcode as the primary key because Rails provides an ID automatically generated. We also have not added an index for full_location_address because we should be able to use location_barcode to look up locations. We added coordinate columns which will store the same integer values as in Labwhere.
