### ISSUE TITLE
DPL-537 - Update Ubuntu version used for docker image building process [by December 1st 2022]

### ISSUE THREAD

**Issue by Sangeetha-Bheeman** [sanger/General-Backlog-Items#224]
**User story**
As a developer from PSD I would like to have the Ubuntu-18.04 version used for docker image building process in all the applications upgraded to the latest, as it will be deprecated soon by December 1st 2022. Builds running on this version will now be failed during the scheduled brownout period to raise awareness.

**Who are the primary contacts for this story**
   Sangeetha B, Eduardo

**Who is the nominated tester for UAT**
   Someone within the team

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] update Ubuntu to the latest stable version in all the applications that automate the docker image building
- [x] test if the build runs successfully with the new version (builds develop)
   - [x] Sequencescape
   - [x] Lighthouse-ui
   - [x] Lighthouse
   - [x] samples_extraction
   - [x] Baracoda
- [ ] test if the build runs successfully with the new version (builds production)
   - [x] Sequencescape
   - [x] Lighthouse-ui
   - [x] Lighthouse
   - [ ] samples_extraction
   - [x] Baracoda

**Dependencies**
This story is blocked by the following dependencies:
None

References
This story has a non-blocking relationship with:
NA

**Additional context**
Refer to the link [https://github.com/actions/runner-images/issues/6002] for more details

List of applications that need upgrading(Please add if anything is missing from the list):
- [x] Sequencescape
- [x] Lighthouse-ui
- [x] Lighthouse
- [x] samples_extraction
- [x] Baracoda

Checked and already OK:
- Labwhere
- PMB
- Quanthub
- Crawler
- Wrangler
- Traction-UI
- Traction-service
- Gatekeeper
- Event warehouse
- Unified warehouse
- Sm workflow lims
- Asset audits
- SPrint
- Cherrytrack
- Automanual
- Stan (Core)

**Comment by andrewsparkes** [comment]
From the link:
Workflows using the ubuntu-18.04 image label should be updated to ubuntu-latest, ubuntu-20.04, or ubuntu-22.04

**Comment by andrewsparkes** [comment]
Samples extraction doesn't seem to have a version number, and merging develop into master doesn't seem to automatically trigger a build. Need input from someone with experience with this app.
