### ISSUE TITLE
DPL-552 Look into DBS timestamps and answer any outstanding questions on the Miro boards tables.

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/General-Backlog-Items#228]
**Description**
Look into the timestamps requested for the DBS pipeline (see table on Miro board here - https://miro.com/app/board/uXjVPX6xWqg=/?openActivity&utm_source=notification&utm_medium=email&utm_campaign=daily-updates&utm_content=view-activity).
Resolve any uncertainties and check if the desired data is present for a set of recent historical samples.

**Tasks**
Write query and extract data for:
- [x] relevant set of samples (validate against WIP spreadsheet)
- [x] stock plates
- [x] studies
- [ ] projects
- [ ] all timestamps in Miro table

**Who the primary contacts are for this work**
Lee, Sara V, Barbora, Katy

**Comment by KatyTaylor** [comment]
Data extracts so far - https://docs.google.com/spreadsheets/d/1l8-e5z0uGUzygUnv9KHbIBmCbRrlZMgLakMRi88bPY4/edit#gid=0

**Comment by TWJW-SANGER** [comment]
Lee would like this to be reduced to answering any remaining outstanding questions on DBS on Miro board.
