### ISSUE TITLE
DPL-553 Look into extracting data from RT system for TAT-WOW project 

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/General-Backlog-Items#229]
**Description**
Answer a number of questions around extracting data from the RT ticketing system, for use in the TAT-WOW project.
More detail to be added.

**Who the primary contacts are for this work**
Lee, Katy

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by TWJW-SANGER** [comment]
I'm going to discuss this with Lee next week to see if we can close this off, or come up with something a bit more concrete.

**Comment by TWJW-SANGER** [comment]
Agreed that this is out of scope for this initial project.
