### ISSUE TITLE
DPL-575 Create view or stored procedure for LCMB-ISC samples

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/General-Backlog-Items#232]
The queries that came out of https://github.com/sanger/General-Backlog-Items/issues/223 all share a common core query, which retrieves the list of samples that are relevant to the LCMB-ISC pipeline. At time of writing, this is the query:
```
SELECT ewh_sample_id, sample_uuid_bin, sample_uuid, sample_friendly_name
FROM
(
  SELECT DISTINCT s.id AS ewh_sample_id,
                  s.uuid AS sample_uuid_bin,
                  insert(insert(insert(insert(lower(hex(s.uuid)),9,0,'-'),14,0,'-'),19,0,'-'),24,0,'-') AS sample_uuid,
                  s.friendly_name AS sample_friendly_name,
                  m.value AS pipeline
  FROM metadata m
  JOIN events e ON e.id = m.event_id
  JOIN event_types et ON et.id = e.event_type_id
  JOIN roles r ON r.event_id = e.id
  JOIN role_types rt ON r.role_type_id = rt.id
  JOIN subjects s ON s.id = r.subject_id
  WHERE m.`key` = 'order_type' AND m.value IN ('LCMB', 'ReISC')
    AND m.created_at > '2022-05-10'
    AND rt.`key` = 'sample'
    AND et.`key` = 'order_made'
) AS all_lcmb_reisc_samples_by_pipeline

GROUP BY all_lcmb_reisc_samples_by_pipeline.ewh_sample_id
HAVING Count(*) > 1
;
```

However, the source of truth for the query should be the pull request, in case it changes - https://github.com/sanger/event_warehouse/pull/314/files

This should be extracted into a view or a stored procedure, so that it can be easily referenced in all the queries, instead of duplicating code. This will greatly improve readability, and also make it more obvious that they all have this common core. The view or stored procedure could also be useful for people in other projects who want to identify samples associated with this pipeline (e.g. Scott in RT 761561).

It would probably make sense for the view to be in the Event Warehouse, since this is where the data is coming from, although theoretically there could be similar future queries that query across both the Event and the Unified Warehouse (MLWH).

**Comment by KatyTaylor** [comment]
The equivalent view for the DBS pipeline could now be made too.

**Comment by TWJW-SANGER** [comment]
This is good idea, but out of scope for the initial project. We will have to see what the next phase wants to do before prioritising.

**Comment by SujitDey2022** [comment]
Hi @TWJW-SANGER @yoldas, please can you help confirm if this story needs to be on the board and in the backlog or we can archive it.

**Comment by TWJW-SANGER** [comment]
@SujitDey2022 Hi Sujit - I think we can remove it of the board. We can always bring it back if TATS&WoW gets another phase.
