### ISSUE TITLE
DPL-613 Report: Retrieve all plates for given date range

### ISSUE THREAD

**Issue by neilsycamore** [sanger/General-Backlog-Items#240]
Back in September/October @sdjmchattie worked on gathering metadata about specific source and destination plates to help in the production of a list of Heron plates to that would enable us to identify plates to be destroyed/preserved based on a series of criterias. This was detailed in the following github entry: DPL-493 https://github.com/sanger/General-Backlog-Items/issues/211

We have received a request to produce an inventory report of the samples between the time period of first data to date, aiming to get a break down of what is currently stored a month-by-month breakdown. I would like to request a data extraction similar to the one provided back in October ([RT769282](https://rt.sanger.ac.uk/Ticket/Display.html?id=769282)), but for all source and destination plates to date (Sampling dates from first data – to date). Would it be possible to re-run Stuart’s data retrieval script for the plates in that range? We would require the following information to generate the report and a Month breakdown:

·        Sampling dates from first data – to date

·        LHR RT were the original RT plates that sometimes came directly from CGaP and other times from samples sent by lighthouses.  These are from the very early stages of the pandemic.                                       

·        LTHR RT are the equivalent plates, but for tailed samples.                                                           

·        LHR Cherry-pick are the destination plates from cherry-picking using Beckman and Biosero

·        LTHR Cherry-pick are the tailed samples of the above

·        Information to be included in the report:

o   Plate Purpose

o   Plate Barcode

o   Sample Count

o   Min Date Tested

o   Max Date Tested

o   Is sequenced

o   Fully Qualified Location 

Who the primary contacts are for this work
Stuart M, Camilo G, Adrianne L

Knowledge or Stake holders
Adrianne L, Tanya B, Fernanda N, Camilo G

**Comment by sdjmchattie** [comment]
I have added some content to the README for the data patch archive.  I will apply these operations on Sequencescape and the MLWH next week.  Best not to push heavy requests through those systems late on a Friday!

**Comment by sdjmchattie** [comment]
Both exports are now on Google Drive where it can be shared with Adrianne and others.

**Comment by sdjmchattie** [comment]
The merge request for the write up of this task is in https://gitlab.internal.sanger.ac.uk/psd/data-patch-archive/-/merge_requests/17
