### ISSUE TITLE
DPL-615 - As developers we need to review our current applications and repositiories to try and reduce our technical debt

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#241]
**Description**
As developers we need to review our current applications and repositiories to try and reduce our technical debt

**Who the primary contacts are for this work**
Steve

**Knowledge or Stake holders**
PSD, Scientific Operations, Pipeline solutions

**Additional context or information**
Process to do this:
- create a lucid chart or miro board which lists all of our applications
- add a description for each app and it's current usage
- add technical debt that needs to be fixed e.g. Node, Ruby, security risks (including certificates) and remediation that we need to do to fix it
- Make a decision on whether we want to continue to support, open source it, offer as a service or deprecate remove
- If we want to open source them or offer as a service what are the next steps?
- Review our current repositories (there are 70!) and see if any can be archived or deleted.
- If we want to deprecate:
- list the current functionality and see whether it is still needed or can be moved and then create stories to move it
- Calculate the work needed to shut applications down that we need to and measure that against the resource that it will save

**Comment by TWJW-SANGER** [comment]
Refined into DPL-634 and DPL-635 to manage the scope
