### ISSUE TITLE
DPL-628 As PSD TL I want to ensure no RVI samples are in the Beckman robots DART database so that it is impossible to pick RVI samples under the Heron study. 

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#251]
**User story**
As PSD TL I want to ensure no RVI samples are in the Beckman robots DART database so that it is impossible to pick RVI samples under the Heron study. 

**Who are the primary contacts for this story**
TW Andrew S

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] If we can determine the RVI plates currently in storage, ensure none of these plates appear in the DART database

**Comment by andrewsparkes** [comment]
Some thoughts:

There was some discussion about picking both Heron (via Beckman) AND RVI (via Biosero) samples from the same mixed plates (for source plates before consolidation was implemented). Can we confirm whether that idea has been abandoned? Simpler for us if it has.

This solution does not prevent the RVI plates being loaded onto a Beckman. I think the robot would write a Heron 'no plate map' data event for the source plate and return it to the input stack. Might need to consider how the Lab user is going to understand why that has happened. Perhaps Box Buster flags plates as 'for RVI'?

Also, how is that list of RVI plates input, maintained, visualised and queried? Is it a one off list or modifiable? Is it in a database? Do we need screens for inputing and querying the list?

**Comment by TWJW-SANGER** [comment]
Removing from board after replanning approach. We might come back to this.
