### ISSUE TITLE
DPL-634 As a TL (Tom W) I would like a map of applications vs technical debt so that we have visibility of required updates.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#252]
**Describe the Housekeeping**
As a TL (Tom W) I would like a map of applications vs technical debt so that we have visibility of required updates.

**Who the primary contacts are for this work**
Tom W, Steve I

**Knowledge or Stake holders**
PSD, Scientific Operations, Pipeline solutions

**Additional context or information**
For the product/application list see the Products page on the PSD public confluence website.

EOL = End of Life

**Acceptance criteria:**
- [x] Create a lucid chart or miro board or table which lists all of our applications
- [x] For each application add a column for language version & EOL date if known, framework version & EOL date if known, OS version & EOL date if known, SSL cert location, SSL expiry date, other dependencies, known security risks
- [x] Colour any dependencies that are past EOL or expiry date RED
- [x] Colour any dependencies that have EOL or expiry date within the coming year YELLOW

**Comment by Sangeetha-Bheeman** [comment]
https://drive.google.com/file/d/1l-dIp2SHJLVTUYV05qCYMyCJbtoFL5B9/view?pli=1

**Comment by sdjmchattie** [comment]
The document looks good.  Might I suggest using an orange colour halfway between yellow and red to indicate that a dependency is going to be out of support in the next 3 months?  Those will need to be prioritised above the dependencies that still have 3 to 12 months left.

**Comment by emrojo** [comment]
Some things I saw on reviewing:
- Asset audits uses mysql same as other apps
- Cherrytrack uses mysql too; sqlalchemy is the library that abstracts the access to the database
- Lighthouse uses both mongo and mysql
