### ISSUE TITLE
DPL-635 As a TL (Tom W) I would like to review our repos (github & gitlab) and see if any can be archived

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#253]
**Describe the Housekeeping**
As a TL (Tom W) I would like to review our repos (github & gitlab) and see if any can be archived

**Additional context**

- [ ] Generate list of repos to archive
- [ ] Review with team 
- [ ] Archive repos team agree with

**Comment by SujitDey2022** [comment]
@TWJW-SANGER added a new label as  - 'OKR 2023'

**Comment by Sangeetha-Bheeman** [comment]
https://docs.google.com/spreadsheets/d/1_07RSij3a_BRhxHnWQ8Hp8dQZLJKTVBkw-xSlG9OQKY/edit#gid=0

**Comment by TWJW-SANGER** [comment]
Regarding Automanual - looking  and running the code [here](https://github.com/sanger/automanual/blob/develop/ss_script.sql)  it is only update sequencing runs under the "UK  Biobank Main Phase Study"  (id=5902).

This study has finished so we can archive the repo.

I suspect (but have to confirm) that Automanual update of manual qc passes was required because the data analysis and QC was performed outside of the normal NPG analysis pipelines.

**Comment by Sangeetha-Bheeman** [comment]
Trying to use this script https://github.com/sanger/deployment/issues/184 to find out any ips calling the automanual and couldn't find any.

**Comment by Sangeetha-Bheeman** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<body>


Github repositories |  
-- | --
lighthouse-ui | https://github.com/sanger/lighthouse-ui
traction-legacy | https://github.com/sanger/traction-legacy
automanual | https://github.com/sanger/automanual
sanger_barcode | https://github.com/sanger/sanger_barcode
label_printer | https://github.com/sanger/label_printer
sequencescape_search | https://github.com/sanger/sequencescape_search
ss_cherrypicking | https://github.com/sanger/ss_cherrypicking
  |  
Gitlab repositories |  
  |  
ukb_docker | https://gitlab.internal.sanger.ac.uk/psd/ukb/ukb_docker
ukb_report | https://gitlab.internal.sanger.ac.uk/psd/ukb/ukb_report
ukb_site | https://gitlab.internal.sanger.ac.uk/psd/ukb/ukb_site


</body>
</html>

**Comment by harrietc52** [comment]
@Sangeetha-Bheeman It might be also worth checking there is no code for the above repos in the provision/ config or deployment repo. I imagine there will be at least deployment code for Automanual
