### ISSUE TITLE
DPL-636 As a TL (Tom W) I would like the Heron deployment process to have one location for SSL certificates & make it possible to deploy individual app separately so that any team member can be confident in deploying.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#254]
**Describe the Housekeeping**
As a TL (Tom W) I would like the Heron deployment process to have one location for SSL certificates & make it possible to deploy individual app separately so that any team member can be confident in deploying.

**Additional context**

- [x] Refactor SSL certificate location so it is only stored in one location for deployment rather than 3 (could this be shared by other app's deployment processes?)
- [x] Enable deployment of say Rabbit Message Queue, Lighthouse UI etc separately (assuming not enormous work?)
- [x] Document process of deploying the whole stack or individual applications in an md file in the deployment repo.

**Comment by yoldas** [comment]
Certificates were stored in different places in the past. See the PR [Clean up use of and update ssl certificates](https://github.com/sanger/deployment/pull/100), specifically the ssl_certificates role's [README](https://github.com/sanger/deployment/pull/100/commits/818c07885e671b52c374829bc89a0bf5873107c8#diff-c762f64ff5e2c0f976683da5859f1bfdf56779bc983337925d23998f82465e73R12): "Currently the psd_sanger_ac_uk public certificate and private key are stored in 3 locations in the deployment project. role: `deploy_heron_stack`, role: `deploy_samples_extraction` and here in role `ssl_certificates`. Next step is to have these three roles use the ssl_certifcates only."

However, the project was refactored to have one source for the certificates, i.e., in ssl_certificates role. See the PR [Dpl560 update certificates](https://github.com/sanger/deployment/pull/283), specifically the commit [Refactor to only get the certificates from one source](https://github.com/sanger/deployment/pull/283/commits/292b1ca9a43359347ff97742987bd5f0a6cfe965). Note that certs folder was removed from deploy_heron_stack role.

Now SSL certificates are already stored under `ssl_certificates` role and the issuer certificate is stored under `ssl_issuer_certificate` role in the deployment project. 

The certificates are copied from  single source to different paths on target hosts. The apps expects certain paths and needs access permissions to use them.

TODO: Check why there is a separate folder in ssl_certicates role for ToL. 

TODO: Check why rabbitmq role has its own copy of the issuer certificate; not using from ssl_issuer_certificate_role.

**Comment by yoldas** [comment]
- Check why rabbitmq role has its own copy of the issuer certificate; not using from ssl_issuer_certificate_role.

This looks like a left-over from older code as the certificate locations are unified into two roles:  ssl_certificate and ssl_issuer_certificate.

roles/install_dependencies includes roles/rabbitmq

setup_sequencescape.yml, setup_single_apps.yml and setup_warehouses.yml include roles/install_dependencies **after including roles/ssl_issuer_certificate and roles/ssl_certificates.**

The following files are exactly the same (ansible-vault view):

CA file in rabbitmq role:
roles/rabbitmq/certs/main/Genome_Research_Ltd_Certificate_Authority-cert.pem

CA file in ssl_issuer certificate:
roles/ssl_issuer_certificate/certs/main/Genome_Research_Ltd_Certificate_Authority-cert.crt

Therefore, I am removing the CA file in the rabbitmq role and the task to copy it from roles/rabbitmq/tasks/configure.yml .

**Comment by yoldas** [comment]
- Check why there is a separate folder in ssl_certicates for ToL.

Using ssl_certificates role, the cert and key files are copied from **current** ssl_certificate_group. There should not be a need for a separate  
directory for ToL as ssl_certificates/certs/tol as it is confusing.

I am moving the ssl_certificates/cert/tol to an archived directory.

**Comment by yoldas** [comment]
There are already separate playbooks to deploy individual apps for Heron stack such as deploy_heron_rabbitmq.yml and deploy_lighthouse_ui.yml .
