### ISSUE TITLE
DPL-661  Bioscan - Create network drive folder to hold created mBrave files

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#267]
**User story**
As PSD we want to generate the Bioscan mBrave files and store them in a directory accessible to the faculty team. We need a network directory with suitable permissions set up to allow this.

**Who are the primary contacts for this story**
PSD

**Who is the nominated tester for UAT**
Bioscan faculty team (TBC who)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] PSD software to be able to write files to the directory (RW access)
- [ ] Bioscan faculty team to be able to read from the directory (R only access)
- [ ] Directory to be large enough to hold several years worth of files

**Dependencies**
This story is blocked by the following dependencies:
None

References
This story has a non-blocking relationship with:
- DPL-573

**Additional context**
Expecting 1 file per month. We have an example file to judge filesize.

**Comment by yoldas** [comment]
We are waiting an example mBrave file to make an estimate on the total size of the drive. We are taking "several years" as 5 years. The total size will be 5 X 12 X filesize and tolerance.

**Comment by TWJW-SANGER** [comment]
After discussion at standup - we decided a simpler approach to allow the lab team to download the file and put in whatever folder they desire will be more flexible and suffice.
