### ISSUE TITLE
DPL-673 As a TL I would like to prepare Baracoda to connect to the new upgraded database so we can coordinate the upgrade process with the DBAs.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#269]
**User story**
As a TL I would like to prepare Baracoda to connect to the new upgraded database so we can coordinate the upgrade process with the DBAs.

**Who are the primary contacts for this story**
TW Edwin R

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Change baracoda connection string for the new Postgres DB (Ask Edwin R for details)
- [x] Update credentials repo with the new details
- [x] Arrange new database upgrade time (downtime of about 1 hour) with Stakeholders
- [x] Schedule production release to be after the DBA team upgrade the Postgres dB
- [x] Shutdown Baracoda prior to DB upgrade
- [x] Once DB upgraded deploy changes and start Baracoda

**Comment by TWJW-SANGER** [comment]
New connection string provided by DBA team. 
TW SM SB SD EMR have the details.

**Comment by Sangeetha-Bheeman** [comment]
Steps to start and stop the service:

`docker service ls`

To stop the service

`docker service scale <name_of_service>=0`

After the db upgrade, to start the service

`docker service scale <name_of_service>=1`
