### ISSUE TITLE
GPL-436 Deployment of lighthouse related services

### ISSUE THREAD

**Issue by pjvv** [sanger/General-Backlog-Items#27]
**User story**
As a dev team we would like to update the deployment project to be able to deploy the new lighthouse related services:
* crawler
* baracoda
* lighthouse

**Who the primary contacts are for this story**
Philip

**Acceptance criteria**
To be considered successful the solution must allow:
1. add playbooks for each project
2. add services to the Docker stack

**Additional context**

**Comment by emrojo** [comment]
Redeploying any service requires to restart nginx as well:

https://github.com/docker/compose/issues/2003
