### ISSUE TITLE
DPL-687 As TL (Tom) I would like to create a rough user story backlog for the 007c Single Cell RNA Core Pipeline so that we can provide an estimate.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#276]
**User story**
As TL (Tom) I would like to create a rough user story backlog for the 007c Single Cell RNA Core Pipeline so that we can provide an estimate.

**Who are the primary contacts for this story**
TW LS ST

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] A rough number of user stories required to implement the MVP version of the pipeline
- [x] Annotated process map

**Additional context**
See email from LS for Lucid Chart link to process map.
Timebox the effort to about 1 days. Only a rough order of magnitude estimate is needed.

**Comment by harrietc52** [comment]
Annotated Process Map [here](https://lucid.app/lucidchart/180f2f7a-c15a-4a82-a904-55ae64d56753/edit?viewport_loc=-1479%2C-1448%2C3938%2C2261%2C0_0&invitationId=inv_f00fb666-4667-4ed6-9133-b94b01676a37)

**Comment by harrietc52** [comment]
# On Deployment

## SS console 
We want to run this to create the Chromium Chip in the AssetShape table, so it can be used by a Plate Purpose. 

```
require './lib/plate_map_generation'
PlateMapGeneration.generate!
```

**Comment by harrietc52** [comment]
Email Lucid link to Lesley, Abby Crackett, Chris Henderson for awareness. But Lesley is on annual leave until 2rd April, so book in a meeting for when she is back

**Comment by harrietc52** [comment]
# Estimating stories

## Summary
7 x L, 7 x M


## Breakdown

**Bed verifications:**
11 (but use existing Cardinal and 5’ Chromium?)
 = 1 x M 

**Labware Creators:**
Isolated PBMC
Donor pool plate (PBMC donor pool -> Chip)
Chip -> 10x HT 5' GEM 
10x HT 5’ cDNA PCR XP
Custom library pool 
 = 5 x L 

**Intergration test:**
 = 1 x L

**New Presenters:**
10x HT 5’ GEMS
 = 1 x M

**SS config (template/ stock purpose):**
 Submission at XP branch step (automated?)
 = 1 x M

**Limber pipeline/ purpose config:**
Cardinal
New pipeline part
5’ chromium pipeline
Branches for chromium pipeline
QC CSV file creation 2 creation/ 1 upload
 = 1 x L

**Drive download files (Limber exports contr):**
 = 4 x M 

**Printing/ Barcode format:**
Chip label
 = 1 x M

**Tags**
Check at 10x HT 5’ PCR
 ?
