### ISSUE TITLE
DPL-694 Bioscan - Can we cut down the MVP design any further?

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#280]
**Description**
The faculty team leader has expressed a concern about the time it might take for PSD to develop the Bioscan pipeline.

As PSD and R&D we need to take another look at the MVP design and see if we can reduce the overall development time any further. Then come up with the revised story list and sizings.

**Who the primary contacts are for this work**
PSD

**Knowledge or Stake holders**
Scott T
Lesley S
Emma B

**Additional context or information**
### Not tracking the Lysate plate preparation on the new Beckman robot
This would simplify the start of the pipeline and make the Lysate plate the entry point straight into the Library prep pipeline.
Removes stories about the Lysate plate pipeline configuration, robot bed verifications, the labware creator to randomise the control well locations, and the API endpoint for the Beckman method to ask where the controls should go.
**Pro's:**
The Labware creator is a large story. Unknown whether it can event create the control samples needed. Also needs input from Beckman around restrictions (if any) on the randomisation process.
**Cons:** 
Configuration story and integration suite stories already 90% done.
Lysate plates would have to enter the LIMS (with their controls) via Sequencescape Sample manifests.
Increased risk that you'd have user mistakes on the robot. 
Controls would have to be in fixed locations set in the Beckman method which makes it harder to detect plate swaps.
Loss of tracking of displaced samples, which would never be in the LIMS.
Ongoing cost in time for faculty team and R&D to track this stage.
Revision of Beckman method development to fix controls and not use LIMS API (currently in SAT stage). Potential further development work and cost here if you want to return to this at a later date. And possibly additional cost now to change it from agreed API interaction in URS and SAT documents.
**Time saved:** 1 x L (1 week), plus 1 x M (3 days) for PSD

### Not tracking the tag plate creation
Instead track which index was used for each PCR plate (1-24).
Removes stories to create the scripts to generate tag groups and tag layout templates, and to create instances of the tag plates for use in the pipelines.
**Pro's:**
Save the story to create the scripts.
**Cons:** 
This was already the MVP design to avoid having to create a replacement for the Gatekeeper application.
Tag clash detection at pooling would not be possible. Or we'd need some new method of tag clash prevention using the tag plate 1-24 indexes (so more work then).
mBrave file creation would not be possible with some (new) matching up between a (new) stored tag plate index and a listing of unique tag indexes by tag plate index for the 9216 combinations (so more work to do that).
**Time saved**: 1 x L (1 week) for PSD

### Not creating the mBrave file
Instead R&D have to generate it manually using google sheets.
**Pro's:**
Removes story for generating the mBrave file.
**Cons:** 
Risk that manual generation of file will be done incorrectly.
It takes ongoing R&D time each month to generate.
Story can be worked on in parallel.
**Time saved**: 1 x M (3 days) for PSD

### Not using a RabbitMQ queue to export to Traction
Instead use an API endpoint (new) on Traction in order to create the Traction side library object.
Removes stories around creating a RabbitMQ message schema, generating a message, creation of queues/shovels/exchanges via the deployment project, and creating a Sequencescape side feedback consumer. Adds stories for creating an endpoint in Traction and interaction with it from Limber/SS.
**Pro's:**
Possible re-use of new Traction API library creation endpoint
**Cons:** 
The main con is that it creates a dependency in Sequencescape on Traction. This is against the PSD strategy of using queues to de-couple applications. Although using an API endpoint is not as good as using the message queue it is a step in the right direction. It means we do not need to do any ui work in Traction and it could be moved to a message queue later (Lab user would not see any difference). It also adds a library creation endpoint in Traction which is reusable. @stevieing will create 2 stories, one for re-barcoding and one for the library creation endpoint.
**Time saved**: 1-2 weeks (2 x L and 1 x M RabbitMq stories removed, 1 x M Traction API endpoint creation and 1 x M Sequencescape interaction with traction API endpoint stories added) for PSD

### Scrapping LIMS tracking altogether and they continue to use Excel/Google sheets
Not a serious option but included for completeness.
**Cons:** 
No persisted tracking of the samples or pipeline in LIMS.
Lots of risk of user mistakes throughout.
Significant ongoing time investment required by faculty team and R&D to do the tracking manually.

**Comment by harrietc52** [comment]
## No Traction at all
pros:
rid of stories
compound sample story
DPL-664/ DPL-665/ DPL-666/ 667 remove RabbitMQ / api story
simplify the Limber panel UI story
DPL-678/ DPL-573 job create smaller
DPL-665

cons: use existing manual process to get info into Traction

## Controls are fixed 
pros: DPL-568 but not have the logic of +ve/-ve positions
future proofing, can then making random later
cons: still need to create control samples in creator

## mBrave file
Create mBrave file via API or job. 

API
pro: don't need network drive, could reuse existing code
con: no persistence, not sure if possible for time takes to build mBrave

Job:
pro: no risk of time out
con: need network file to put it somewhere

**Comment by harrietc52** [comment]
Safe to work on:
modify pooling of 4 tubes to 24 tubes
DPL-573 creation of mBrave
DPL-541 tag creation scripts 
DPL-659 paging sample list

**Comment by andrewsparkes** [comment]
Waiting on R&D/faculty decision on whether Traction export can be done manually for MVP or needs the PSD-designed solution via Limber and Traction API (or RabbitMQ).

**Comment by harrietc52** [comment]
Update from Scott:

> Hi 
We can now confirm that we would like to request the ‘MVP light’ option.
This is the ‘No Traction at all’ option as described in DPL-694, where a manual submission is required from the SSR.
