### ISSUE TITLE
DPL-696 Upgrade Ubuntu server versions on UAT and training FCE from v18.04 to 20.nn

### ISSUE THREAD

**Issue by Sangeetha-Bheeman** [sanger/General-Backlog-Items#284]
**Housekeeping**
 To upgrade Ubuntu to 20.nn in all the UAT and training environment.  The End of Life for v18.04 is 30th April 2023

The primary requirement is captured as part of the sanger/cherrytrack#36 ticket which can be converted and split into smaller user-stories.

**Who are the primary contacts for this story**
e.g. Sangeetha (don't include surnames in public repos)

**Who is the nominated tester for UAT**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:

Upgrade of the UAT and training servers to 20.nn 

- [x] Sequencescape
- [x] Limber
- [x] Lighthouse, Crawler, Lighthouse-ui, Baracoda
- [x] Traction
- [x] Gatekeeper
- [x] Assest audits
- [x] Print_my_barcode
- [x] Labwhere
- [x] sm_workflow_lims
- [x]  Focal Ubuntu 20.04 image exists in provision and can be used to create an instance if required
- [x] Monit 
- [x] Samples extraction
- [x] Trac-smrtlink
- [ ] Unified_warehouse

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

For production upgrade:
https://github.com/sanger/General-Backlog-Items/issues/292

**Comment by Sangeetha-Bheeman** [comment]
Commands to upgrade to Ubuntu 20.04:

`
$ sudo apt update 
$ sudo apt list --upgradable (optional - to check what will be upgraded)
$ sudo apt upgrade

$ sudo reboot (if required to reboot)

$ sudo do-release-upgrade 
`

Steps to solve the openssl issue:
`
-  rbenv uninstall 3.2.0
-  sudo apt-get install autoconf bison patch build-essential rustc libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libgmp-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev uuid-dev
-  sudo apt-get install autoconf bison patch build-essential rustc libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libgmp-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev uuid-dev
-  rbenv install 3.2.0
-  Move shared folder in /var/www/sm_workflow_lims/ (mv shared shared-ddmmyy) and then delete it later (rm -rf shared-ddmmyy)after successful deployment of the application
`

**Comment by Sangeetha-Bheeman** [comment]
List of UAT, training FCE

https://docs.google.com/spreadsheets/d/1JSKk2KD914-_DJFl50ViXHwKnF18pBM_r_G_y5V2FlE/edit#gid=0

**Comment by emrojo** [comment]
Changes in provision project: 

https://github.com/sanger/provision/pull/15

**Comment by emrojo** [comment]
In UAT, there are some machines (monit, samples extraction, warehouse and trac-smrtlink) that are still in ubuntu 18. There are other machines in ubuntu 22, that would make sense to rollback to ubuntu 20 (gatekeeper).
In training, same issue with monit and samples extraction.

Apart from the issues during the upgrade, monit is currently showing some of the machines as failed because the root file system is over 85%. Not for this one, but as part of the next story DPL-697 we should fix this too.
