### ISSUE TITLE
DPL-697 Upgrade Ubuntu server versions on production FCE from v18.04 to 20.nn [due 30/04/23]

### ISSUE THREAD

**Issue by Sangeetha-Bheeman** [sanger/General-Backlog-Items#285]
**Housekeeping**
 To upgrade Ubuntu to 20.nn in all the production FCE.  The End of Life for v18.04 is 30th April 2023

The primary requirement is captured as part of the sanger/cherrytrack#36 ticket which can be converted and split into smaller user-stories.

**Who are the primary contacts for this story**
e.g. Sangeetha (don't include surnames in public repos)

**Who is the nominated tester for UAT**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
Upgrade of the production FCE to 20.nn for the below: 
- [ ] Sequencescape
- [ ] Limber
- [ ] Lighthouse, Crawler, Lighthouse-ui, Baracoda
- [ ] Traction
- [ ] Gatekeeper
- [ ] Assest audits
- [ ] Unified_warehouse
- [ ] Print_my_barcode
- [ ] Labwhere
- [ ] sm_workflow_lims

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Comment by SujitDey2022** [comment]
Need to check if [DPL-752](https://github.com/sanger/General-Backlog-Items/issues/292) is the same work item as this

**Comment by TWJW-SANGER** [comment]
Following our meeting on 9/5 we agreed to deprecate this in favour of individual stories for each production service upgrade.
