### ISSUE TITLE
DPL-704 New STS plate barcode template 

### ISSUE THREAD

**Issue by Sangeetha-Bheeman** [sanger/General-Backlog-Items#286]
As CASM Senior Scientific Manager (Rob T) we would like a template that can print barcodes for plate labels.

**Who are the primary contacts for this story**
 Rob/Sangeetha

Main story:
https://github.com/sanger/General-Backlog-Items/issues/278

**Comment by TWJW-SANGER** [comment]
Quick question. Do we know the printer type, label size and rough layout? Or is that for refinement?

**Comment by Sangeetha-Bheeman** [comment]
Printer type:  Toshiba
Label type: plate label
Layout to be copied from an existing plate template: sqsc_96plate_label_template_code39(Sequencescape). But will require further changes to suit the requirements

**Comment by Sangeetha-Bheeman** [comment]
Below is the sample data for the plate barcode template "sts_plate_barcode_template":

`{
	"print_job": {
		"printer_name": "h218bc",
		"label_template_name": "sts_plate_barcode_template",
		"labels": [{
			"top_left": "5-APR-2023",
			"bottom_left": "Cherrypick",
			"top_right": "HT-115228",
			"bottom_right": "DN935681O",
			"barcode": "DN935681O",
			"label_name": "main_label"
		}],
		"copies": "1"
	}
}`

![plate_barcode_label](https://user-images.githubusercontent.com/93536758/230117467-37020074-7995-41f4-a3e4-880a13506f5c.jpeg)
