### ISSUE TITLE
DPL-711 As a team lead I would like to users be able to submit samples for sequencing on the new instrument type of NovaSeqX so that we can support the latest sequencing technology.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#287]
**User story**
As a team lead I would like users to be able to submit samples for sequencing on the new instrument type of NovaSeqX so that we can support the latest sequencing technology.

**Who are the primary contacts for this story**
TW
Richard R

**Who is the nominated tester for UAT**
Tristram B
Liz C

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Users should be able to submit samples to the new NovaSeqX instrument in Limber/SequenceScape using a new Submission Template / Request with an appropriate name.
- [x] SequenceScape will need a new InstrumentType of NovaSeqX.
- [x] Users can assign a flow cell with names "10B" to NovaSeqX submissions.
- [x] "10B" flow cells have 8 lanes (Instrument is apparently similar to HiSeqX).
- [x] "10B" flow cells have 100PE or 150PE read lengths.
- [x] Users can request NovaSeqX sequencing from the “request additional sequencing” page.

**Additional context**
There are no new library types.
There will be a requirement for another flow cell expected later in the year. It will be called "1.5B" and will have only 2 lanes.

**Comment by emrojo** [comment]
Initial set of tasks, but still more research will be needed. Feel free to correct this:

** To define the new dashboard **
- [ ] Create a new request type of type HiSeqSequencingRequest (look at the settings for the existing request type which I would think by the name that is: illumina_htp_novaseq_6000_paired_end_sequencing). New name for the request type: illumina_htp_novaseq_plus_paired_end_sequencing??
- [ ] Create a new Pipeline record in the database that has a maximum number of elements of 8 (8 requests maximum in  a batch) (Map to 8 lanes?). Name of the record: 'Novaseq+'?. Set this pipeline as active. This will define the new dashboard and will be shown in the 'Pipelines' screen in SS.
- [ ] Connect Pipeline with the new request type so they records will be displayed in the dashboard (new record in table pipeline_request_type)

** To order work with new pipeline **
- [ ] Create new SubmissionTemplates as copy of any template that has in the name: "NovaSeq 6000 Paired end sequencing". Modify the requests_type_ids_list in the submission_parameters_column to use the request type id of the new illumina_htp_novaseq_plus_paired_end_sequencing

** To test it**
- [ ] Run integration suite using one of the new submisison templates. Check that at the end there is a new request showing in the dashboard in SS.
- [ ] In theory (**still to confirm**), running this 8 times will create 8 requests, and then in the dashboard create a batch of the 8 requests from the dashboard, that should prepare the flowcell?
- [ ] Complete the batch. Check that the data goes into the warehouse (iseq_flowcell table using the batch id)
- [ ] Check with NPG that they can see the data there?

**Comment by emrojo** [comment]
Some code from a similar task in the past, quit old though. Maybe as a reference but I would expect this is done quite differently now:

https://github.com/sanger/sequencescape/pull/872/files
