### ISSUE TITLE
DPL-752 Upgrade Ubuntu server versions on production FCE from v18.04 to 20.nn

### ISSUE THREAD

**Issue by Sangeetha-Bheeman** [sanger/General-Backlog-Items#292]
**Housekeeping**
 To upgrade Ubuntu to 20.nn in all production FCE.  The End of Life for v18.04 is 30th April 2023

The primary requirement is captured as part of the sanger/cherrytrack#36 ticket which can be converted and split into smaller user-stories.

**Who are the primary contacts for this story**
e.g. Sangeetha, Eduardo (don't include surnames in public repos)

**Who is the nominated tester for UAT**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:

Upgrade the production servers to 20.nn 

- [ ] Sequencescape
- [ ] Limber
- [ ] Lighthouse, Crawler, Lighthouse-ui, Baracoda
- [ ] Traction
- [ ] Gatekeeper
- [ ] Assest audits
- [ ] Unified_warehouse
- [ ] Print_my_barcode
- [ ] Labwhere
- [ ] sm_workflow_lims

Plan the downtime in advance
Plan for the upgrade process like creating snapshot before upgrade and rollback plan if the upgrade fails.
 

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Comment by Sangeetha-Bheeman** [comment]
`<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2113.6">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'}
table.t1 {border-collapse: collapse}
td.td1 {border-style: solid; border-width: 1.0px 1.0px 1.0px 1.0px; border-color: #9a9a9a #9a9a9a #9a9a9a #9a9a9a; padding: 1.0px 5.0px 1.0px 5.0px}
</style>
</head>
<body>


Applications | Upgrade date | Upgrade time
-- | -- | --
Gatekeeper | 02-05-2023 | 6 pm to 7 pm
Assest audits | 03-05-2023 | 6 pm to 7 pm
sm_workflow_lims | 04-05-2023 | 6 pm to 7 pm
Labwhere | 05-05-2023 | 6 pm to 7 pm
Print_my_barcode | 09-05-2023 | 6 pm to 7 pm


</body>
</html>
`

**Comment by TWJW-SANGER** [comment]
Following our meeting on 9/5 we agreed to deprecate this story in favour of individual one for each production service
