### ISSUE TITLE
DPL-769 Create new Openstack env for UAT2 (S=L; C=M)

### ISSUE THREAD

**Issue by emrojo** [sanger/General-Backlog-Items#294]
**User story**
As PSD developer I would like to have a new Openstack separate environment uat2 so we can have 2 different environments (uat and uat2) to deploy different versions of the applications we maintain.

**Who are the primary contacts for this story**
Eduardo M

**Who is the nominated tester for UAT**
Eduardo M

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] All servers and application in current uat will have an equivalent uat2 machine
- [ ] Warehouse uat2 will have its own database so we can test uat2 messaging
- [ ] All servers will have a uat2 CNAME in the dns
- [ ] Everything can be created with terraform scripts
- [ ] Process is documented

**Dependencies**
This story is blocked by the following dependencies:
- It may require support from systems to increase the threshold of resource we can make use for

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by TWJW-SANGER** [comment]
#336 achieves the same aim of unblocking UAT and is currently higher in priority.
If #336 is completed we should review if we still wish to complete this story.
