### ISSUE TITLE
DPL-774 As a Team Lead (Tom) I would like to update our documentation and end users about the current_labware_location so that they can write more efficient queries.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#296]
**Describe the Housekeeping**
As a Team Lead (Tom) I would like to update our documentation and end users about the current_labware_location so that they can write more efficient queries.

**Acceptance Criteria**
- [x] Update Confluence pages on MLWH such as "How to Get The Current Location Of Labware from MLWH_Events"
- [x] Update any queries on Confluence using MLWH_Events and 'location_info' to get current location of labware
- [x] Send email to MLWH user group at mlwh-notices "at" sanger.ac.uk 
- [x] Notify Matt F updating his LabWhere tableau reports.

**Blocking issues**
#295 

**Additional context**
Email to mlwh-notices should contain:
* Notification of the new table in MLWH. 
* Brief description of it's purpose - that is a) simplifying how to find the current location of plates/tubes/labware from MLWH, b) enabling current location to be linked with samples efficiently in MLWH, c) enabling combining locations stored in different systems in one place
* Links to update documentation on how to use in queries.

Email to Matt F. The same and ask for any feedback on updating his Tableau reports.

**Comment by javidahmed64592** [comment]
Progress: I have added a new page called [How to Get the Current Location of Labware from MLWarehouse](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/How+to+Get+the+Current+Location+of+Labware+from+MLWarehouse).

Can we now simply archive [How to Get The Current Location Of Labware from MLWH_Events](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/How+to+Get+The+Current+Location+Of+Labware+from+MLWH_Events)?

**Comment by javidahmed64592** [comment]
Progress: I have updated [Useful queries for the multi-LIMS warehouse](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Useful+queries+for+the+multi-LIMS+warehouse) to include query for getting labware location.

**Comment by javidahmed64592** [comment]
Progress: I have updated [Warehouse queries for sample tracking](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Warehouse+queries+for+sample+tracking) to include labware_location table

**Comment by TWJW-SANGER** [comment]
Looks good.
I have:
Added an example query to find all labware under a fully qualified address to Confluence.
Added a noted to the page getting current locations from the Events DB to prefer to use this new solution.
