### ISSUE TITLE
DPL-778 As a team we would like to create a set of guidelines for updating dependencies so that we have a consistent process.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#299]
**Description**
As a team we would like to create a set of guidelines for updating dependencies so that we have a consistent process.

**Who the primary contacts are for this work**
TW SI

**Knowledge or Stake holders**
PSD Team 

**Additional context or information**
A placeholder page is on the PSD Public Confluence wiki under Public Processes.
We should research what and how other teams manage their processes.

**Comment by harrietc52** [comment]
[Dependency research doc](https://docs.google.com/document/d/1c4w27uN9ELCqmuSF7YWCGipzBW5OoRa2HBVEIz-i0iA/edit?usp=sharing)

**Comment by BenTopping** [comment]
### Output stories for dependency process improvements
**Preface:** We need to schedule and prioritise work to upgrade all applications to the latest major framework and language versions to ensure consistency across applications. This does not block the below stories but it would improve the quality of the dependency upgrade process.

1. Deprecate dependency tracking google sheet. Setup recurring stories to upgrade application groups every 3 months.
- Identify how to setup recurring stories
### Application groups:
**Rails - 1**
Sequencescape
Limber
Traction service
Print my barcode
Labwhere

**Rails - 2**
Samples extraction
Asset audits
Gatekeeper
Event Warehouse
Unified Warehouse
SM Workflow Lims

**Python**
Lighthouse
Crawler
Baracoda
Cherrytrack
Wrangler
Janitor

**Javascript**
Lighthouse-ui-v3
Traction-ui
Quanthub

**Deployment (subject to deployment strategy)**
Deployment
Config
Provision

2. Reconfigure depfu and dependabot to create individual PRs for security dependencies and grouped ones for all other dependencies. 
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
- https://docs.depfu.com/article/16-choose-your-update-strategy

3. Setup a notification system for security dependencies (This is to ensure they are merged and deployed all the way to production, even on less-active repos). It would be good to identify if we still need to alert stakeholders for deployments as this would make this task more tedious.

**Comment by BenTopping** [comment]
### Dependency guidelines

1. Automerge security requests and patch updates (in semver major.minor.patch) if they are passing CI builds.
2. Review minor / major updates (in semver major.minor.patch) for breaking changes, deprecation warnings, and new features. Pull down the changes and manually check for issues locally, even if passing CI. 
3. Wait 1-2 weeks before merging in a new dependency update. This prevents having to re-merge a dependency multiple times for any hotfixes or additional patches they put out in that time.
4. Split out major breaking changes if they require their own story. E.g Major framework updates like Rails, Vue, Flask.
5. Deploy dependencies all the way to production. Check for existing work in progress to ensure you don’t disrupt or break in-progress work. This is to ensure that apps are regularly updated with security updates.

**Comment by KatyTaylor** [comment]
Guidance looks clear, thanks @BenTopping. Happy to give this system a try - maybe we can review after 6 months or so to see how it's working.

**Comment by BenTopping** [comment]
Closing in favour of the following outcome stories:

https://github.com/sanger/General-Backlog-Items/issues/328
https://github.com/sanger/General-Backlog-Items/issues/329
https://github.com/sanger/General-Backlog-Items/issues/330
