### ISSUE TITLE
DPL-779 As a Team Lead (Tom) I would like to generate high level architectural diagram & data flow diagram of the RVI flexible cherry picking system so that we are clear on the components and responsibilities. 

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#300]
**Description**
As a Team Lead (Tom) I would like to generate high level architectural diagram & data flow diagram of the RVI flexible cherry picking system so that we are clear on the components and responsibilities. 

**Who the primary contacts are for this work**
TW AS EMR ST

**Additional context or information**
The architectural diagram should consist of the components of the system and their connections/interfaces. It should include at a minimum:

- PlateGenie
- CherryTrack
- Biosero software
- SequenceScape
- MLWH Events Database

The data flow diagram should show the flow of data for Use Case 1 in the URS through the different components.

**Possible unanswered questions blocking the creation of these diagrams**
- Which system do we anticipate will be used to choose samples to cherrypick?  Do we have something pre-existing that we can either use or adapt?
- Do we expect the user to be able to use a GUI to choose samples for cherrypicking, or will they be defined in something like a CSV file?
- How will this picking process be materially different to the Heron process for cherrypicking, other than the more manual selection of samples to transfer?  i.e. will all records of the picking process be made into similar databases and systems?
- The URS describes Case 1 as having input stacks and output stacks.  Is that how it will actually work?  I thought we were using a more manual process?
- It says that the destination plate will have the "specified plate purpose".  Is that something that is defined by the run operator or a fixed purpose for all cherrypicking runs?
- We need to decide how to support the use of destination plates during cherrypicking as source plates in the same process.  This needs to also be the starting plate for a sequencing run.  We don't know what Limber can support.  Some discussion was had to suggest we have two possible cherrypicking pipelines.  One that goes from the shallow well plates used in stamping to a destination plate type.  And another that goes from that destination plate type to further destination plate types.

**Comment by sdjmchattie** [comment]
I've documented this in the document: https://lucid.app/lucidchart/b59fb5d6-a7e5-4121-a451-cc5d8fcb3dc6
