### ISSUE TITLE
DPL-845 - As long read samples extraction (Hermione) I would like to be able to receive tubes with 2D barcodes so we no longer need to reprint barcodes

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#316]
**Description**
As long read samples extraction (Hermione) I would like to be able to receive tubes with 2D barcodes so we no longer need to reprint barcodes.

Currently tubes are received with 1D barcodes. When these are imported into traction they are ean13 barcodes which are not readable or usable. As a hack the long read samples extraction team run them through the samples extraction service just to print a new human readable barcode.

If they were able to receive them with 2D barcodes then they would be able to miss out this step and would no longer need to use samples extraction. This would save time and effort and also mean we could remove the dependency between samples extraction and traction and so reduce technical debt.

Expected outcomes of this research:

- identify where in the process the barcodes are printed off and where from e.g. Sequencescape or Limber and which pipeline they are attached to if any
- identify whether the 2D tube template created for Bioscan is suitable for long read
- an implementation story to add the functionality to Sequencescape / Limber
- identify acceptance criteria for long read

**Who the primary contacts are for this work**
Steve / hermione

**Knowledge or Stake holders**
Abdullah (PSD) who created the functionality in Sequencescape to print 2D barcodes for Bioscan.

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by SujitDey2022** [comment]
Discussed with @TWJW-SANGER that this story needs to be looked at with the other Barcode user stories in the backlog and decide on an approach to prioritize. For this reason, this has been moved back to the backlog from Triage.

**Comment by stevieing** [comment]
> Discussed with @TWJW-SANGER that this story needs to be looked at with the other Barcode user stories in the backlog and decide on an approach to prioritize. For this reason, this has been moved back to the backlog from Triage.

Raised this in backlog prioritisation this morning. @SujitDey2022 I think it would be worth prioritising. Currently the Long Read samples extraction team are having to use samples extraction LIMS solely for reprinting barcodes. It adds technical debt as well as extra work for them. The work that Abdullah did could support this. It would also remove a dependency and move us towards shutting samples extraction. I would also be concerned if we bundle it in with a larger printing project how long it would take.
