### ISSUE TITLE
DPL-847 As a TL (Tom) I would like to investigate how message schema can be shared and used between applications on AWS and application onsite in OpenStack.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#317]
**Description**
As a TL (Tom) I would like to investigate how message schema can be shared and used between applications on AWS and application onsite in OpenStack.

**Who the primary contacts are for this work**
TW, HC, SM, EMR

**Knowledge or Stake holders**
SM, EMR

**Additional context or information**
The RabbitMQ message queues supported by PSD use RedPanda to define and enforce versioned message schemas for communication. This works by running a RedPanda schema registry instance on OpenStack as a service.

When using a message bus spanning AWS cloud applications and private cloud applications running on OpenStack, what are the options for sharing and enforcing message schemas?

For example, the simplest option is not to enforce message schemas at all in the first instance, this is v. easy to implement but I suspect harder to maintain..
A more functional alternative option might be using a VPN between AWS and OpenStack so that a RedPanda server can be reached from either end - however this has impacts on uptime within each cloud should the VPN connection be broken.

Anticipated activities in this work are:
* Researching the various technologies and tools available
* Researching any existing solutions to similar problems.
* Writing up different possible approaches and trade-offs.
* Time boxed to 2 to 3 days.

Outputs for this story should be:
* Outlines of at least 2 different architectural options to enable shared message schemas across clouds with trade-offs between maintenance, uptime, performance etc...
* A recommendation for a given option to be used.

**Comment by stevieing** [comment]
Closed as being done.
