### ISSUE TITLE
DPL-852 As a team we would like to document how label printing works now so that we have a clear understanding of the current system.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#318]
**Description**
As a team we would like to document how label printing works now so that we have a clear understanding of the current system.

**Who the primary contacts are for this work**
PSD

**Knowledge or Stake holders**
PSD, especially SI, DR, NS.

**Additional context or information**
Output documentation should include:

- Application communication diagram (what's talking to what) [here](https://lucid.app/lucidchart/9db06e4e-6181-4e00-b4d7-4aafb4bc658a/edit?viewport_loc=-2987%2C-2881%2C7404%2C3583%2C0_0&invitationId=inv_5ff20630-d5d2-4583-92f7-bc941fbc5baa)
- Places where label templates are stored [here](https://docs.google.com/spreadsheets/d/1uUNU0m8UOKjsZ6aKSJgaj6ofS2EH6VS6eqO1__HKNFw/edit?usp=sharing)
- List of frequently occurring problems [here](https://docs.google.com/document/d/1duGjCmlbEXNoK5jidpPixsd2hUVlmi9ErSzfRmZqGsU/edit#heading=h.y1to20d6gim9)
- Edge cases and how/if they are handled, e.g. alignment differences between printers.
- Constraints, e.g. robotic platforms that have only 1D label scanners.
- For each of our apps: [here](https://docs.google.com/spreadsheets/d/1uUNU0m8UOKjsZ6aKSJgaj6ofS2EH6VS6eqO1__HKNFw/edit?usp=sharing)
  - Which print service it uses (PMB v1, PMB v2, SPrint) 
  - How the templates are stored (which host, how deployed, what file format)
  - List of template names used by it
  - Any quirks

**Comment by harrietc52** [comment]
## Output

Overview of "Understanding Label Printing" Google Doc [here](https://docs.google.com/document/d/1duGjCmlbEXNoK5jidpPixsd2hUVlmi9ErSzfRmZqGsU/edit?usp=sharing)

More specific implementation details, per application, in Google Sheet [here](https://docs.google.com/spreadsheets/d/1uUNU0m8UOKjsZ6aKSJgaj6ofS2EH6VS6eqO1__HKNFw/edit?usp=sharing)

Current Architecture of our Printing, in Lucid Chart [here](https://lucid.app/lucidchart/9db06e4e-6181-4e00-b4d7-4aafb4bc658a/edit?viewport_loc=-2987%2C-2881%2C7404%2C3583%2C0_0&invitationId=inv_5ff20630-d5d2-4583-92f7-bc941fbc5baa)

**Comment by harrietc52** [comment]
**Todo** 

How to create and test new labels
List of template names used per app (hard!)
More Edge cases and how/if they are handled
Add link ref to Google sheet

**Comment by yoldas** [comment]
Added missing screenshot images of Windows in UTM and Cablabel S3 Lite to Designing Sprint Templates section of Understanding Label Printing document on Confluence.

**Comment by yoldas** [comment]
### Continue adding detail for each possible story (i.e. each Application)

WIP

**Comment by yoldas** [comment]
### Add where printers are stored per app

Added where printer names come from for each app [here](https://docs.google.com/spreadsheets/d/1uUNU0m8UOKjsZ6aKSJgaj6ofS2EH6VS6eqO1__HKNFw/edit?usp=sharing)

**Comment by yoldas** [comment]
### Add a list of label template names used

See  [here](https://docs.google.com/spreadsheets/d/1uUNU0m8UOKjsZ6aKSJgaj6ofS2EH6VS6eqO1__HKNFw/edit?usp=sharing) for how/where templates names are set for specific apps.

NB. PMB V1 uses template ids from databases. Some applications embed templates in their code.

**Comment by yoldas** [comment]
### New labels

There is enough information in the documents about creating and testing SPrint templates for Squix printing. However, we do not have enough info about creating PMB templates from scratch for Toshiba printing. Our usual practice so far is that we copied existing templates in the PMB database and modified them to make new templates.
