### ISSUE TITLE
DPL-862 As a team we would like to setup a recurring story process for managing dependencies

### ISSUE THREAD

**Issue by BenTopping** [sanger/General-Backlog-Items#328]
**Describe the Housekeeping**
As a team we would like to setup a recurring story process for managing dependencies. This will allow us to make the dependency work visible to the team. The dependency stories will cover **groups of dependencies** and should r**e-occur every 3 months**

**Acceptance criteria**

- [ ] Identify how to setup recurring stories
- [ ] Identify the most sensible application grouping. Proposed application groups:

**Rails - 1**
Sequencescape
Limber
Traction service
Print my barcode
Labwhere

**Rails - 2**
Samples extraction
Asset audits
Gatekeeper
Event Warehouse
Unified Warehouse
SM Workflow Lims

**Python**
Lighthouse
Crawler
Baracoda
Cherrytrack
Wrangler
Janitor

**Javascript**
Lighthouse-ui-v3
Traction-ui
Quanthub

**Deployment (subject to deployment strategy)**
Deployment
Config
Provision

**Additional context**
This work came out of the [Dependency research doc](https://docs.google.com/document/d/1c4w27uN9ELCqmuSF7YWCGipzBW5OoRa2HBVEIz-i0iA/edit?usp=sharing)

**Comment by stevieing** [comment]
This is superceded by the technical debt board.
