### ISSUE TITLE
DPL-863 As a team we would like to reconfigure depfu and dependabot

### ISSUE THREAD

**Issue by BenTopping** [sanger/General-Backlog-Items#329]
**Describe the Housekeeping**
Reconfigure depfu and dependabot for all repositories to create individual PRs for security dependencies and grouped ones for all other dependencies. We should review the use of dependabot and depfu for each repository to check if they are both needed.

**Acceptance criteria**
- [ ] All repositories group non-security dependencies into a single PR
- [ ] Depfu / Dependabot are configured to create individual pull requests for security issues

**Additional context**
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
https://docs.depfu.com/article/16-choose-your-update-strategy

This work came out of the [Dependency research doc](https://docs.google.com/document/d/1c4w27uN9ELCqmuSF7YWCGipzBW5OoRa2HBVEIz-i0iA/edit?usp=sharing)

**Comment by stevieing** [comment]
closed as done. I think we reviewed all of them and seemed to have reached a consensus.
