### ISSUE TITLE
DPL-864 As a team we would like to setup a notification system for security dependencies

### ISSUE THREAD

**Issue by BenTopping** [sanger/General-Backlog-Items#330]
**Describe the Housekeeping**
Setup a notification system for security dependencies (This is to ensure they are merged and deployed all the way to production, even on less-active repos). It would be good to identify if we still need to alert stakeholders for deployments as this would make this task more tedious. Or Can we automerge security dependencies using something like renovate or a depfu setting.

**Acceptance criteria**
- [ ] Slack channel with notfications for new security issues in our repositories
- [ ] Review setting up auto-merge for security dependencies

**Additional context**
This work came out of the [Dependency research doc](https://docs.google.com/document/d/1c4w27uN9ELCqmuSF7YWCGipzBW5OoRa2HBVEIz-i0iA/edit?usp=sharing)

**Comment by stevieing** [comment]
This is superceded by the technical debt board.
