### ISSUE TITLE
DPL-868	RVI Tecan cherrypicking volume tracking

### ISSUE THREAD

**Issue by neilsycamore** [sanger/General-Backlog-Items#333]
User Story
As the Automation lead for RVI cherry-picking (Scott T) I need to establish if we have a current mechanism that supports tracking sample volumes in order to see if it can be repurposed for RVI cherry-picking on the Tecan instruments.

Who are the primary contacts for this story
Scott T (R&D)
Rich C (SSR)
Tobi A (R&D)

Who is the nominated tester for UAT
Rich C
Scott T

Acceptance criteria
To be considered successful the solution must: 

- Identify if there are volumes stored for current stock and cherrypick plates

If volumes are tracked for both set of plates then:
- Identify where this information is stored
- Identify how this information is initially populated e.g. via sample manifest upload, volume checker QC etc.
- Identify how these values are updated (are specified cherrypick volumes subtracted from the initial/latest volume)
- Identify if there is a mechanism to prevent negative volumes being selected in the cherrypick. Are negative volumes prevented from being subtracted from the cherrypick source?
- Identify how the volume extracted from a source is defined (manually?) or is it assumed the entire volume is taken
- Identify if the volume remaining value is (or can be) used in the initial selection of samples. There is no point selecting a sample to be cherrypicked if there is not enough volume remaining for the cherrypick or downstream process.
- Identify if subsequent aliquot steps update (or could update) the volume remaining value
- Capture the volume tracking information in a document to to be used as a source of knowledge in the future.

Time box to 3 days.

Related stories
DPL-821 [RVI] Cherry-picking LSW-96 Stock plates using the existing Tecan systems

Background
The Respiratory Virus and Microbiome Initiative (RVI) project is looking to utilise the equipment and systems set up for COVID sequencing to sequence respiratory viruses more broadly. 
We plan to use the Biosero cherry-picking systems in the GSLP labs long term, but it has become clear that we will need to make significant changes to the robot program and LIMS logic to accommodate the flexible cherry-picking approach that RVI requires. 
The final scope, as currently understood, will require significant work from PSD and Biosero, which is likely to take months to implement. 

We have discussed using the Tecan instruments as an interim solution on the RVI project calls. If we can use the existing cherry-picking process (possibly with minor alterations) then we could start cherry-picking at a much earlier stage while we are still working on the Biosero implementation. 

There are many unknowns around this proposed approach. Most of the relevant information has been gathered in DPL-821, but there are still several unknowns surrounding sample volumes which are significant enough to warrant a separate story.

Details
Cherrypick source plates will be in PerkinElmer shallow-well 96-well plates or Biorad hardshell shallow-well 96-well plates (physically identical and interchangeable labware)
Cherrypick source plates will have ‘LSW-96 stock’ or an as yet undefined RVI cherrypick plate purpose
Cherrypick destination plates will have an as yet undefined RVI cherrypick plate purpose
Plates will be cherrypicked by volume, with no normalisation step.
The preferred option for GSU is that all the remaining volume is transferred from the source plate to the destination plate
‘LSW-96 stock’ Source plates will have a starting volume of 35µl
RVI cherrypick source plates are expected to have a lower volume (reduced by stamp/aliquots taken for downstream processes e.g. 10µl taken for Bait Capture Library Prep).  
The samples to be cherry-picked would be selected by GSU or use GSU-defined selection criteria
This could include both COVID ‘positive’ (fit to pick) and Covid ‘negative’ samples.
Positive and negative controls may be added to the plate
This is likely to use new control plate.

**Comment by TWJW-SANGER** [comment]
After discussion around the RVI process for this winter, the RVI/OPs team decided the best approach was to use visual checks on available plate volumes. 
So this story is no longer required for the near term.
