### ISSUE TITLE
DPL-874 As an R&D scientist (Di R) I would like to establish the feasibility of utilising elements of the RNA PolyA (RNAA) library prep followed by elements of the LCMB pipeline and ISC (Twist pulldown) in order to create a new LIMS pipeline for an in-house Bait Capture library preparation pipeline for RVI [Completion date 09/1023]

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#334]
**To be completed WB 02/10/23
Estimated completion date 09/10/23**

**Description**
As an R&D scientist (Di R) I would like to establish the feasibility of utilising elements of the RNA PolyA (RNAA) library prep followed by elements of the LCMB pipeline and ISC (Twist pulldown) in order to create a new LIMS pipeline for an in-house Bait Capture library preparation pipeline for RVI.

**Who the primary contacts are for this work**
Di R

**Knowledge or Stake holders**
PSD

**Acceptance Criteria**

In order to be successful, this research story should:

- [x] Identify any current blockers or new requirements for repurposing the RNA and Twist pulldown pipelines. E.g.
plate purposes, plate states, plate manifests, library types, request types.
- [x] Decide if repurposing existing pipelines, "starting from scratch" or a different approach to delivery is most optimal in terms of efforts & complex.
- [x] If possible create a backlog of user stories for further refinement to deliver the in-house Bait Capture library preparation pipeline.
- [x] Using the backlog and available resource estimates, establish an estimated delivery timeline for the RVI Bait Capture  pipeline

**Additional context or information**

- sanger/limber#1406
- sanger/limber#1407

Several different bait capture approaches are being evaluated for RVI library preparation, these include commercial offerings which would require new automation to be written, and an ‘in-house’ method which re-purposes existing automation programs.

The in-house method would have a shorter R&D and automation development cycle, this research story has been requested to establish if LIMS development would be aided or hindered by utilising parts of existing workflows.

*The as yet undetermined RVI Cherrypick plate purpose may require additional states to be added to the state machine

Potential list of plate purposes:

**RVI Cherrypick***
_LB cDNA XP_
LCMB End Prep
LCMB Lib PCR
LCMB Lib PCR-XP
**_LB Lib PrePool
LB Hyb
LB Cap Lib
LB Cap Lib PCR
LB Cap Lib PCR-XP
LB Cap Lib Pool
Lb Lip Pool Norm_**

 

Key:
**RVI (TBD)**
_RNA A_
LCMB
**_ISC_**

Additional materials

Process overview in [Lucidchart](https://lucid.app/lucidchart/28732575-1548-4e09-a3cb-21af2205d7ca/edit?referringApp=google+drive&beaconFlowId=9b28e294a7011077&invitationId=inv_2406ae5a-1d1c-4ff9-bbd5-b40ae031c555&page=jEPPbYI4Rllu), see tab ‘In-house’

Original RT Number: 785811

**Comment by KatyTaylor** [comment]
N.B. From Scott:
The new "in-house" RVI pipeline should maintain the functionality from LCMB ISC, where WGS library prep can be performed after the sequencing results of ISC libraries been analysed.

See RT 786021

**Comment by stevieing** [comment]
Bait Capture pipeline:

https://lucid.app/lucidchart/c1a5c6a6-f4d4-4cfe-b216-e5a8e9dc34ce/edit?viewport_loc=-1562%2C-1035%2C2367%2C1395%2C0_0&invitationId=inv_14681694-a000-47a8-bca7-104cf2537d80

**Comment by stevieing** [comment]
Notes from meeting on 13/10:

- We will create a new library type RVI-BCL
- It would make sense to version the pipeline and the library type as we might also need to create a v2
- Question: Do we need a step for creating a tag plate?
- Question: Do we go from RVI End Prep plate to Lib PCR or go from end prep to lig bind and then lig bind to lib PCR can’t easily scan the barcode for the end prep plate? Also the samples haven’t been in that plate for some time. Answer: Based on that this is what happens in the real world it makes sense to capture those steps.
- Scott: It makes sense to put boxes behind to show the stages for clarity
- Question: currently you do WGS then ISC for LCMB. In this case you want to do ISC then WGS later on the LIB-PCR XP plate. As we want to push the LIB-PCR XP plate through WGS is there anything we need to do in the LIMS i.e. create a new submission?
- Question: We need to be able to flag which plates we want to be able to fail wells on? This functionality on specific plate purposes. Plate purposes where we are doing a QC step need to be able to be failed. These are distinguished by one of the 4 wells is marked with an x.
