### ISSUE TITLE
DPL-886 As a team (PSD) we want to connect the Training environment to a warehouse database so that we can use Training for testing when the UAT environment is blocked.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#336]
**User story**
As a team (PSD) we wan to connect the Training environment to a warehouse database so that we can use Training for testing when the UAT environment is blocked.

**Who are the primary contacts for this story**
PSD

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] New MySQL 8 MLWH and MLWH Events database for the training environment.
- [ ] The databases to be seeded with data consistent with the other applications in the Training environment.
- [ ] The new databases (mlwarehouse, mlwh_events, mlwh_reporting) should be sync'ed with production once a week to maintain consistency with the SequenceScape database.
- [ ] Any processes/documents for updating data within the Training environment to be updated to include the new databases.
- [ ] Applications in the Training environment to connect and transmit data to the new databases.
- [ ] Passwords and server details stored in KeePass.
- [ ] Deployment project updated where required.

**Comment by TWJW-SANGER** [comment]
Appears to be duplicate of #127

**Comment by KatyTaylor** [comment]
I've put this as large as it requires:
- back and forth with the DBAs
- updates to multiple apps, which connect to the warehouses in various ways

I've got a few questions:

> The databases to be seeded with data consistent with the other applications in the Training environment.'

Not sure what this means exactly. The Sequencescape training db is refreshed from prod each week - is this saying that these 2 new dbs should do the same? The current situation is that the SS training app is connected to the `..._proddata` warehouse dbs, which are refreshed from prod each week - this is very useful for debugging RTs so I think we need to keep something similar to this. Can we just link up the existing `..._proddata` warehouse dbs?

> Any processes/documents for updating data within the Training environment to be updated to include the new databases.

Not aware of any processes around this - if there are some, could the relevant docs be linked?

**Comment by dasunpubudumal** [comment]
`unified_warehouse` has a queue associated with it that pushes records to MLWH. This is, in UAT, accessed via http://ware-uat.psd.sanger.ac.uk:15672/#/ (by default it forwards to the management console). `warren` shovels the messages in this queue to MLWH.

If we are setting up a separate MLWH, we might need to set this queue up in a VM and create a DNS record to access (e.g., http://ware-training.psd.sanger.ac.uk:15672/#/) as well.

**Comment by dasunpubudumal** [comment]
Set of tasks [DRAFT]

- [ ] Set up the VM `ware-prod.psd.sanger.ac.uk`.
- [ ] Add configuration into `environments/training/hosts` in `deployment` project.
- [ ] Set up RabbitMQ and point DNS for the management console to: http://ware-training.psd.sanger.ac.uk:15672/#/
- [ ] Set up, configure and deploy `unified_warehouse` in `ware-prod.psd.sanger.ac.uk` VM.

**Comment by stevieing** [comment]
Closed in favour of [#465](https://github.com/sanger/General-Backlog-Items/issues/465)
