### ISSUE TITLE
GPL-598 Count of LH +ve samples not WIP or sequenced 

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#36]
**User story**
GPL-598 | As Senior manager PAM (John S) I would like to know for a given week the count of +ve samples not WIP or sequenced from the Lighthouse labs (Whats left behind we could go back too?)

**Who are the primary contacts for this story**
John S (PAM)
Cristina A (PAM)
Neil S
Rich L

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Weeks start on the Monday
- [ ] Number the weeks - is decreed that week starting 20th July is week 0
- [ ] Only interested in coun tof +ve samples / site
- [ ] Use the 'date tested' from LH SFTP data in crawler as the week the sample is from 
- [ ] Suggested that not sequenced vs WIP+Sequence is presence of COG-UK id in LIMS
- [ ] Need to understand how given thisdata operations would find the '3 positives from week commencing the 13th April we did not do' 

**Additional context**
This report is in a similar vein (presented every Monday since 20th July): https://ssg-confluence.internal.sanger.ac.uk/x/DQKRBg 
Raised as requirement in the Monday meeting on the 3rd August.

**Comment by stevieing** [comment]
Steve / Andrew / Katy had a discussion about this on 20/08.
Katy to email PAM and ask them if they can use the current lighthouse reports as an interim solution.
To do this properly we would need to either use events or add columns to the mongo db.

**Comment by KatyTaylor** [comment]
Have emailed Cristina to discuss possibility of using the current lighthouse reports

**Comment by KatyTaylor** [comment]
Reply from Sonia:

> Yes, we are aware of the 'Lighthouse positive samples reports' and we do use it. 
I believe the user story you mention is only part of what we need...

> Katy, to give you an idea on the current requirements for reporting, I've attached a draft table with the main fields we would need data for, important considerations:
> - we need to be able to distinguish between the virtual cherry picking (submission) and the physical cherry picking
> - breakdown by LH lab and week
> - data for each step in the process

> Totally understand some of this may not be straight forward, very happy to have a call to discuss.

Table referred to had the following format:

Date | Week | No. +ve   Plates | Plate Occupancy | No. Positive   Samples | Cherry-picked | Virtual   cherry-picked (submission) | Physical cherry   picked | Started Lib prep | Sequencing | QC failed | QC passed | Uploaded to   CLIMB | Uploaded to   CLIMB (with metadata) | % | Remaining
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
27/07/2020 | 1 |   |   |   |   |   |   |   |   |   |   |   |   |  
20/07/2020 | 0 |   |   |   |   |   |   |   |   |   |   |   |   |  
13/07/2020 | -1 |   |   |   |   |   |   |   |   |   |   |   |   |  
06/07/2020 | -2 |   |   |   |   |   |   |   |   |   |   |   |   |  
29/06/2020 | -3 |   |   |   |   |   |   |   |   |   |   |   |   |  
22/06/2020 | -4 |   |   |   |   |   |   |   |   |   |   |   |   |  
15/06/2020 | -5 |   |   |   |   |   |   |  |   |   |   |   |   |  
08/06/2020 | -6  |   |   |   |   |   |   |   |   |   |   |   |   |  
 01/06/2020 | -7 |   |   |   |   |   |   |   |   |   |   |   |   |

**Comment by KatyTaylor** [comment]
Based on the acceptance criteria, I think this story will be unnecessary after doing [GPL-579](https://github.com/sanger/unified_warehouse/issues/118) and [GPL-578](https://github.com/sanger/labwhere/issues/181)

GPL-579 will add the Lighthouse plate map data into the MLWH - you can then query this to find out whether samples have a COGUK id or not (as well as the result and date tested).
GPL-578 adds LabWhere information into the Events WH - you can query this to find out which samples are on site.

Looking at the table sent by Sonia above, though, that covers a few different stories and not sure if we've got it all covered or not atm.

**Comment by stevieing** [comment]
Better to wait until GPL-579 is completed before completing this story.
Neil will write some SQL which will be code reviewed and then we could try and get it on to Global Reporting?
