### ISSUE TITLE
DPL-1046 Edit existing Confluence articles

### ISSUE THREAD

**Issue by StephenHulme** [sanger/General-Backlog-Items#360]
**Describe the Housekeeping**
Edit existing Confluence articles to improve purpose and readbility as described in #352 

> - [Feedback Wall](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Feedback+Wall?src=contextnavpagetreemode), with complements and insights from our Users and Customers
>   - ✏️ order of items should be flipped so that the mot recent is at the top

> - [Products](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Products?src=contextnavpagetreemode) - High-level details of PSD products (applications, databases, etc.)
>   - Individual Product and Application pages (Sequencescape, STAN, LabWhere, MLWH, etc.)
>   - ✏️ hard to read due to table column spacing

**Blocking issues**
None

**Additional context**
None

**Comment by dasunpubudumal** [comment]
Tasks:

- [ ] Order of items should be flipped so that the mot recent is at the top
- [ ] Adjust table column spacing

**Comment by dasunpubudumal** [comment]
Note: The products table in [Products](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Products?src=contextnavpagetreemode) is a responsive table (i.e., it "wraps" the content based on the reader's screen resolution). Thus, it might be better to zoom the page out if the words in the sentences are breaking into multiple lines.

**Comment by stevieing** [comment]
All looks fine to me. We can move this to done.
