### ISSUE TITLE
DPL-1048 Add missing information to Confluence

### ISSUE THREAD

**Issue by StephenHulme** [sanger/General-Backlog-Items#361]
**Describe the Housekeeping**
Add missing information to Confluence as described in #352 

Add summary of where to find and place information on a main/home/entry page in Confluence

> Documentation Suggestions:
>
> - Confluence (Public)
>   - Focussed on publically available code-bases, operations procedures, design documents, user documentation, Lucid charts
>   - A How-To article, ideally provide a link to it from the appropiate pipeline or product page in the folder structure
>   - See Recommended Folder Structure above for more details
> - Confluence (Private)
>   - Focussed on team and organisation
> - Repository `docs` Folder
>   - Used on a per-repository basis
>   - Could be considered for migration to Confluence
>     - Such as documents on PSD design principles such as in Sequencescape
>   - Recommended for specific use cases only
>     - Such as developer design docs in Limber for adding new Purposes and Pipelines
> - Repository Readme
>   - Code related
>   - Setup, installation, and troubleshooting
>   - How to contribute to this repo
>     - Linting
>     - Style-guides
>     - Testing
>   - Commonly used commands
>   - Developer hints and tips
>   - Developer workarounds
>   - Miscellaneous developer notes
> - Subfolder Readme
>   - Implementation details
>   - Gotchas
>   - Code related
> - Pull Requests
>   - Descriptions of changes made 

> - [Services](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Services) - A list and links to active PSD services
>   - ➕ would be helpful to include links to each product in the Products page

> - [Projects & Pipelines](https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=101357241&src=contextnavpagetreemode)
>     - Details on individual pipeline planning, design, usage, and support. Independent of PSD application.
>     - ➕ would be helpful to add dummy pages or move older pipelines pages to here to make it clear that this is the de facto pipeline page

> - [Traction](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Traction?src=contextnavpagetreemode)
>   -  ➕ add Traction outlines, diagrams, and related documentation

**Blocking issues**
None

**Additional context**
None

**Comment by yoldas** [comment]
I have two more suggestions:
- Adding Tags (Confluence Labels) so the search filter can be applied. 
- More descriptive titles to articles so the search can show the most relevant results on top.
