### ISSUE TITLE
DPL-1062 New STS barcode template 15x40

### ISSUE THREAD

**Issue by neilsycamore** [sanger/General-Backlog-Items#363]
As CASM Senior Scientific Manager (Rob T) we would like a template that can print barcodes of dimension 15mm (h) x 40mm (w) and should feature a 2D barcode. We will be printing this from the STS, via printmybarcode.

Who are the primary contacts for this story
rt14
Image and label spec. attached and detailed in [RT795163](https://rt.sanger.ac.uk/Ticket/Display.html?id=795163)
![RT795163_new_template](https://github.com/sanger/General-Backlog-Items/assets/299768/35d27180-a498-4408-8e99-b9d9c8ab4890)

similar story to [DPL-688](https://github.com/sanger/General-Backlog-Items/issues/278)

**Comment by Sangeetha-Bheeman** [comment]
Tasks:

 - [ ] In deployment project go to  **roles/sprint/files/label_templates** copy **traction_tube_label_template.yml.erb** to create a new label template **sts_tube_15h_40w_2d_template.yml.erb** for STS Squix424 label sized 15h by 40 w.
 - [ ] Change the template x,y coordinates to match the label size.
 
 `[
  {
    "barcodeFields": [
      {
        "x": 2,
        "y": 10,
        "cellWidth": 0.4,
        "barcodeType": "datamatrix",
        "value": "<%= merge_fields[:barcode] %>"
      }
    ],
    "textFields": [
      {
        "x": 11,
        "y": 11,
        "value": "<%= merge_fields[:first_line] %>",
        "font": "proportional",
        "fontSize": 2.5
      },
      {
        "x": 11,
        "y": 15,
        "value": "<%= merge_fields[:second_line] %>",
        "font": "proportional",
        "fontSize": 2.5
      },
      {
        "x": 11,
        "y": 19,
        "value": "<%= merge_fields[:third_line] %>",
        "font": "proportional",
        "fontSize": 2.5
      }
    ]
  }
]`

 - [ ] Deploy to UAT
			`ansible-playbook -i environments/uat/ -vv deploy_print_label_templates.yml`
 - [ ] The print_job request checks for the label template name in the pmb database table labe_templates. So add the new template to pmb database 
        - [ ] Go to pmb UAT server
        - [ ] bundle exec rails c
        - [ ] label_template = LabelTemplate.find_by(name: 'traction_tube_label_template')
        - [ ] label_template.super_dup('sts_tube_15h_40w_2d_template')

**Comment by Sangeetha-Bheeman** [comment]
<img width="1193" alt="Screenshot 2024-02-21 at 12 31 42 pm" src="https://github.com/sanger/General-Backlog-Items/assets/93536758/07485ec8-93c4-4f0b-b21b-be48055893ec">

**Comment by Sangeetha-Bheeman** [comment]
Post request to `http://uat.print-my-barcode.psd.sanger.ac.uk:9292/v2/print_jobs`

<img width="529" alt="image" src="https://github.com/sanger/General-Backlog-Items/assets/93536758/b837ccea-08a4-41db-b837-af65ebb89034">
