### ISSUE TITLE
DPL-1083 As an RVI SSR I would like to be able to find the physical locations of "stock" plates containing a given set of samples or plates so that we can fetch them for processing.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#368]
**User story**
As an RVI SSR I would like to be able to find the physical locations of "stock" plates containing a given set of samples or plates so that we can fetch them for processing.

**Who are the primary contacts for this story**
Anna G
Scott T
Adrianne L
Lesley S
Sara S
Adam M

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Create & Test a SQL query against MLWH that given the barcode for one or more  plates returns the current location of those plates from the labware_location table or returns an empty result for that plate.
- [x] Document the above query on the Confluence "How to Get the Current Location of Labware or Samples from MLWarehouse"
- [x] Create & Test a SQL query against MLWH that given the sample supplier name for one or more samples returns the the sample supplier name, stock plate barcode, well coordinate and current location of the stock plate.
- [x]  Document the above query on the Confluence "How to Get the Current Location of Labware or Samples from MLWarehouse"
- [x] Notify primary contacts and direct to documentation.

**Additional context**
The RVI program will need to locate samples with specific properties such as test date, CT value etc. so that they can be submitted to the RVI pipeline. What the current samples properties are is currently unknown but creating 2 example queries in this user story will give them something to work with.

**Comment by neilsycamore** [comment]
stock plate location is [here](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/How+to+Get+the+Current+Location+of+Labware+or+Samples+from+MLWarehouse#HowtoGettheCurrentLocationofLabwareorSamplesfromMLWarehouse-Findcurrentlocationofstockplatesfromagivenlistofstockplatebarcodes)

stock plate location via sample supplier name is [here](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/How+to+Get+the+Current+Location+of+Labware+or+Samples+from+MLWarehouse#HowtoGettheCurrentLocationofLabwareorSamplesfromMLWarehouse-Findthesamplesuppliername,stockplatebarcode,wellcoordinateandcurrentlocationofthestockplatefromagivenlistofsuppliernames)
