### ISSUE TITLE
Y24-001 As a TL (Tom) I would like our SSL certificate/s updated so that our applications and message queues continue to work after 02/04/2024

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#371]
**Describe the Housekeeping**
As a TL (Tom) I would like our SSL certificate/s updated so that our applications and message queues continue to work after 02/04/2024

**Additional context**
The SSL certificate/s used by our applications will expire in early April. We need to renew it and apply to all our applications and services to keep them functioning.

- Create a service desk ticket to create a new SSL certificate 
- Apply certificate to deployment project
- Deploy applications - following deployment process on the Confluence
- Check updated SSL cert is being served for the applications (below) this can be done on the command line)
- Create a calendar reminder for the team a month before the new SSL cert expires

- [ ] Sequencescape
- [ ] LIMBer
- [ ] Traction
- [ ] Quant Hub
- [ ] Gatekeeper
- [ ] LabWhere
- [ ] Sample Management workflow (Mini LIMS)
- [ ] Samples Extraction
- [ ] Asset Audits
- [ ] Lighthouse HERON
- [ ] Plate Genie
- [ ] Plate Genie RVI
- [ ] Baracoda
- [ ] Print my Barcode
- [ ] Crawler
- [ ] Wrangler
- [ ] RabbitMQ services for MLWH, ToL and Heron

**Comment by andrewsparkes** [comment]
Found this on confluence:
https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Process+For+Requesting+a+New+SSL+Certificate

**Comment by yoldas** [comment]
A few notes:

1. I wrote a script for RT [768940](https://rt.sanger.ac.uk/Ticket/Display.html?id=768940). Although the Confluence page that the script refers to deleted. The script notAfter.py takes an input export.csv to produce an output.csv .
2. The procedure of updating is described in the comments of `update_nginx_certificates.yml` ansible deployment script as well.
3. Single apps are updated by replacing the certificate on the host and reloading nginx.
4. Docker apps are embedding the certificates, that is why they are re-installed. 
5. However, there was a work on this for Heron stack. `update_docker_stack_certificates.yml` . It copies the certificates to the bind-mount location on the host and reloads nginx and rabbitmq. This scheme will be supported for heron stack for the future once a re-deployment is done.

**Comment by yoldas** [comment]
We have created a new branch `y24-001-update-ssl-certificates`

We don't know why there is a `signature.asc` file in the current directory of ssl_certificates role.

We copied the new certificate and inspected using the following command:
`keytool -printcert -file psd_sanger_ac_uk-cert.pem`

Valid from: Tue Mar 19 16:51:10 GMT 2024 until: Fri Apr 18 17:51:10 BST 2025
EMAILADDRESS=psd@sanger.ac.uk (it was t117-lims-bob@sanger.ac.uk last time)
DNS list is the same as the year.

We executed the following for single apps and load balancer certificates:
`ansible-playbook -vD update_nginx_certificates.yml -i environments/uat`

We first saw the following error and applied a fix in the branch.
```
The conditional check 'vars['result']['issuer']['commonName'] == '{{ vars['ssl_issuer_common_name'] }}'' failed. The error was: Conditional is marked as unsafe, and cannot be evaluated.
fatal: [tol-01-uat.psd.sanger.ac.uk]: FAILED! => {}
```

We executed the command again and saw another error:
```
TASK [ssl_certificates : Validate the public certificate and private key match (are compatible)] ***
fatal: [sslb-uat.psd.sanger.ac.uk]: FAILED! => {
    "assertion": "vars['result']['public_key'] == vars['result_privatekey']['public_key']",
    "changed": false,
    "evaluated_to": false
}
```

We also tested and found that they are indeed not compatible by comparing modulus values printed by the following commands:
```
openssl x509 -in psd_sanger_ac_uk-cert.pem -modulus -noout
openssl rsa -in psd_sanger_ac_uk-key.pem -modulus -not
```
Therefore we may need also a copy of the private key that matches the given public key.

**Comment by yoldas** [comment]
Executed:
ansible-playbook -vD update_nginx_certificates.yml -i environments/uat

**Comment by yoldas** [comment]
We have disabled the retention policy plugin in the master branch of samples_extraction because it failed with an exception while trying to create an image version 2.2.3 . The following commands are used for generating a new image after updating the release version:

```
git checkout master
git pull
git tag 'release-2.2.4'
git push origin --tags
```

We have deployed samples_extraction stack to UAT using the command:

`ansible-playbook -vD deploy_samples_extraction.yml -i environments/uat  -e "github_branch=release-2.2.4 full_stack=true"`

We have verified the updated SSL certificate.

**Comment by yoldas** [comment]
We have now finished all SSL updates and checks for UAT, Training, and Production environments. 
The summary of checks is given in [output.csv ](https://gist.github.com/yoldas/f48b16c91069fbe1cad8da338da64db8) .

Notes about the results:

- Each environment and each service was verified separately, for both HTTPS and AMQPS. 
- Heron and Tol RabbitMQ AMQPS ports are checked as well as HTTPS because there is a proxying from nginx to their monitoring UI. Checking HTTPS is not enough for testing. 
- Warehouse RabbitMQ is verified using only HTTPS at port 15671 because it uses the same certificate for UI and AMPQ. 
- Monitor Monit and Kibana services do not use HTTPS at the moment; only HTTP.
- Janitor does not have a relavant interface.
- Traction SMRT Link UAT has its own self-signed certificate at the moment expiring in 2033. 
- I don't know if it has a separate Production deployment for Traction SMRT Link.
- I have also updated sprint and mixtio production certificates.
- I also checked production Stan but I could not understand the format of keyfile (JKS vs P12). It is not updated and it will expire on 2nd of March 2024.
- It is not directly related to the certificate updates but we have a problem with loading CA certificate in docker containers used for gitlab runner.

Notes about updates:
```
# New docker images are built for old docker app releases. Docker apps and full stacks are deployed again because both public and private file changes and embedding of certificates as secrets into docker containers.

# Single apps
ansible-playbook -vD update_nginx_certificates.yml -i environments/training

# Heron stack
ansible-playbook -vD deploy_heron_stack.yml -i environments/training

# Samples Extraction
ansible-playbook -vD deploy_samples_extraction.yml -i environments/training -e "github_branch=release-2.2.4 full_stack=true"

# PMB
ansible-playbook -vD deploy_print_my_barcode.yml -i environments/training -e "github_branch=2.6.2 full_stack=true"

# Tol Stack
ansible-playbook -vD deploy_tol_stack.yml -i environments/training -e "github_branch=1.1.1 full_stack=true"

# Validate
ansible-playbook -vD update_nginx_certificates.yml -i environments/training --tags validate

# Validate 

python notAfter.py export.csv output.csv

# Warehouse RabbitMQ UAT and Prod

ansible-vault decrypt roles/ssl_certificates/certs/current/psd_sanger_ac_uk-key.pem 
cd roles/ssl_certificates/certs/current
scp *.pem ware-uat.psd.sanger.ac.uk:~/
ssh ware-uat.psd.sanger.ac.uk

sudo su

mv psd_sanger_ac_uk-cert.pem /etc/ssl/certs/psd_sanger_ac_uk-cert.pem.new
mv psd_sanger_ac_uk-key.pem /etc/ssl/private/psd_sanger_ac_uk-key.pem.new

cd /etc/ssl/certs/
getfacl psd_sanger_ac_uk-cert.pem > permissions.txt
mv psd_sanger_ac_uk-cert.pem.new psd_sanger_ac_uk-cert.pem
setfacl --restore=permissions.txt
rm permissions.txt

cd /etc/ssl/private/
getfacl psd_sanger_ac_uk-key.pem > permissions.txt
mv psd_sanger_ac_uk-key.pem.new psd_sanger_ac_uk-key.pem
setfacl --restore=permissions.txt
rm permissions.txt

rabbitmqctl eval 'ssl:clear_pem_cache().'

exit
exit

scp *.pem ware-prod.psd.sanger.ac.uk:~/
ssh ware-prod.psd.sanger.ac.uk

sudo su

mv psd_sanger_ac_uk-cert.pem /etc/ssl/certs/psd_sanger_ac_uk-cert.pem.new
mv psd_sanger_ac_uk-key.pem /etc/ssl/private/psd_sanger_ac_uk-key.pem.new

cd /etc/ssl/certs/
getfacl psd_sanger_ac_uk-cert.pem > permissions.txt
mv psd_sanger_ac_uk-cert.pem.new psd_sanger_ac_uk-cert.pem
setfacl --restore=permissions.txt
rm permissions.txt

cd /etc/ssl/private/
getfacl psd_sanger_ac_uk-key.pem > permissions.txt
mv psd_sanger_ac_uk-key.pem.new psd_sanger_ac_uk-key.pem
setfacl --restore=permissions.txt
rm permissions.txt

rabbitmqctl eval 'ssl:clear_pem_cache().'

exit
exit

# Sprint
ssh sprint.psd.sanger.ac.uk
Find password in /sbin/sprint/config/application.properties

openssl pkcs12 -export -in psd_sanger_ac_uk-cert.pem -inkey psd_sanger_ac_uk-key.pem -out psd.p12 -name "psd"
Enter password twice

scp psd.p12 sprint.psd.sanger.ac.uk:/sbin/sprint/config/psd.p12.new
ssh sprint.psd.sanger.ac.uk
cd /sbin/sprint/config/
chmod 500 psd.p12.new
sudo mv psd.p12.new psd.p12
sudo systemctl restart sprint

# Mixtio

scp *pem mixtio.psd.sanger.ac.uk:~/
ssh mixtio.psd.sanger.ac.uk
cd /etc/nginx/ssl/certs
mkdir old
cp -a *pem old/
cp /home/ubuntu/*pem .
rm /home/ubuntu/*pem

# Partial work on Stan Production. Aborted process (I could not continue with creating the stan key file as I am confused about the expected format, JSK vs P12).

openssl x509 -outform der -in psd_sanger_ac_uk-cert.pem -out grl_ca.cer
openssl pkcs12 -export -in psd_sanger_ac_uk-cert.pem -inkey psd_sanger_ac_uk-key.pem -out stan.p12 -name stan
Enter password twice
# I had also another command for adding the entry into P12 file to output the key file but I was not sure. I stopped.
```

**Comment by yoldas** [comment]
I believe the only remaining task is "Create a calendar reminder for the team a month before the new SSL cert expires"
