### ISSUE TITLE
Y24-054 Update barcode template for STS

### ISSUE THREAD

**Issue by neilsycamore** [sanger/General-Backlog-Items#380]
As CASM Lab. manager (Rob T) when printing STS labels using barcode template 15x40 three labels are used each time
![RT800231_labels](https://github.com/sanger/General-Backlog-Items/assets/299768/206fe7b6-74ad-408c-be2f-f50ce95eaeae)

This is very wasteful, can the template be adjusted so that only one label is used?
Previous work carried out by [DPL-1062](https://github.com/sanger/General-Backlog-Items/issues/363)
Relates to [RT800231](https://rt.sanger.ac.uk/Ticket/Display.html?id=800231) in which is mentioned "..Judging from page 31 of the Squix manual (https://www.cab.de/media/pushfile.cfm?file=2771) it may be because the template size setting in the software is too large. From the images DPL-1062 it may be that the template area itself indeed covers three labels. It may be that reducing the overall size of the template, while keeping the same relative co-ordinates that were assigned, will fix the problem?

**Comment by khelwood** [comment]
@BenTopping Height, width, displacement are all in mm. Displacement is the distance between the top of one label and the top of the next one on the roll.
