### ISSUE TITLE
Y24-060 - As developers we would like to create a sanger access token so we do not need to use personal ones which create a risk of being removed [ Deadline - 07/05 ]

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#382]
**Description**
As developers we would like to create sanger access tokens to replace the ones that are currently in use associated with individual team members accounts - these are at risk of being removed, e.g. if the person leaves the institute. It will also prevent failure of the action due to personal tokens expiring.

1. Create a token with 'project' and read:project' permissions, to be used in the org wide secret 'ADD_TO_PROJECT_PAT_ORG_WIDE', to add dependencies to the tecnhical debt board.
2. Create a token with 'read:packages' and 'delete:packages' permissions, to be used in the org wide secret 'REMOVE_OLD_IMAGES', to remove old packages from our docker image repository.

**Who the primary contacts are for this work**
Steve / Katy

**Additional context or information**
[Any other useful context or information that may be useful.](https://www.reddit.com/r/github/comments/1744og1/how_to_generate_an_access_token_for_an/)

**Comment by seenanair** [comment]
@stevieing @KatyTaylor Regarding the generation of the REMOVE_OLD_IMAGES token, it appears that GitHub Actions currently only supports the use of Personal Access Tokens (PATs) for deleting packages. Therefore, converting a PAT to a GitHub App does not seem to be a viable option. This limitation is outlined in detail on this page ([https://docs.github.com/en/packages/learn-github-packages/deleting-and-restoring-a-package]), which states that 'GitHub Packages only supports authentication using a personal access token (classic).

**Comment by seenanair** [comment]
@stevieing @KatyTaylor PAT updated
![Screenshot 2024-04-29 at 11 05 01](https://github.com/sanger/General-Backlog-Items/assets/55585488/f2d3b299-27fc-4f09-a3e2-bdf28be82c1c)
