### ISSUE TITLE
x1201—As PO (Minal) I want an updated report of Stan tickets, to inform of training needs or development requirements

### ISSUE THREAD

**Issue by khelwood** [sanger/General-Backlog-Items#395]
Compile numbers of different categories of recent RT tickets.

**Comment by khelwood** [comment]
@KatyTudor Here is a list of all the tickets that have come in so far in 2024, added to earlier ones that are stalled.

[RTs.xlsx](https://github.com/sanger/General-Backlog-Items/files/15387919/RTs.xlsx)

**Comment by KatyTudor** [comment]
@khelwood thanks david, is there a way to regularly do it (every quarter) or should we put a story in every quarter?

**Comment by khelwood** [comment]
@KatyTudor I don't think there's a way to do it automatically, so feel free to put in a story as necessary.
