### ISSUE TITLE
BUG - modify passwords for warehouse dev and mongo db dev

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#40]
**Describe the bug**
modify passwords for warehouse dev and mongo db dev

- [x] change password for mlwh dev
- [x] change password for monog db dev
- [x] modify psd credentials
- [x] modify psd deployment project
- [x] remove git history
- [x] redeploy

**Comment by emrojo** [comment]
Some services in uat (crawler) seems to not connect to the database. It would need redeploying them.

**Comment by stevieing** [comment]
> Some services in uat (crawler) seems to not connect to the database. It would need redeploying them.

Yes. I didn't get a chance to redeploy them because I needed to sort the production ones.
