### ISSUE TITLE
Y24-115 - Add a reusable workflow to automate the generation of issue title numbers

### ISSUE THREAD

**Issue by SHIV5T3R** [sanger/General-Backlog-Items#406]
**Describe the Housekeeping**

A reusable workflow to be used across public repos where upon a new issue being submitted, the title will automatically be given a prefixed issue number.

This aims to remove the need for a shared spreadsheet to track and update issue numbers. All repos will share an organisation variable which will be incremented upon an issue being made.

**Additional context**

This will affect all actively maintained public repos. There is a linked GitHub application which will be used to generate the tokens for updating issues & organisation variables.

**Comment by yoldas** [comment]
As far as I understand the **issue prefix** is not set automatically, i.e. **Y24** . Are we supposed to set it manually to Y25 next year?

**Comment by SHIV5T3R** [comment]
> As far as I understand the **issue prefix** is not set automatically, i.e. **Y24** . Are we supposed to set it manually to Y25 next year?

https://github.com/sanger/.github/blob/7a2b5491c0508fc1759e1db822c28e6cc83c9cc4/.github/workflows/generate_issue_number.yml#L21

This line will grab the last two digits of the current date, and form Y24. It'll automatically deal with next year without any extra work

**Comment by dasunpubudumal** [comment]
Hi @SHIV5T3R, I noticed that [Issuer](https://github.com/SHIV5T3R/Issuer) is not in Sanger organisation's repositories. Are we moving it into [Sanger](https://github.com/sanger) organisation and then update [`.github/workflows/generate_issue_number.yml`](https://github.com/sanger/.github/blob/d40b9842c8669023d0eaea42d0d2106e2a0fb486/.github/workflows/generate_issue_number.yml#L32C15-L32C35)?
