### ISSUE TITLE
GPL-643 UAT PSD LIMS infrastructure from eta to theta

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#42]
**User story**
GPL-643 | Migrate UAT PSD LIMS infrastructure from eta to theta

**Who are the primary contacts for this story**
Rich L

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] 17 UAT instances (in smrtlink)

**Additional context**
" We aim to have 50% of machines to be migrated to the new platform during September, and the migration to be complete by the end of October " Suggest UAT (~1/3 of our infrastructure) needs to be moved by ~25th Sept

https://docs.google.com/document/d/1WHyTRtaswzwwoGr1r1ds_fBd1ewOBjSX3FzIB7f4mUI/edit?usp=sharing

**Comment by harrietc52** [comment]
**psd-provison**

- [ ] create new workspace
- [ ] create key pairs
- [ ] run packer to create images
- [ ] update variables.tf file (**uat-theta**-....): auth, tenant name, images, floating ips, auth url
- [ ]  run psd-provision for all instances

**psd-config**
- [ ] add a new environment for **uat-theta**  with floating ips
- [ ] run config_all for all hosts
- [ ] run config_docker_hosts for all docker hosts
- [ ] run application specific playbooks
- [ ] copy over any volumes
- [ ] run dns a name, e.g. theta-uat-traction -> floating ip

**psd-deployment**
- [ ] add environment variables
- [ ] check vars for each role
- [ ] deploy playbook for each application
- [ ] cnames
- [ ] run set up scripts

**Comment by harrietc52** [comment]
Had to increase flavour on consul machine as ran out of disk space

**Comment by harrietc52** [comment]
Future TODO
- Clean up shared folder

**Comment by harrietc52** [comment]
Cnames
- move uat to uat-eta
- move uat-theta to uat
- have to pull down psd-deployment
- stop the services

**Comment by harrietc52** [comment]
1. remove the cnames for uat-theta. this will involve running the current uat enviroment with state absent

2. update cname vars for enviroment uat. which involves renames uat-theta.* to uat.*

3. drop cnames for uat-eta 

4. create cnames for uat

**Comment by harrietc52** [comment]
Redeploy ss_workers/ ss_webservers/ saex/ dsm after updating theta var

**Comment by harrietc52** [comment]
Tomorrow:
merge in psd-deployment PR
update ps-config uat naming of folders
ask everyone to test 
reflect
