### ISSUE TITLE
Y24-205 - Add Dependabot dependency updates to Technical debt board

### ISSUE THREAD

**Issue by seenanair** [sanger/General-Backlog-Items#420]
Dependabot PRs are not being updated in the Technical Debt project even though they are passing, because the reusable workflow is only looking at PRs labeled 'depfu'.
 
- Create PRs with a consistent label (e.g., 'dependabot') for Dependabot dependency updates so the labels generated by Dependabot PRs will be consistent across repositories.
- Include the label created as part of dependabot update to [ add_to_tech_debt_project reusable work flow
](https://github.com/sanger/.github/blob/master/.github/workflows/add_to_tech_debt_project_reusable.yml)
- add wrangler to the technical debt board

**Blocking issues**
Describe any other issues or tickets that may be blocking this change.

**Additional context**

**Comment by SHIV5T3R** [comment]
Any PR that gets the "dependencies" label added to it will now be added to the tech debt board.

Next steps:

- Give Depfu PRs the "dependencies" label
- Support repos that need this tech debt action
