### ISSUE TITLE
Y24-208 - As a technical lead (TW) I would like to identify the work required to create the new GSLP RVI pipeline.

### ISSUE THREAD

**Issue by BenTopping** [sanger/General-Backlog-Items#421]
**Description**
As a technical lead (TW) I would like to identify the work required to create the new GSLP RVI pipeline.

The RVI Bait Capture Library pipeline is being moved to GSLP. The existing RVI-BCL limber pipeline will run as an R&D pipeline and we will need to create a new Limber pipeline to support the GSLP RVI BCL pipeline. The proposed pipeline is [available here](https://lucid.app/lucidchart/c1a5c6a6-f4d4-4cfe-b216-e5a8e9dc34ce/edit?viewport_loc=-7352%2C-3425%2C11738%2C8168%2Cs0NUA01kint4&invitationId=inv_14681694-a000-47a8-bca7-104cf2537d80). The aim of this story is to identify any remaining unknowns and create the stories necessary to build the pipeline.

**Who the primary contacts are for this work**
TW, BT, AS, ST, DR

**Acceptance criteria**
- [ ] Finalise the current research and proposed diagram and identify any remaining unknowns.
  - e.g. New purpose prefix (RVIG?), bed verifications, R&D questions.
- [ ] Create the necessary stories to create the pipeline.

**Comment by TWJW-SANGER** [comment]
You have board approval.

**Comment by TWJW-SANGER** [comment]
Mid October target - to provide timeline estimates.

**Comment by BenTopping** [comment]
Pipeline design:
https://lucid.app/lucidchart/c1a5c6a6-f4d4-4cfe-b216-e5a8e9dc34ce/edit?invitationId=inv_14681694-a000-47a8-bca7-104cf2537d80&page=s0NUA01kint4#

Stories:
1. Limber pipeline: https://github.com/sanger/limber/issues/1975
2. Sequencescape config: https://github.com/sanger/sequencescape/issues/4394
3. Limber finalising bed verifications: https://github.com/sanger/limber/issues/1974
