### ISSUE TITLE
GPL-644 TRAINING PSD LIMS infrastructure from eta to theta

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#43]
**User story**
GPL-644 | Migrate TRAINING PSD LIMS infrastructure from eta to theta

**Who are the primary contacts for this story**
Rich

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] 15 UAT instances

**Additional context**
https://docs.google.com/document/d/1WHyTRtaswzwwoGr1r1ds_fBd1ewOBjSX3FzIB7f4mUI/edit?usp=sharing

**Comment by harrietc52** [comment]
**psd-provison**

- [ ] create new workspace 
- [ ] create floating ips
- [ ] key pairs in vars and in openstack
- [ ] run packer to create images - run docker_based_image with ss_test_vars. 
- [ ] SMRTlink
- [ ] update variables.tf file (**uat-theta**-....): auth, tenant name, images, floating ips, auth url
- [ ]  run psd-provision for all instances

**psd-config**
- [ ] add a new environment for **uat-theta**  
- [ ] add key to ssh repo
- [ ] run dns a name, e.g. theta-uat-traction -> floating ip
- [ ] run config_all for all hosts
- [ ] run config_docker_hosts for all docker hosts
- [ ] run psd_config
- [ ] run SMRTlink
- [ ] run application specific playbooks
- [ ] copy over any volumes - (lighthouse reports, crawler backups, kibana logs)

**psd-deployment**
- [ ] set up scripts
- [ ] add environment variables
- [ ] check vars for each role
- [ ] deploy playbook for each application
- [ ] check everything
- [ ] cnames
- [ ] Systems certificate update domain ?

**Comment by harrietc52** [comment]
Create Confluence doc. Everything we run in training, keep a log. To use exactly in production. On confluence

config and deployment
stopping time
remove dns
start dns with different IP
rather than create *-uat-theta


Also todo:
Increase monit disk space in psd-provision
Clean up shared folder in psd-deployment
Check and remove all switching functionality
Remember to reload nginx - update the default for full_deploy

**Comment by harrietc52** [comment]
Step-by-step guide

psd-provision

    Create new workspace `terraform workspace new <prod-theta>`
    Allocate Floating IPs from theta OpenStack <env> tenancy and add them to the variables.tf file
    Update/ check variables in update `variables.tf` file
    Run shared playbook to create security groups etc
    Check ss_prod_vars are correct, these are used for packer
    Run packer to create images - run docker_based_image and smrt image with ss_prod_vars
    Create new environment folder
    Create key pair
    Run playbook terraform apply -var 'user_name=<username>' -var 'password=<password>'


psd-config

For each application:

    Run its respective commands from the deployment_script.sh
     
     
    ...Config for manager (not workers)....
     ssh into samples extraction manager
    Run: sudo docker swarm join-token worker  and copy the token  into environments/training/group_vars/docker_swarm_managers.yml in variable: docker_swarm_worker_token
    ... run config for workers...


Deploy monitos:
