### ISSUE TITLE
Y24-264 - ANOSPP - Options for Addition of Controls on the Lysate plate

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#438]
**Description**
As Michael B, I would like PSD to estimate the stories required and development cost for different possibilities around adding controls to Lysate plates in the ANOSPP pipeline.

Being discussed (not exclusive):
1. Both controls randomised vs one fixed and one randomised (like in Bioscan)
2. No sample movement (losing samples) vs moving displaced samples to the empty wells at location G12 and/or H12 (to save as many samples as possible)
3. Whether lab could periodically run a controls plate through the pipeline and what would be involved in accommodating that

Scott T will be considering the changes required on the lab side e.g. changes required for the Beckman liquid handler robot method.

**Acceptance Criteria**
- [ ] Estimate the number and size of stories to implement the various options.
- [ ] Create the stories (once decision made).

**Who the primary contacts are for this work**
Michael B

**Knowledge or Stake holders**
Scott T
Andrew S
Katy T

**Additional context or information**
ANOSPP is a short pipeline leading into the existing GBS library prep pipeline. See the test in integration suite for anospp for the best idea of how it works. It has some similarity to Bioscan lysate prep, but currently no controls are added. This discussion is about adding functionality to include controls on the Lysate plate.
NB. ANOSPP is not live yet, and config files are still WIP flagged, plus there is a shared bed verification with GBS to deploy changes for (see [PR link](https://github.com/sanger/limber/pull/1817)). The integration suite scenario is currently set to be skipped in UAT because of this bed verification.

See this document about ANOSPP controls discussion [document link](https://docs.google.com/document/d/1jjok54_pEpBv6E8abPfiUj8UFVSOO2GMpYVJK_B4gnk/edit?usp=sharing)

***Point 1 - control randomisation:***
The labware creator `StampedPlateAddingRandomisedControls` in Limber used in Bioscan for creating the **LBSN-96 Lysate** plate is configured in the plate purpose as to number of controls, type, and whether they should be placed in randomised or fixed locations. This may just work as it is for use in ANOSPP, whether they prefer both controls to be randomised or just one (both were tested during Bioscan development). _Check if there is anything Bioscan-specific in the labware creator preventing re-use and estimate cost to change if required._

The API endpoint in Lighthouse for the robot method to fetch the location of the controls may contain Bioscan-specific validations about expected plate purpose type and types of controls. Likely to need a new version of this endpoint for ANOSPP, but that should be minimal effort, _check what's involved_. I believe we tested the endpoint through Postman so we could use a similar approach to testing this. See [PR link](https://github.com/sanger/lighthouse/commit/dce3a8735a498014fc87e21b62548ecaec98bddc).

***Point 2 - sample movement:***
The labware creator `StampedPlateAddingRandomisedControls` in Limber used in Bioscan for creating the **LBSN-96 Lysate** plate decides on the position of the controls and simply displaces any sample in that position (it is not transferred to the child, and the request for Lysate prep is cancelled). What they would prefer is not to lose that displaced sample for each control. They are proposing to leave G12 and H12 empty, to leave space on the Lysate plate to receive the  displaced samples. So the labware creator would determine if G12 and/or H12 are empty (not all plates have both wells empty, some may not have either empty) and move displaced samples into those empty locations. Moved samples would not have their Lysate prep requests cancelled. So when creating the Lysate child plate the transfer requests are modified to account for these movements, rather than simply stamping all (non-displaced) samples across. _Estimate the effort required_ to create a new version of this LabwareCreator that moves displaced samples (extend existing class?).

The API endpoint in Lighthouse would need to respond with the additional information of which samples were moved to where, in addition to the control information. e.g. 

Example 1 (neither positive or negative control are in G12 or H12)
```
{
    "barcode": barcode,
    "sample_moves": { "A12": "G12", "D5": "H12" },
    "positive_control": "A12",
    "negative_control": "D5"
}
```

Example 2 (one of the positive or negative controls are in G12 or H12)
```
{
    "barcode": barcode,
    "sample_moves": { "D5": "H12" },
    "positive_control": "G12",
    "negative_control": "D5"
}
```

Example 3 (both of the positive and negative controls are in G12 or H12)
```
{
    "barcode": barcode,
    "sample_moves": {},
    "positive_control": "G12",
    "negative_control": "H12"
}
```
_Estimate the size of these changes._

***Option 3: Running a controls plate through periodically ***
Scott T suggested an option to validate quality of sequencing results would be to periodically run a 'controls' plate through the pipeline. This could be created by manifest and contain 'control' type samples rather than standard samples. Ideally it would be in place of the initial stock plate and go through the Lysate prep to more accurately receive the same treatment as a normal insect sample plate. Or possibly it could come in as a GBS-96 Stock plate at the start of the GBS library prep part of the pipeline (after lysate plate prep).

_Consider how that would work and what changes might be needed for those 2 entry points_. e.g. if the plate is full of controls, would you want to still replace 2 of them with the controls on the Beckman robot when creating the Lysate plate? What would be needed to skip that control addition step in the labware creator? how would we know this was a controls plate? etc. Could we use a different plate purpose for example, and simply record a stamp of it into the Lysate plate. Or fix the control addition to go into 2 empty wells? Probably need to discuss this further with Scott T as to whether it's a feasible idea from the lab point of view and how it might be set up.

**Comment by TWJW-SANGER** [comment]
I don't see option 3 in the Controls Recommendation section of the "ANOSPP GBS Process Control Technical Evaluation" document. I presume that means we don't need it?

**Comment by KatyTaylor** [comment]
### Draft stories

1a - labware creator - no sample relocation - Small
* Adapt Bioscan labware creator (StampedPlateAddingRandomisedControls) to new context if necessary

1b - labware creator - with sample relocation - Medium
* New labware creator to create lysate plate, based on Bioscan one (StampedPlateAddingRandomisedControls)
* Relocates displaced samples to H12 / G12 if empty

2 - plate states - Small
* Add in new state on Stock plate to track the control addition, as in Bioscan

3a - API endpoint - no sample relocation - Small
* Adapt Bioscan one to run slightly different code based on the ‘purpose’ of the plate it’s given.

3b - API endpoint - with sample relocation - Medium
* New endpoint based on Bioscan one
* Return information about sample moves
* Beckman involvement needed to change endpoint and add behaviour based on different response.

4 - H12 empty manifest - Small
* Check if ‘H12 empty’ manifest would need to be cloned in order for more columns to be added


### What's needed for each option

Option 1a - both randomised, with no sample relocation
* Stories 1a, 2, 3a = 3 small 

Option 1b - both randomised, with sample relocation
* Stories 1b, 2, 3b = 1 small, 2 medium
* Beckman involvement needed

Option 2 - one fixed, one randomised
* Stories 1a, 2, 3a, 4 = 4 small

**Comment by TWJW-SANGER** [comment]
Waiting on decision on which option to implement.

**Comment by SujitDey2022** [comment]
Message from Project Management (Michael B)

"I am pleased to confirm that a final decision has been made and agreed between GSLP and faculty with input from the QMT to ensure the RCA recommendations are fulfilled. Controls will be located in well H12 and be provided by faculty. The positive control will be mosquitoes fed on malarial parasites and negative control will be a well containing no insect, only ethanol and subsequent buffers. Plates will alternate between positive and negative controls in this well (H12) to allow for 2 +ve controls and 2-ve controls within a 384-well batch.
GSLP will manage the control composition of 384 well plates at 96 to 384 consolidation in the GBS pipeline, so there is no need for control addition or control logic to be implemented in the Non-Destructive Extraction (NDE) process.
Controls will be flagged to SSRs in the manifest via the control type column (‘positive’ or ‘negative’), which will then be visible in Limber for Sample Prep and GSLP. This means that no extra LIMS work is expected to be required in order for the pipeline to go live 
"
Fyi... @KatyTaylor @TWJW-SANGER @andrewsparkes
