### ISSUE TITLE
GPL-645 PRODUCTION PSD LIMS infrastructure from eta to theta

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#44]
**User story**
GPL-645 | Migrate PRODUCTION PSD LIMS infrastructure from eta to theta

**Who are the primary contacts for this story**
Rich L

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] 17 instances

**Additional context**
Assumes that GPL-643 (https://github.com/sanger/General-Backlog-Items/issues/42 )done and has been use by operations to test for week? before finalizing production move
needs to be complete by 26th October (see note below)
https://docs.google.com/document/d/1WHyTRtaswzwwoGr1r1ds_fBd1ewOBjSX3FzIB7f4mUI/edit?usp=sharing

**Comment by rl15** [comment]
Pete C wrote (Wednesday, 9 September 2020 at 11:11)

...we have managed to extend our RedHat cover for the Sanger-cloud until the 26th of October.

**Comment by harrietc52** [comment]
Documenting steps performed [here](https://ssg-confluence.internal.sanger.ac.uk/display/PSD/How+to+migrate+FCE+environments)

**Comment by rl15** [comment]
Plan: https://ssg-confluence.internal.sanger.ac.uk/x/uY6eBg
