### ISSUE TITLE
Y24-278 - [BUG] Reduce unreliability of Integration Suite tests

### ISSUE THREAD

**Issue by StephenHulme** [sanger/General-Backlog-Items#444]
**Describe the bug**
Integration suite tests do not run in a reliable and repeatable fashion for a constant setup of Integration Suite, Limber, and Sequencescape versions.

The existing tests should be made more robust so that their output can be better trusted.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Run integration suite tests
2. Run them again
3. Sometimes run them a third time

**Expected behaviour**
That they pass or fail on the same tests each time

**Screenshots**
<img width="1258" alt="Screenshot 2024-08-22 at 10 26 43" src="https://github.com/user-attachments/assets/4a81e035-b8d2-4f47-a715-ea7f29a4f656">

<img width="1302" alt="Screenshot 2024-08-22 at 10 27 14" src="https://github.com/user-attachments/assets/b32bff88-5496-4267-aa22-ad36336a1202">

**Additional context**

**Comment by andrewsparkes** [comment]
@StephenHulme Can you add a link to the PR?
