### ISSUE TITLE
Y24-358 - Setup Test Laptop and Script for CyberArk

### ISSUE THREAD

**Issue by StephenHulme** [sanger/General-Backlog-Items#456]
**Describe the Housekeeping**
Setup a Mac to PSD standards.

Create a script to duplicate a developer's general workflow.

This script should include:

- [x] Common git process
- [ ] Startup times of 
  - [ ] iTerm
  - [ ] Outlook
  - [ ] VSCode
- [x] Ruby install (`rbenv install 3.3.4`) and uninstall
- [x] Running a test suite
Note, this list might change

**Blocking issues**
None

**Additional context**
The script will be run by Tom T, or one of the other members of the security, etc. teams

**Comment by TWJW-SANGER** [comment]
@StephenHulme 
I wonder if this could be broken up a bit so we can provide the security team with something to measure sooner.
(We can always add to the script, but if they have something that measures the problem they can work on resolving that issue in parallel to us extending it.)

I'm not entirely convinced Outlook startup times are significant for us for example. Perhaps pick the worst two or the two that most impact the team?

Happy to discuss.
