### ISSUE TITLE
BUG - Docker stack running out of space

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#46]
**Describe the bug**
When deploying the docker stack it runs out of space and so the deployment errors

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 28] No space left on device
`
**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by harrietc52** [comment]
Updated it when moving from eta top theta. 
Upgraded storage and ram
flavour is now xlarge
