### ISSUE TITLE
Y24-436 - Set up a training database for MLWH

### ISSUE THREAD

**Issue by dasunpubudumal** [sanger/General-Backlog-Items#465]
**User story**

As developers, we need to to set up a separate database in a separate host for MLWH training environment. 

We also want a script written to manually dump records from production into this instance, as is currently being done by the script.

This might require some communication and collaboration with the DBAs.

**Who are the primary contacts for this story**

Dasun P, Stephen I, DBAs

**Who is the nominated tester for UAT**

PSD

**Acceptance criteria**

To be considered successful the solution must include:
- [x] A new host to create a database in.
- [x] A new database `mlwht_mlwarehouse_trainingdata` with the schemas created.
- [x] A script to manually take a database dump from production and extract it into the new database..

**Additional context**

MLWH is populated asynchronously using a queueing mechanism. There are three components that are part of this mechanism overall:

1. **Message publishing application**: Applications like Sequencescape, Traction and `tol-lab-share` publishes records to MLWH. These applications connect to the message broker (discussed below), publishes the message and closes the connection.
2. **RabbitMQ broker**: There's a broker running in the server that runs `unified_warehouse` (discussed below) - you can access its management console via http://ware-uat.psd.sanger.ac.uk:15672/#/. 
3. **`unified_warehouse` consumer**: Consumes messages coming into the broker and persists records in MLWH database. `unified_warehouse` is a thin [Railtie](https://api.rubyonrails.org/classes/Rails/Railtie.html) application that uses an AMQP connection to connect with the broker and `ActiveModel` to connect with the database.

Currently, we have a database `mlwhd_mlwarehouse_proddata` in our UAT host (`mlwhd-db.internal.sanger.ac.uk:3436`) that is populated through a scheduled `mysqldump` script every Monday morning. This script extracts data from **production** and extracts the data into `mlwhd_mlwarehouse_proddata`. However, there is no combination of a message broker and a `unified_warehouse` instance connected to this database to publish messages into the database. Because of this, we can't connect applications running in our training environment to MLWH.

NB: MLWH is not populated through applications other than `unified_warehouse`. This is primarily to maintain a uniform interface to populate the warehouse.

For better separation, this story introduces a new database in a new host including a script that could manually be invoked when necessary.

**Comment by stevieing** [comment]
Supercedes [#336](https://github.com/sanger/General-Backlog-Items/issues/336)

**Comment by dasunpubudumal** [comment]
FreshService ticket link: https://sanger.freshservice.com/a/tickets/14561

**Comment by dasunpubudumal** [comment]
The MLWH Training host details:

- Host: `mlwh-training-db.internal.sanger.ac.uk`
- Port: `3339`

There are three user accounts:

1. `mlwh_training_admin`: Full privileges on all training databases + GRANT privilege
2. `mlwh_training_rw`: Read/Write account 
3. `mlwh_training_ro`: Read-only account
4. `mlwh_admin`: Read-only user for the events database.

Please find the credentials in KeePassXC.

**Comment by dasunpubudumal** [comment]
**Process to dump data from production**

This needs to be done in two steps. It _could_ be done in a single atomic step, but it was advised by the DBAs to carry out this process in two isolated steps for a seamless process.

[`mysqldump`](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html) is the recommended CLI tool that needs to be used for the dumping process. The steps discussed below are the procedures that are recommended to carry out a proper data dumping process.

First, we should extract the schemas without data. We will use `--no-data` option that `mysqldump` ships with.

```bash
mysqldump -h mlwh-training-db.internal.sanger.ac.uk -P 3339 -u mlwh_training_admin -p --no-data mlwarehouse > schema.sql
```

This will create a `schema.sql` file in your local machine (or a remote server; depending on where you invoke this command) which will include the DDL of the schemas.

Second, we should extract the data without explicitly defining the schema. We will use `--no-create-info` option that `mysqldump` ships with.

```bash
mysqldump -h mlwh-training-db.internal.sanger.ac.uk -P 3339 -u mlwh_training_admin -p --no-create-info mlwarehouse table1 table2 > data.sql
```

> [!NOTE]  
> It is a safe bet to include specific tables that you need to dump data from (`table1` and `table2` in the script given above). If it is required to dump **all** the data, do not include any table names.

> [!WARNING]  
> Note that the default `mysqldump` process is a blocking operation (i.e., by default it locks the tables).

**Process to extract data into training**

Since the database has already been created in training, we just need to extract the schemas and data. We might need to purge existing schemas to do this beforehand.

```bash
mysql -h mlwh-training-db.internal.sanger.ac.uk -P 3339 -u mlwh_training_admin -p mlwh_training_mlwarehouse < schema.sql
mysql -h mlwh-training-db.internal.sanger.ac.uk -P 3339 -u mlwh_training_admin -p mlwh_training_mlwarehouse < data.sql
```

**Some statistics collected from the DBAs**

Note that extracting the schemas and data from production mlwh takes about 30 minutes. The resulting file size is about 125GB in size.

Dumping into another instance (e.g., training) usually takes over 12 hours.

> [!IMPORTANT]
> Due to these statistics, it is advisable to carry out this operation in a weekend or a timeframe that has low database I/O load. We **do** already have a database dump periodically taken from the DBAs from production `mlwarehouse` in `mlwhd-db.internal.sanger.ac.uk: 3436` in `mlwhd_mlwarehouse_proddata`.
