### ISSUE TITLE
GPL-652 week-on-week report spice up counts of plates/ samples LH and on site 

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#48]
**User story**
GPL-652 | As heron Stakeholders (Christen, Cristina, Sonia James M & Tanya) we would like the week on week semi automated report to show +ve occupancy (from plate map data) with +ve counts of plates on site 

**Who are the primary contacts for this story**
Neil S
James M (ops)
Christen S (PAM)
Cristina A (PAM)
Sonia G (PAM)

**Acceptance criteria**
To be considered successful the solution must modify the week on week report published here: https://ssg-confluence.internal.sanger.ac.uk/x/DQKRBg 
- [x] Add column to, titled week number, where week number 0 starts 20th July, -1 week commencing 13th July and week 1 27th July onwards
- [x] Show count positives per plate from the plate map data (ignoring whats on site)
- [x] Add note to page that date used for plates on site changed from test date to scanned into LabWhere
- [x] Add glossary to page to define the detail behind a column heading eg Date on site =  as declared into LabWhere, as a result of Box manifest being uploaded. The plate may not yet be on site but in transit from LH labs.
- [x] Eduardo to code review

**Detail**

- Col 1: Week count (NEW)
- Col 2: Week beginning date 
- For each lab in order (AP,  CB, GWL, MK) 
- Count neg plates on site (0 +ve samples o plate)
- Count positive plate on site (1 or +ves on plate)
- Count of all positive samples from plate map (in mongo now) (REINSTATE)
- Avg Count of all positive samples from plate map (REINSTATE)
- Count of all positive samples on site (scanned into Labwhere) 
- Avg count of all positive samples on site
As above all sites

**Additional context**
Report takes ~30 minutes to run (without enhancement requested above)
Ideally report will be run towards COP on Friday ready for Monday morning meting at 10.

**Comment by neilsycamore** [comment]
Eduardo
I've annotated were I THINK the code needs explanation
code is here
https://github.com/sanger/usg_scripts/blob/master/Production_scripts/Heron/Heron_reports/LH_weekly_on_site_off_site_report.rb

report is posted here
https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Week+on+week+count+for+Lighthouse+laboratory+samples

**Comment by emrojo** [comment]
From code review:

- Can we add a glossary inside the code itself as a coment with the definition of important variables in code, like: nbc, pbc, sc,...
- The procedure to run the report involves some manual tasks, like, downloading current data and then move some files to be able to run it under labwhere context; would it be better if we upload these files into a temporary table in a SQL database so you can query labwhere and the values together with SQL?

**Comment by neilsycamore** [comment]
Yes a glossary would be good - I'll add that.

I'm hoping that GPL-579 Expose LH plate map metadata to PAM will do this? Though I may need  some help writing the weekly data aggregation to get it to look like the report at present!

**Comment by neilsycamore** [comment]
Have added glossary to the get_row method as this is where it gets very confusing.
Else where I have removed abbreviations and expanded dates to scanned in and tested to make them more self explaining
