### ISSUE TITLE
GPL-655 Beckman SAT: Test 7.1 a&b LIMS communication test (ping)

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#49]
**Description**
GPL-655 | As  development team we need to test successful connection via ping between LIMS host in FCE and Biomek/ SAMI controller PC to varify there is a viable channel for API calls 

**Who the primary contacts are for this work**
Rich L
Tim C
Lesley S

**Acceptance criteria**

Establish a connection to the robot **from** LIMS via Sanger Flexible Compute Environment (FCE) e.g. SSH ping.
Establish a connection from the robot **to** LIMS via Sanger Flexible Compute Environment (FCE) e.g. SSH ping.

Purpose of ‘a’ and ‘b’ above is to demonstrate that the Biomek computer and Sanger server PC are able to communicate. Change for their wording?

(Thurston, 2020)

**Additional context or information**
Any other useful context or information that may be useful.

**References**
Scott Thurston, S. (Tuesday, 22 September 2020 at 11:33) Subject: Beckman cherry-picking SAT, email to Rich L, Tim C & Lesley S.

**Comment by JamesGlover** [comment]
Is this still relevant given the proposed integration via DART?
