### ISSUE TITLE
GPL-688 As a development team we need to ascertain whether we can update/query the DART database

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#61]
**User story**
As a development team we need to ascertain whether we can update/query the DART database

**Who are the primary contacts for this story**
Steve / Andrew / Katy

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] we need to be able to insert data into the DART database
- [ ] we need to be able to retrieve data from the DART database

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by rl15** [comment]
Pull request 'dart' in on psd credentails

**Comment by stevieing** [comment]
Branch for Sequencescape side ready https://github.com/sanger/sequencescape/tree/GPL-675-sprint

**Comment by stevieing** [comment]
Stored procedures are not ready yet.
