### ISSUE TITLE
GPL-687 As a development team we need to understand how to best manage events for cherrypicking

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#62]
**Description**
As a development team we need to understand how to best manage events for cherrypicking.

**Who the primary contacts are for this work**
Andrew, Eduardo, Chris, Alex, James

**Knowledge or Stake holders**
PAM / R&D / PSD

**Additional context or information**
See https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Cherrypicking+Events

**Comment by JamesGlover** [comment]
I've prepared a brief summary about the existing events, but long and short of it is that there is little value here. 

Existing events:
1) Generated via `RobotVerificationsController#download`
2) Call to `Batch.robot_verified!`
3) Generates a `LabEvent` which in turn generates a `BroadcastEvent::LabEvent` This ends up in the event warehouse:

event_type: robot_verified

subjects:

These mostly seem to be geared up for sequencing, form a quick oggle, I think we get:
1) All the samples in the batch, not just those picked.
2) All the studies associated with the batch, not just those picked
3) And stock plates associated with all source plates in the batch

Summary:

1) Existing pick code isn't hugely useful for our purposes as we're not planning to use any of the systems it hooks into.
2) The existing event name isn't really relevant. We're not verifying anything.
3) Existing even subjects are broadcast at the entire batch level. This behaviour is wrong, and has been for a while. Even pre-mega-batch it was possible to process destination plates in separate picks.
4) Existing subjects are a little limited, although sample does seem to be the preferred level of break-down.
5) `BroadcastEvent` itself is still a useful tool for generating the actual event messages.

**Comment by JamesGlover** [comment]
From informal discussions on zoom, it sounds like we want to capture:
1) Destination plate picked, ideally linked to the source plates.
2) Source plates that were loaded onto the robot
3) Some means of identifying source plates loaded onto the robot, and targeted for destruction~
4) ?Some means of identifying source plates loaded onto the robot but left in the cytomat?

Source plates don't exist in Sequencescape, so the only representation of these is in labwhere (which has uuids). As a result, source plate events may be generated via labwhere.

**Comment by JamesGlover** [comment]
Relevant issue: https://github.com/sanger/General-Backlog-Items/issues/76
