### ISSUE TITLE
GPL-715 As developers we need to confirm the label size dimensions

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#64]
**Description**
We need to confirm label size dimensions for:
- width
- height
- displacement

for:
- 384 well plate
- 96 well plate
- tube

**Who the primary contacts are for this work**
Steve / Harry

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Refer to sprint existing sizes in printers.xml file

**Comment by harrietc52** [comment]
SPRINT current labels sizes are:

**Tiny**
displacement: 12
height: 9
width: 28

**Thin**
displacement: 11
height: 8
width: 90

**Slide**
displacement: 22
height: 19
width: 23

**Comment by harrietc52** [comment]
Lesley S on 22nd
"The labels sizes are the same as those used in the Toshiba printers."

**Comment by stevieing** [comment]
From print my barcode:

plate label type:
`{"feed_value":"008","fine_adjustment":"04","pitch_length":"0110","print_width":"0920","print_length":"0080","name":"Plate"}`

384 plate label type:
`{"feed_value":"008","fine_adjustment":"04","pitch_length":"0130","print_width":"0680","print_length":"0060","name":"plate - 6mm"}`

Tube:
`{"feed_value":"008","fine_adjustment":"10","pitch_length":"0430","print_width":"0300","print_length":"0400","name":"Tube"}`

**Comment by harrietc52** [comment]
Label Size Dimentions

384 well plate
height: 6, width: 68, displacement: 13

96 well plate
height: 8, width: 92, displacement: 11

tube
height: 40, width: 30, displacement: 43

**Comment by harrietc52** [comment]
Questions:
Confirm label text
Confirm barcode rotation
Confirm not expecting tube lid label

**Comment by harrietc52** [comment]
LIMBER label templates mock ups [here](https://lucid.app/lucidchart/9b806fe3-4722-4ba0-bed9-2499d7833c1a/edit?beaconFlowId=F85418E641C92960&page=0_0#?folder_id=home&browser=icon)
