### ISSUE TITLE
GPL-700 - As a developer I need to create a label template for 96 well plates

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#65]
**User story**
As a developer I need to create a label template for 96 well plates

- [x] confirm what needs to appear on the label
- [x] confirm what position each field needs to appear
- [x] create label template file
- [x] add template file to config
- [x] tested

**Who are the primary contacts for this story**
Steve / Harry

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] we need to be able to print multiple labels sequentially using the template on the correct printer and they should look right
- [x] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by KatyTaylor** [comment]
Screenshots from testing 2 96 well templates today

plate_96.yml.erb

<img width="1283" alt="Screenshot 2020-10-30 at 14 44 56" src="https://user-images.githubusercontent.com/10407809/97725703-64af7800-1ac6-11eb-99cf-f3ed6363aa8e.png">

plate_96_pmb.yml.erb (matching exact coordinates on existing pmb template)

![Uploading Screenshot 2020-10-30 at 14.45.08.png…]()
