### ISSUE TITLE
GPL-702 - As a user I need to be able to print labels from Limber to the Squix printer for the tailed workflow

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#68]
**User story**
As a user I need to be able to print labels from Limber to the Squix printer for the tailed workflow

**Who are the primary contacts for this story**
Steve / Harry

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] I should be able to print a 384 well plate label from quad stamping
- [x] I should be able to print a tube label from library creation
- [x] I should be able to print a 96 label from the 96 pipeline
- [x]  request to sprint client gem, containing printer name, label template name and data fields including barcode

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by KatyTaylor** [comment]
Check:
- [ ] Is ok to have a switchover where Heron pipelines start using only Squix printers, and can no longer print from old ones.
- [ ] Modify Heron pipeline & Heron Tailed pipeline, or just tailed?

**Comment by harrietc52** [comment]
Pull Requests:

- [ ] ss client api [here](https://github.com/sanger/sequencescape-client-api/compare/GPL-702-add-print_service-attr?expand=1)

**Comment by harrietc52** [comment]
PR [here](https://github.com/sanger/limber/pull/545)

**Comment by harrietc52** [comment]
Script for running on SS deployment
- [ ] UAT
- [ ] Prod

```
tube = BarcodePrinterType.find_by(name: "1D Tube")
plate_96 = BarcodePrinterType.find_by(name: "96 Well Plate")
plate_384_double = BarcodePrinterType.find_by(name: "384 Well Plate Double")

BarcodePrinter.create!(name: 'heron-bc1', print_service: 'SPrint', barcode_printer_type: plate_96)
BarcodePrinter.create!(name: 'heron-bc2', print_service: 'SPrint', barcode_printer_type: plate_384_double)
BarcodePrinter.create!(name: 'heron-bc3', print_service: 'SPrint', barcode_printer_type: plate_96)
BarcodePrinter.create!(name: 'heron-bc4', print_service: 'SPrint', barcode_printer_type: plate_384_double)
BarcodePrinter.create!(name: 'heron-bc5', print_service: 'SPrint', barcode_printer_type: plate_96)
BarcodePrinter.create!(name: 'heron-bc6', print_service: 'SPrint', barcode_printer_type: plate_384_double)
BarcodePrinter.create!(name: 'heron-bc7', print_service: 'SPrint', barcode_printer_type: tube)

```
