### ISSUE TITLE
GPL-705 - As a developer I need a gem to interact with SPrint

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#70]
**User story**
As a developer I need a gem to interact with SPrint

**Who are the primary contacts for this story**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] gem is called sprint client gem
- [x] it will contain a model that can be called from an app
- [x] the library will convert input to correct Graph QL format and send request to sprint
- [x] configuration files containing label templates can be access from a specific local folder (determined by psd-deployment)
- [x] add test for method

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by emrojo** [comment]
GPL-705 and GPL-706 both define a library. What is your opinion if we define  a client gem so we can add it to other apps when we need to print with new printers?

**Comment by harrietc52** [comment]
https://github.com/sanger/sprint_client/

**Comment by harrietc52** [comment]
Tests PR [here](https://github.com/sanger/sprint_client/pull/1)
