### ISSUE TITLE
GPL-706 - As a developer I need psd-deployment to add label template config to Limber

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#71]
**User story**
As a developer I need psd-deployment to add label template config to Limber

**Who are the primary contacts for this story**
Steve / Harry

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] new role sprint
- [x] label templates are defined
- [x] label templates are added to a specific location for Limber on deployment
- [x] test with deployed code
- [x] add finalised label templates

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by harrietc52** [comment]
PR GitLab psd-deployment 131
