### ISSUE TITLE
GPL-713 As developers we would like to create some kind of error handling so users can troubleshoot issues 

### ISSUE THREAD

**Issue by stevieing** [sanger/General-Backlog-Items#78]
**User story**
As developers we would like to create some kind of error handling so users can troubleshoot issues. For example:
- if a plate does not have a plate map but is being processed as a source plate
- if the plate map was not processed correctly so it does not have any DART data

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
This may be down to Beckman to incorporate into their method. Users have to physically be able to identify the plates, so may need the stack locations displayed end of run.

**Comment by andrewsparkes** [comment]
Superceded by box buster story GPL726.
