### ISSUE TITLE
GPL-719 Removal of obsolete functionality from Lighthouse and UI [Heron]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/General-Backlog-Items#82]
**User story**
After changeover to the new cherrypicking design, some of the functionality in Lighthouse and Lighthouse-UI is likely to be obsolete and can be removed.

**Who are the primary contacts for this story**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
Cherrypicking, source plate creation in Sequencescape, Cog Uk Id lookup, etc.

**Comment by KatyTaylor** [comment]
Sentinel is still being used, closing this issue
