### ISSUE TITLE
GPL-730 [Improvement] Standarize deployment command (s) (Dulipcate of hot reload)

### ISSUE THREAD

**Issue by emrojo** [sanger/General-Backlog-Items#84]
Some projects (Limber, Labwhere) require an extra flag for deployment named ```full_deploy=true```, while other projects don't need it. This is caused because in this projects we have an issue that doesn't allow to stop and start all puma workers on deployment.
If we want to use full_deploy=true mandatorily, then we should give it the right default value so we don't have to pass it as an argument when we want to deploy. The way it is now is prone to error as we can forget if we have to use the full_deploy flag in the project we are deploying in that moment.

Acceptance criteria:
- [ ] Give a default value for ```full_deploy flag``` in psd deployment for all projects, so we dont have to specify it when we want to deploy normally

**Comment by JamesGlover** [comment]
Probably work working out why puma hot-reloading isn't working properly as well, better to fix that if we can.
Sequencescape always had issues, but its new for Limber.

I know Luca thought it was related to rebuilding the binstubs on puma version updates, but from my understanding of the way puma manages hot-reloads, this should be possible to solve.

**Comment by KatyTaylor** [comment]
Spun out James's comment into new issue - https://github.com/sanger/General-Backlog-Items/issues/136
