### ISSUE TITLE
GPL-780 Decommision VM psd2* (E: L, V: 4)

### ISSUE THREAD

**Issue by harrietc52** [sanger/General-Backlog-Items#97]
**Summary**

Tasks to follow up on email Subject: "Re: Plan to decomisioning last of the PSD tin and VM's", on Tuesday, 1 September 2020 at 14:16.

Following the agreed 4 step plan:

1. Decommission:
- [x] Psd2a
- [x] Psd2b
- [x] Psd2d
- [x] Psd2e

2. Decommission and migrate PMB to FCE
- [x] psd2j

3. Decommission and migrate Warehouse 2 & UKBB events to FCE
- [ ] Psd2c - https://github.com/sanger/General-Backlog-Items/issues/137

4. Decommission and migrate OLD traction to FCE - https://github.com/sanger/traction/issues/108
- [ ] Psd2h (UAT)
- [ ] Psd2i (PROD)

**Who are the primary contacts for this story**
Harry
Steve
Phil

**Additional context**
Confluence doc [here](https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=111052602)
Original story https://github.com/sanger/sequencescape/issues/2867

**Comment by stevieing** [comment]
closed in favour of DPL-218 and DPL-219
