### ISSUE TITLE
GPL-740-c Update Recorded Query for Sample Tracking

### ISSUE THREAD

**Issue by Chris-Friend** [sanger/General-Backlog-Items#98]
**User story**
Update the relevant queries on https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Warehouse+query+for+sample+tracking with the new control rules as outlined in https://github.com/sanger/crawler/issues/150

**Who are the primary contacts for this story**
Chris F

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Query updated with new control exclusions
- [x] Inform the appropriate contacts

**Comment by Chris-Friend** [comment]
@KatyTaylor would it be possible for you to look at the relevant confluence query I have updated as way of code reviewing this?

**Comment by KatyTaylor** [comment]
Yep looks good
